use crate::component::{AssetContent, AssetOutput, ResourcePackComponent};
use crate::components::font::{BitmapFont, BitmapProvider};
use crate::sprite::{Color, gen_bar_png};

/// A bitmap-font progress bar whose sprite strip is **generated at build time**
/// from color parameters rather than copied from a user-supplied PNG.
///
/// Constructed via the [`hud_bar!`] macro with a `create!(...)` expression in
/// the `texture:` field:
///
/// ```rust,ignore
/// use sand_macros::hud_bar;
///
/// hud_bar!(
///     name: "health",
///     texture: create!(fill: 0xFF4444FF, empty: 0x333333FF),
///     steps: 10,
///     height: 14,
///     ascent: 14,
/// );
/// ```
///
/// The macro expands to a [`GenHudBar`] instead of a [`HudBar`] when it
/// detects the `create!(...)` call.
///
/// [`hud_bar!`]: sand_macros::hud_bar
/// [`HudBar`]: crate::HudBar
pub struct GenHudBar {
    /// Unique identifier used in diagnostics and codepoint derivation.
    pub name: &'static str,

    /// Destination sub-path inside `assets/<namespace>/textures/` (without
    /// extension), e.g. `"font/health_bar"`.
    pub texture_dest: &'static str,

    /// Override the first unicode codepoint for the bar frames.
    ///
    /// When `None` (the default), the codepoint is derived automatically from
    /// the component name via [`bar_base_codepoint`](crate::bar_base_codepoint).
    pub unicode_start: Option<char>,

    /// Number of frames in the generated sprite strip.
    pub steps: u32,

    /// Rendered glyph height in pixels. Also used as `frame_width` when
    /// `frame_width` is `0`.
    pub height: i32,

    /// Vertical offset from the baseline to the top of the glyph.
    pub ascent: i32,

    /// Name of the font file (without extension).
    pub font: &'static str,

    /// Packed `0xRRGGBBAA` color for the filled portion of each frame.
    pub fill: u32,

    /// Packed `0xRRGGBBAA` color for the empty / background portion.
    pub empty: u32,

    /// Pixel width of each individual frame.
    ///
    /// A value of `0` means "use `height`" (produces square frames).
    pub frame_width: u32,
}

impl GenHudBar {
    fn chars_row(&self) -> String {
        let start = self
            .unicode_start
            .map(|c| c as u32)
            .unwrap_or_else(|| crate::unicode::bar_base_codepoint(self.name));
        (start..start + self.steps)
            .filter_map(char::from_u32)
            .collect()
    }

    fn effective_frame_width(&self) -> u32 {
        if self.frame_width == 0 {
            // Default to 2× height for a pill-proportioned bar.
            self.height as u32 * 2
        } else {
            self.frame_width
        }
    }
}

impl ResourcePackComponent for GenHudBar {
    fn assets(&self, namespace: &str) -> Vec<AssetOutput> {
        let chars_row = self.chars_row();
        let file_ref = format!("{}:{}.png", namespace, self.texture_dest);
        let frame_width = self.effective_frame_width();

        // Font JSON (same structure as HudBar).
        let font = BitmapFont {
            font_name: self.font,
            provider: BitmapProvider {
                file: file_ref,
                height: self.height,
                ascent: self.ascent,
                chars: vec![chars_row],
            },
            // No file to copy — we'll attach generated bytes below.
            texture_src: None,
            texture_dest: self.texture_dest,
        };

        let mut outputs = font.assets(namespace);

        // Generated PNG bytes.
        let fill = Color::from_u32(self.fill);
        let empty = Color::from_u32(self.empty);
        let png_bytes = gen_bar_png(fill, empty, self.steps, frame_width, self.height as u32);
        let tex_path = format!("assets/{}/textures/{}.png", namespace, self.texture_dest);
        outputs.push(AssetOutput {
            path: tex_path,
            content: AssetContent::Bytes(png_bytes),
        });

        outputs
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::AssetContent;

    fn test_gen_bar() -> GenHudBar {
        GenHudBar {
            name: "health",
            texture_dest: "font/health_bar",
            unicode_start: None,
            steps: 3,
            height: 9,
            ascent: 9,
            font: "default",
            fill: 0xFF4444FF,
            empty: 0x333333FF,
            frame_width: 0,
        }
    }

    #[test]
    fn assets_produces_font_and_bytes() {
        let bar = test_gen_bar();
        let outputs = bar.assets("my_pack");
        assert_eq!(outputs.len(), 2);

        // Font JSON
        assert_eq!(outputs[0].path, "assets/my_pack/font/default.json");
        match &outputs[0].content {
            AssetContent::Json(v) => {
                assert_eq!(v["providers"][0]["type"], "bitmap");
            }
            _ => panic!("expected Json"),
        }

        // Generated PNG bytes
        assert_eq!(
            outputs[1].path,
            "assets/my_pack/textures/font/health_bar.png"
        );
        match &outputs[1].content {
            AssetContent::Bytes(b) => {
                // PNG magic number
                assert_eq!(&b[..8], b"\x89PNG\r\n\x1a\n");
            }
            _ => panic!("expected Bytes"),
        }
    }

    #[test]
    fn explicit_unicode_start_is_respected() {
        let bar = GenHudBar {
            unicode_start: Some('\u{E200}'),
            ..test_gen_bar()
        };
        let outputs = bar.assets("ns");
        match &outputs[0].content {
            AssetContent::Json(v) => {
                let chars = v["providers"][0]["chars"][0].as_str().unwrap();
                assert_eq!(chars.chars().next().unwrap(), '\u{E200}');
            }
            _ => panic!(),
        }
    }
}
