use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use colored::Colorize;

use crate::config::SandConfig;

pub struct RunArgs {
    /// JVM max heap size, e.g. "4G" or "2048M". Used for both -Xmx and -Xms.
    pub ram: String,
    /// Write `online-mode=false` to server.properties for offline testing.
    pub offline: bool,
    /// Skip `sand build`; use whatever is already in dist/.
    pub no_build: bool,
}

pub fn run(args: RunArgs) -> Result<()> {
    // ── 1. Read sand.toml ────────────────────────────────────────────────────
    let config_path = std::env::current_dir()?.join("sand.toml");
    if !config_path.exists() {
        bail!("sand.toml not found — run `sand run` from your project root");
    }
    let config: SandConfig =
        toml::from_str(&std::fs::read_to_string(&config_path)?)
            .context("failed to parse sand.toml")?;

    let mc_version = resolve_mc_version(&config.pack.mc_version);

    // ── 2. Build the datapack ────────────────────────────────────────────────
    if args.no_build {
        println!("{}", "Skipping build (--no-build)".dimmed());
    } else {
        crate::build_cmd::run(false)?;
    }

    // ── 3. Download / verify server jar ─────────────────────────────────────
    println!(
        "{} server jar for Minecraft {}...",
        "Checking".cyan().bold(),
        mc_version.yellow()
    );
    let jar_path = sand_build::ensure_server_jar(&mc_version)
        .with_context(|| format!("failed to get server jar for Minecraft {mc_version}"))?;
    println!("  {} {}", "jar:".dimmed(), jar_path.display().to_string().white());

    // ── 4. Set up dist/server/ ───────────────────────────────────────────────
    let server_dir = PathBuf::from("dist").join("server");
    std::fs::create_dir_all(&server_dir)
        .context("failed to create dist/server/")?;

    // ── 5. Accept EULA ───────────────────────────────────────────────────────
    let eula_path = server_dir.join("eula.txt");
    if !eula_path.exists() {
        std::fs::write(
            &eula_path,
            "# EULA accepted automatically by `sand run`\n\
             # https://aka.ms/MinecraftEULA\n\
             eula=true\n",
        )
        .context("failed to write eula.txt")?;
        println!("  {} eula.txt (eula=true)", "Wrote".dimmed());
    }

    // ── 6. Write server.properties ───────────────────────────────────────────
    let props_path = server_dir.join("server.properties");
    if !props_path.exists() {
        let online_mode = if args.offline { "false" } else { "true" };
        std::fs::write(
            &props_path,
            format!(
                "# Generated by `sand run` — edit as needed\n\
                 level-name=world\n\
                 online-mode={online_mode}\n\
                 spawn-protection=0\n"
            ),
        )
        .context("failed to write server.properties")?;
        println!(
            "  {} server.properties (online-mode={online_mode})",
            "Wrote".dimmed()
        );
    }

    // ── 7. Sync datapack into world/datapacks/ ───────────────────────────────
    let namespace = &config.pack.namespace;
    let src  = PathBuf::from("dist").join(namespace);
    let dest = server_dir.join("world").join("datapacks").join(namespace);

    if !src.exists() {
        bail!(
            "dist/{namespace}/ does not exist — run `sand build` first \
             (or remove --no-build)"
        );
    }

    sync_dir(&src, &dest)
        .with_context(|| format!("failed to sync datapack to {}", dest.display()))?;
    println!(
        "  {} datapack → {}",
        "Synced".dimmed(),
        dest.display().to_string().white()
    );

    // ── 8. Launch the server ─────────────────────────────────────────────────
    println!(
        "\n{} Minecraft {} with {}RAM...\n",
        "Starting".green().bold(),
        mc_version.yellow(),
        format!("{}  ", args.ram).white()
    );

    let ram = &args.ram;
    let status = std::process::Command::new("java")
        .arg(format!("-Xmx{ram}"))
        .arg(format!("-Xms{ram}"))
        .arg("-jar")
        .arg(&jar_path)
        .arg("nogui")
        .current_dir(&server_dir)
        .status()
        .context(
            "failed to start Java — make sure Java 21+ is on your PATH (`java -version`)",
        )?;

    if !status.success() {
        bail!("server exited with status {status}");
    }

    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Resolve "latest" to the actual Mojang release version.
fn resolve_mc_version(mc_version: &str) -> String {
    if mc_version == "latest" {
        sand_build::latest_release_version()
    } else {
        mc_version.to_string()
    }
}

/// Recursively copy all files from `src` to `dest`, overwriting existing files.
///
/// This mirrors the datapack directory so that every `sand run` picks up the
/// latest build without having to restart the server process setup.
fn sync_dir(src: &Path, dest: &Path) -> Result<()> {
    std::fs::create_dir_all(dest)?;
    for entry in walkdir::WalkDir::new(src) {
        let entry = entry?;
        let rel = entry.path().strip_prefix(src)?;
        let target = dest.join(rel);
        if entry.file_type().is_dir() {
            std::fs::create_dir_all(&target)?;
        } else {
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::copy(entry.path(), &target)?;
        }
    }
    Ok(())
}
