use std::io::{BufReader, BufWriter, Read};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use colored::Colorize;

use crate::config::SandConfig;
use crate::console::OutputMode;

pub struct RunArgs {
    /// JVM max heap size, e.g. "4G" or "2048M". Used for both -Xmx and -Xms.
    pub ram: String,
    /// Write `online-mode=false` to server.properties for offline testing.
    /// Overrides a `sand.build.rs` `ServerConfig`'s `online_mode`.
    pub offline: bool,
    /// Skip `sand build`; use whatever is already in dist/.
    pub no_build: bool,
    /// How to present the Minecraft server's log output.
    pub server_log: OutputMode,
    /// Build profile passed to `sand.build.rs` (issue #317). Defaults to
    /// `"dev"`; has no effect on projects without a `sand.build.rs`.
    pub profile: String,
}

/// 🖥️ Server (host) only — the local dev-server settings a `sand.build.rs`
/// script's `ServerConfig` produces. Read from
/// `dist/.sand-server-config.json` (written by `sand build`, never inside
/// `dist/<namespace>/`) and applied only to `sand run`'s local server.
#[derive(Debug, serde::Deserialize)]
struct ServerConfigFile {
    /// `None` when the project's `sand.build.rs` configured only a fixed
    /// `World::seed` and no `ServerConfig` at all — the file still exists
    /// so `sand run` can read the seed, but every `ServerConfig` field
    /// falls back to its vanilla default in that case.
    #[serde(default)]
    view_distance: Option<u8>,
    #[serde(default)]
    simulation_distance: Option<u8>,
    #[serde(default)]
    difficulty: Option<String>,
    #[serde(default)]
    online_mode: Option<bool>,
    #[serde(default)]
    world_reset_policy_always_reset: Option<bool>,
    /// 🖥️ Server (host) only, despite coming from `World::seed` — see the
    /// module-level explanation on `run_worldbuild`/`World::seed`. Applied
    /// as `server.properties`' `level-seed` on first launch only.
    #[serde(default)]
    seed: Option<i64>,
}

/// The `server.properties` values `sand run` writes on first launch,
/// resolved from `--offline`, a `sand.build.rs` `ServerConfig` (if any), and
/// vanilla defaults. Pulled out as a pure function so the precedence rules
/// (`--offline` always wins over `ServerConfig::online_mode`; everything
/// else falls back to vanilla defaults when there's no `ServerConfig`) are
/// unit-testable without spawning a server.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ResolvedServerProperties {
    online_mode: bool,
    view_distance: u8,
    simulation_distance: u8,
    difficulty: &'static str,
    /// `Some` only for a fixed `World::seed`; `None` (vanilla's own random
    /// seed) omits the `level-seed` line entirely rather than writing an
    /// empty one — both mean "let the server pick," but omitting matches
    /// what a hand-written server.properties would look like.
    seed: Option<i64>,
}

impl ResolvedServerProperties {
    fn resolve(offline_flag: bool, server_config: Option<&ServerConfigFile>) -> Self {
        let online_mode = if offline_flag {
            false
        } else {
            server_config.and_then(|s| s.online_mode).unwrap_or(true)
        };
        Self {
            online_mode,
            view_distance: server_config.and_then(|s| s.view_distance).unwrap_or(10),
            simulation_distance: server_config
                .and_then(|s| s.simulation_distance)
                .unwrap_or(10),
            difficulty: match server_config.and_then(|s| s.difficulty.as_deref()) {
                Some("peaceful") => "peaceful",
                Some("easy") => "easy",
                Some("hard") => "hard",
                _ => "normal",
            },
            seed: server_config.and_then(|s| s.seed),
        }
    }

    fn to_properties_text(self) -> String {
        let mut text = format!(
            "# Generated by `sand run` — edit as needed\n\
             level-name=world\n\
             online-mode={}\n\
             spawn-protection=0\n\
             view-distance={}\n\
             simulation-distance={}\n\
             difficulty={}\n",
            self.online_mode, self.view_distance, self.simulation_distance, self.difficulty
        );
        if let Some(seed) = self.seed {
            text.push_str(&format!("level-seed={seed}\n"));
        }
        text
    }
}

pub fn run(args: RunArgs) -> Result<()> {
    // ── 1. Read sand.toml ────────────────────────────────────────────────────
    let config_path = std::env::current_dir()?.join("sand.toml");
    if !config_path.exists() {
        bail!("sand.toml not found — run `sand run` from your project root");
    }
    let config: SandConfig = toml::from_str(&std::fs::read_to_string(&config_path)?)
        .context("failed to parse sand.toml")?;

    let mc_version = resolve_mc_version(&config.pack.mc_version);

    // ── 2. Build the datapack ────────────────────────────────────────────────
    if args.no_build {
        println!("{}", "Skipping build (--no-build)".dimmed());
    } else {
        crate::build::run_with_options(crate::build::BuildOptions {
            release: false,
            resourcepack: false,
            print_timings: false,
            explain_rebuild: false,
            profile: args.profile.clone(),
        })?;
    }

    // ── 2b. Read any ServerConfig a sand.build.rs produced (issue #317) ─────
    // 🖥️ Server (host) only — never part of the datapack. Only present when
    // the project has a sand.build.rs whose SandBuild configured a
    // ServerConfig for this profile.
    let server_config_path = PathBuf::from("dist").join(crate::build::SERVER_CONFIG_FILE_NAME);
    let server_config: Option<ServerConfigFile> = if server_config_path.exists() {
        let raw = std::fs::read_to_string(&server_config_path)
            .with_context(|| format!("failed to read '{}'", server_config_path.display()))?;
        Some(
            serde_json::from_str(&raw)
                .with_context(|| format!("failed to parse '{}'", server_config_path.display()))?,
        )
    } else {
        None
    };

    // ── 3. Download / verify server jar ─────────────────────────────────────
    println!(
        "{} server jar for Minecraft {}...",
        "Checking".cyan().bold(),
        mc_version.yellow()
    );
    let jar_path = sand_build::ensure_server_jar(&mc_version)
        .with_context(|| format!("failed to get server jar for Minecraft {mc_version}"))?;
    println!(
        "  {} {}",
        "jar:".dimmed(),
        jar_path.display().to_string().white()
    );

    // ── 4. Set up dist/server/ ───────────────────────────────────────────────
    let server_dir = PathBuf::from("dist").join("server");
    std::fs::create_dir_all(&server_dir).context("failed to create dist/server/")?;

    // ── 4b. World reset policy (issue #317) ──────────────────────────────────
    // 🖥️ Server (host) only — governs Sand's own local dev world directory,
    // never the datapack. `WorldResetPolicy::AlwaysReset` wipes the previous
    // local world so `sand run` starts from a clean slate every time.
    if server_config
        .as_ref()
        .is_some_and(|s| s.world_reset_policy_always_reset.unwrap_or(false))
    {
        let world_dir = server_dir.join("world");
        if world_dir.exists() {
            std::fs::remove_dir_all(&world_dir)
                .with_context(|| format!("failed to reset '{}'", world_dir.display()))?;
            println!(
                "  {} local world (sand.build.rs ServerConfig: world_reset_policy = AlwaysReset)",
                "Reset".dimmed()
            );
        }
    }

    // ── 5. Accept EULA ───────────────────────────────────────────────────────
    let eula_path = server_dir.join("eula.txt");
    if !eula_path.exists() {
        std::fs::write(
            &eula_path,
            "# EULA accepted automatically by `sand run`\n\
             # https://aka.ms/MinecraftEULA\n\
             eula=true\n",
        )
        .context("failed to write eula.txt")?;
        println!("  {} eula.txt (eula=true)", "Wrote".dimmed());
    }

    // ── 6. Write server.properties ───────────────────────────────────────────
    // 🖥️ Server (host) only. `--offline` always wins over a `sand.build.rs`
    // ServerConfig's `online_mode` (it's an explicit, one-off CLI override);
    // `view-distance`/`simulation-distance`/`difficulty` come from
    // ServerConfig when present, otherwise vanilla defaults. Only written
    // the first time — an existing server.properties (including one you've
    // hand-edited) is never overwritten by a later `sand run`.
    let props_path = server_dir.join("server.properties");
    if !props_path.exists() {
        let resolved = ResolvedServerProperties::resolve(args.offline, server_config.as_ref());
        std::fs::write(&props_path, resolved.to_properties_text())
            .context("failed to write server.properties")?;
        println!(
            "  {} server.properties (online-mode={}, view-distance={}, \
             simulation-distance={}, difficulty={})",
            "Wrote".dimmed(),
            resolved.online_mode,
            resolved.view_distance,
            resolved.simulation_distance,
            resolved.difficulty
        );
    }

    // ── 7. Sync datapack into world/datapacks/ ───────────────────────────────
    let namespace = config.pack.namespace.as_str();
    let src = PathBuf::from("dist").join(namespace);
    let dest = server_dir.join("world").join("datapacks").join(namespace);

    if !src.exists() {
        bail!(
            "dist/{namespace}/ does not exist — run `sand build` first \
             (or remove --no-build)"
        );
    }

    let sync = sync_dir(&src, &dest)
        .with_context(|| format!("failed to sync datapack to {}", dest.display()))?;
    println!(
        "  {} datapack → {} ({} copied, {} skipped, {} pruned)",
        "Synced".dimmed(),
        dest.display().to_string().white(),
        sync.copied,
        sync.skipped,
        sync.pruned
    );

    // ── 8. Launch the server ─────────────────────────────────────────────────
    println!(
        "\n{} Minecraft {} with {}RAM...\n",
        "Starting".green().bold(),
        mc_version.yellow(),
        format!("{}  ", args.ram).white()
    );

    let ram = &args.ram;
    let mut command = std::process::Command::new("java");
    command
        .arg(format!("-Xmx{ram}"))
        .arg(format!("-Xms{ram}"))
        .arg("-jar")
        .arg(&jar_path)
        .arg("nogui")
        .current_dir(&server_dir);

    let outcome = crate::console::run_server(command, args.server_log, &mc_version)?;

    if !outcome.exit_status.success() {
        let log_path = server_dir.join("logs").join("latest.log");
        if log_path.exists() {
            bail!(
                "server exited with status {} — see {} for the full log",
                outcome.exit_status,
                log_path.display()
            );
        }
        bail!("server exited with status {}", outcome.exit_status);
    }

    // The JVM can exit 0 (a normal `stop`) even though the datapack never
    // loaded successfully — don't report that as success. `Failed` (the
    // process never became ready) is covered by the exit-status check
    // above in practice, but is included here too for robustness.
    if !crate::console::RunHealth::is_healthy(outcome.health) {
        let log_path = server_dir.join("logs").join("latest.log");
        let hint = if log_path.exists() {
            format!(" — see {} for the full log", log_path.display())
        } else {
            String::new()
        };
        match outcome.health {
            crate::console::RunHealth::Degraded => bail!(
                "Minecraft server exited normally, but the datapack failed to load — \
                 see the diagnostics above{hint}"
            ),
            crate::console::RunHealth::Failed => bail!(
                "Minecraft server exited without becoming healthy — see the diagnostics above{hint}"
            ),
            crate::console::RunHealth::Healthy => unreachable!("checked is_healthy above"),
        }
    }

    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Resolve "latest" to Sand's bundled latest-known verified version.
fn resolve_mc_version(mc_version: &str) -> String {
    if mc_version == "latest" {
        sand_build::latest_release_version()
    } else {
        mc_version.to_string()
    }
}

/// Incrementally mirror all files from `src` to `dest`.
///
/// This copies changed/new files, skips unchanged files, and prunes stale files
/// under the managed destination root.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct SyncStats {
    pub copied: usize,
    pub skipped: usize,
    pub pruned: usize,
}

pub fn sync_dir(src: &Path, dest: &Path) -> Result<SyncStats> {
    let mut stats = SyncStats::default();
    std::fs::create_dir_all(dest)?;
    for entry in walkdir::WalkDir::new(src) {
        let entry = entry?;
        // Sand's own output-manifest bookkeeping file (issue #347 Phase 7) is
        // not part of the datapack/resource-pack; don't mirror it into the
        // live server's world.
        if entry.file_type().is_file()
            && entry.path().file_name().and_then(|n| n.to_str())
                == Some(crate::build::output_manifest::MANIFEST_FILE_NAME)
        {
            continue;
        }
        let rel = entry.path().strip_prefix(src)?;
        let target = dest.join(rel);
        if entry.file_type().is_dir() {
            std::fs::create_dir_all(&target)?;
        } else {
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            if files_match(entry.path(), &target)? {
                stats.skipped += 1;
            } else {
                copy_file_streaming(entry.path(), &target)?;
                stats.copied += 1;
            }
        }
    }

    prune_stale(src, dest, &mut stats)?;
    Ok(stats)
}

fn files_match(src: &Path, dest: &Path) -> Result<bool> {
    if !dest.is_file() {
        return Ok(false);
    }

    let src_meta = std::fs::metadata(src)?;
    let dest_meta = std::fs::metadata(dest)?;
    if src_meta.len() != dest_meta.len() {
        return Ok(false);
    }

    streams_equal(src, dest)
}

fn streams_equal(left: &Path, right: &Path) -> Result<bool> {
    let mut left = BufReader::new(std::fs::File::open(left)?);
    let mut right = BufReader::new(std::fs::File::open(right)?);
    let mut left_buf = [0u8; 8192];
    let mut right_buf = [0u8; 8192];

    loop {
        let left_n = left.read(&mut left_buf)?;
        let right_n = right.read(&mut right_buf)?;
        if left_n != right_n {
            return Ok(false);
        }
        if left_n == 0 {
            return Ok(true);
        }
        if left_buf[..left_n] != right_buf[..right_n] {
            return Ok(false);
        }
    }
}

fn copy_file_streaming(src: &Path, dest: &Path) -> Result<()> {
    let mut input = BufReader::new(std::fs::File::open(src)?);
    let mut output = BufWriter::new(std::fs::File::create(dest)?);
    std::io::copy(&mut input, &mut output)?;
    Ok(())
}

fn prune_stale(src: &Path, dest: &Path, stats: &mut SyncStats) -> Result<()> {
    for entry in walkdir::WalkDir::new(dest).contents_first(true) {
        let entry = entry?;
        let path = entry.path();
        if path == dest {
            continue;
        }

        let rel = path.strip_prefix(dest)?;
        if src.join(rel).exists() {
            continue;
        }

        if entry.file_type().is_dir() {
            std::fs::remove_dir_all(path)?;
        } else {
            std::fs::remove_file(path)?;
        }
        stats.pruned += 1;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{ResolvedServerProperties, ServerConfigFile, sync_dir};

    fn server_config(
        view_distance: u8,
        simulation_distance: u8,
        difficulty: &str,
        online_mode: bool,
        world_reset_policy_always_reset: bool,
    ) -> ServerConfigFile {
        ServerConfigFile {
            view_distance: Some(view_distance),
            simulation_distance: Some(simulation_distance),
            difficulty: Some(difficulty.to_string()),
            online_mode: Some(online_mode),
            world_reset_policy_always_reset: Some(world_reset_policy_always_reset),
            seed: None,
        }
    }

    #[test]
    fn no_server_config_uses_vanilla_defaults() {
        let resolved = ResolvedServerProperties::resolve(false, None);
        assert_eq!(
            resolved,
            ResolvedServerProperties {
                online_mode: true,
                view_distance: 10,
                simulation_distance: 10,
                difficulty: "normal",
                seed: None,
            }
        );
    }

    #[test]
    fn server_config_values_are_applied() {
        let cfg = server_config(6, 4, "hard", false, true);
        let resolved = ResolvedServerProperties::resolve(false, Some(&cfg));
        assert_eq!(resolved.view_distance, 6);
        assert_eq!(resolved.simulation_distance, 4);
        assert_eq!(resolved.difficulty, "hard");
        assert!(!resolved.online_mode);
    }

    #[test]
    fn offline_flag_always_wins_over_server_config_online_mode() {
        let cfg = server_config(10, 10, "normal", true, false);
        let resolved = ResolvedServerProperties::resolve(true, Some(&cfg));
        assert!(
            !resolved.online_mode,
            "--offline must override ServerConfig::online_mode(true)"
        );
    }

    #[test]
    fn offline_flag_with_no_server_config_still_disables_online_mode() {
        let resolved = ResolvedServerProperties::resolve(true, None);
        assert!(!resolved.online_mode);
    }

    #[test]
    fn properties_text_contains_every_resolved_field() {
        let cfg = server_config(6, 4, "peaceful", false, false);
        let resolved = ResolvedServerProperties::resolve(false, Some(&cfg));
        let text = resolved.to_properties_text();
        assert!(text.contains("online-mode=false"));
        assert!(text.contains("view-distance=6"));
        assert!(text.contains("simulation-distance=4"));
        assert!(text.contains("difficulty=peaceful"));
    }

    #[test]
    fn fixed_world_seed_becomes_level_seed() {
        let mut cfg = server_config(10, 10, "normal", true, false);
        cfg.seed = Some(1337);
        let resolved = ResolvedServerProperties::resolve(false, Some(&cfg));
        assert_eq!(resolved.seed, Some(1337));
        assert!(resolved.to_properties_text().contains("level-seed=1337"));
    }

    #[test]
    fn no_seed_omits_level_seed_entirely() {
        let cfg = server_config(10, 10, "normal", true, false);
        let resolved = ResolvedServerProperties::resolve(false, Some(&cfg));
        assert_eq!(resolved.seed, None);
        assert!(!resolved.to_properties_text().contains("level-seed"));
    }

    #[test]
    fn seed_only_file_with_no_server_config_fields_still_parses() {
        // sand-cli writes this shape when a build script sets World::seed
        // but never calls SandBuild::server(...).
        let json = serde_json::json!({ "seed": 42 });
        let cfg: ServerConfigFile = serde_json::from_value(json).unwrap();
        let resolved = ResolvedServerProperties::resolve(false, Some(&cfg));
        assert_eq!(resolved.seed, Some(42));
        // Every ServerConfig-shaped field still falls back to vanilla defaults.
        assert_eq!(resolved.view_distance, 10);
        assert_eq!(resolved.difficulty, "normal");
        assert!(resolved.online_mode);
    }

    #[test]
    fn dev_and_release_server_configs_resolve_differently() {
        // Mirrors the acceptance criterion that dev/release profiles
        // produce genuinely different results — here, for the server-only
        // half of a `SandBuild` rather than the datapack half (covered by
        // sand-core's `dev_and_release_worlds_produce_different_dimension_json`).
        let dev = server_config(8, 6, "peaceful", false, true);
        let release = server_config(10, 10, "normal", true, false);
        let dev_resolved = ResolvedServerProperties::resolve(false, Some(&dev));
        let release_resolved = ResolvedServerProperties::resolve(false, Some(&release));
        assert_ne!(dev_resolved, release_resolved);
    }

    #[test]
    fn sync_skips_unchanged_files() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        std::fs::create_dir_all(src.join("data/pack/function")).unwrap();
        std::fs::create_dir_all(dest.join("data/pack/function")).unwrap();
        std::fs::write(src.join("data/pack/function/load.mcfunction"), "say hi").unwrap();
        std::fs::write(dest.join("data/pack/function/load.mcfunction"), "say hi").unwrap();

        let stats = sync_dir(&src, &dest).unwrap();

        assert_eq!(stats.copied, 0);
        assert_eq!(stats.skipped, 1);
        assert_eq!(stats.pruned, 0);
    }

    #[test]
    fn sync_updates_changed_files() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        std::fs::create_dir_all(src.join("data/pack/function")).unwrap();
        std::fs::create_dir_all(dest.join("data/pack/function")).unwrap();
        std::fs::write(src.join("data/pack/function/tick.mcfunction"), "say new").unwrap();
        std::fs::write(dest.join("data/pack/function/tick.mcfunction"), "say old").unwrap();

        let stats = sync_dir(&src, &dest).unwrap();

        assert_eq!(stats.copied, 1);
        assert_eq!(
            std::fs::read_to_string(dest.join("data/pack/function/tick.mcfunction")).unwrap(),
            "say new"
        );
    }

    #[test]
    fn sync_prunes_stale_managed_outputs() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        std::fs::create_dir_all(src.join("data/pack/function")).unwrap();
        std::fs::create_dir_all(dest.join("data/pack/function")).unwrap();
        std::fs::write(src.join("data/pack/function/load.mcfunction"), "say live").unwrap();
        std::fs::write(dest.join("data/pack/function/old.mcfunction"), "say stale").unwrap();

        let stats = sync_dir(&src, &dest).unwrap();

        assert_eq!(stats.copied, 1);
        assert_eq!(stats.pruned, 1);
        assert!(!dest.join("data/pack/function/old.mcfunction").exists());
    }

    #[test]
    fn sync_does_not_prune_outside_managed_root() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        let other = temp.path().join("server/world/datapacks/manual_pack");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::create_dir_all(&dest).unwrap();
        std::fs::create_dir_all(&other).unwrap();
        std::fs::write(other.join("keep.mcfunction"), "say keep").unwrap();

        sync_dir(&src, &dest).unwrap();

        assert!(other.join("keep.mcfunction").exists());
    }
}
