use std::io::{BufReader, BufWriter, Read};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use colored::Colorize;

use crate::config::SandConfig;
use crate::console::OutputMode;

pub struct RunArgs {
    /// JVM max heap size, e.g. "4G" or "2048M". Used for both -Xmx and -Xms.
    pub ram: String,
    /// Write `online-mode=false` to server.properties for offline testing.
    pub offline: bool,
    /// Skip `sand build`; use whatever is already in dist/.
    pub no_build: bool,
    /// How to present the Minecraft server's log output.
    pub server_log: OutputMode,
}

pub fn run(args: RunArgs) -> Result<()> {
    // ── 1. Read sand.toml ────────────────────────────────────────────────────
    let config_path = std::env::current_dir()?.join("sand.toml");
    if !config_path.exists() {
        bail!("sand.toml not found — run `sand run` from your project root");
    }
    let config: SandConfig = toml::from_str(&std::fs::read_to_string(&config_path)?)
        .context("failed to parse sand.toml")?;

    let mc_version = resolve_mc_version(&config.pack.mc_version);

    // ── 2. Build the datapack ────────────────────────────────────────────────
    if args.no_build {
        println!("{}", "Skipping build (--no-build)".dimmed());
    } else {
        crate::build::run(false, false)?;
    }

    // ── 3. Download / verify server jar ─────────────────────────────────────
    println!(
        "{} server jar for Minecraft {}...",
        "Checking".cyan().bold(),
        mc_version.yellow()
    );
    let jar_path = sand_build::ensure_server_jar(&mc_version)
        .with_context(|| format!("failed to get server jar for Minecraft {mc_version}"))?;
    println!(
        "  {} {}",
        "jar:".dimmed(),
        jar_path.display().to_string().white()
    );

    // ── 4. Set up dist/server/ ───────────────────────────────────────────────
    let server_dir = PathBuf::from("dist").join("server");
    std::fs::create_dir_all(&server_dir).context("failed to create dist/server/")?;

    // ── 5. Accept EULA ───────────────────────────────────────────────────────
    let eula_path = server_dir.join("eula.txt");
    if !eula_path.exists() {
        std::fs::write(
            &eula_path,
            "# EULA accepted automatically by `sand run`\n\
             # https://aka.ms/MinecraftEULA\n\
             eula=true\n",
        )
        .context("failed to write eula.txt")?;
        println!("  {} eula.txt (eula=true)", "Wrote".dimmed());
    }

    // ── 6. Write server.properties ───────────────────────────────────────────
    let props_path = server_dir.join("server.properties");
    if !props_path.exists() {
        let online_mode = if args.offline { "false" } else { "true" };
        std::fs::write(
            &props_path,
            format!(
                "# Generated by `sand run` — edit as needed\n\
                 level-name=world\n\
                 online-mode={online_mode}\n\
                 spawn-protection=0\n"
            ),
        )
        .context("failed to write server.properties")?;
        println!(
            "  {} server.properties (online-mode={online_mode})",
            "Wrote".dimmed()
        );
    }

    // ── 7. Sync datapack into world/datapacks/ ───────────────────────────────
    let namespace = config.pack.namespace.as_str();
    let src = PathBuf::from("dist").join(namespace);
    let dest = server_dir.join("world").join("datapacks").join(namespace);

    if !src.exists() {
        bail!(
            "dist/{namespace}/ does not exist — run `sand build` first \
             (or remove --no-build)"
        );
    }

    let sync = sync_dir(&src, &dest)
        .with_context(|| format!("failed to sync datapack to {}", dest.display()))?;
    println!(
        "  {} datapack → {} ({} copied, {} skipped, {} pruned)",
        "Synced".dimmed(),
        dest.display().to_string().white(),
        sync.copied,
        sync.skipped,
        sync.pruned
    );

    // ── 8. Launch the server ─────────────────────────────────────────────────
    println!(
        "\n{} Minecraft {} with {}RAM...\n",
        "Starting".green().bold(),
        mc_version.yellow(),
        format!("{}  ", args.ram).white()
    );

    let ram = &args.ram;
    let mut command = std::process::Command::new("java");
    command
        .arg(format!("-Xmx{ram}"))
        .arg(format!("-Xms{ram}"))
        .arg("-jar")
        .arg(&jar_path)
        .arg("nogui")
        .current_dir(&server_dir);

    let outcome = crate::console::run_server(command, args.server_log, &mc_version)?;

    if !outcome.exit_status.success() {
        let log_path = server_dir.join("logs").join("latest.log");
        if log_path.exists() {
            bail!(
                "server exited with status {} — see {} for the full log",
                outcome.exit_status,
                log_path.display()
            );
        }
        bail!("server exited with status {}", outcome.exit_status);
    }

    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Resolve "latest" to Sand's bundled latest-known verified version.
fn resolve_mc_version(mc_version: &str) -> String {
    if mc_version == "latest" {
        sand_build::latest_release_version()
    } else {
        mc_version.to_string()
    }
}

/// Incrementally mirror all files from `src` to `dest`.
///
/// This copies changed/new files, skips unchanged files, and prunes stale files
/// under the managed destination root.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct SyncStats {
    pub copied: usize,
    pub skipped: usize,
    pub pruned: usize,
}

pub fn sync_dir(src: &Path, dest: &Path) -> Result<SyncStats> {
    let mut stats = SyncStats::default();
    std::fs::create_dir_all(dest)?;
    for entry in walkdir::WalkDir::new(src) {
        let entry = entry?;
        let rel = entry.path().strip_prefix(src)?;
        let target = dest.join(rel);
        if entry.file_type().is_dir() {
            std::fs::create_dir_all(&target)?;
        } else {
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            if files_match(entry.path(), &target)? {
                stats.skipped += 1;
            } else {
                copy_file_streaming(entry.path(), &target)?;
                stats.copied += 1;
            }
        }
    }

    prune_stale(src, dest, &mut stats)?;
    Ok(stats)
}

fn files_match(src: &Path, dest: &Path) -> Result<bool> {
    if !dest.is_file() {
        return Ok(false);
    }

    let src_meta = std::fs::metadata(src)?;
    let dest_meta = std::fs::metadata(dest)?;
    if src_meta.len() != dest_meta.len() {
        return Ok(false);
    }

    streams_equal(src, dest)
}

fn streams_equal(left: &Path, right: &Path) -> Result<bool> {
    let mut left = BufReader::new(std::fs::File::open(left)?);
    let mut right = BufReader::new(std::fs::File::open(right)?);
    let mut left_buf = [0u8; 8192];
    let mut right_buf = [0u8; 8192];

    loop {
        let left_n = left.read(&mut left_buf)?;
        let right_n = right.read(&mut right_buf)?;
        if left_n != right_n {
            return Ok(false);
        }
        if left_n == 0 {
            return Ok(true);
        }
        if left_buf[..left_n] != right_buf[..right_n] {
            return Ok(false);
        }
    }
}

fn copy_file_streaming(src: &Path, dest: &Path) -> Result<()> {
    let mut input = BufReader::new(std::fs::File::open(src)?);
    let mut output = BufWriter::new(std::fs::File::create(dest)?);
    std::io::copy(&mut input, &mut output)?;
    Ok(())
}

fn prune_stale(src: &Path, dest: &Path, stats: &mut SyncStats) -> Result<()> {
    for entry in walkdir::WalkDir::new(dest).contents_first(true) {
        let entry = entry?;
        let path = entry.path();
        if path == dest {
            continue;
        }

        let rel = path.strip_prefix(dest)?;
        if src.join(rel).exists() {
            continue;
        }

        if entry.file_type().is_dir() {
            std::fs::remove_dir_all(path)?;
        } else {
            std::fs::remove_file(path)?;
        }
        stats.pruned += 1;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::sync_dir;

    #[test]
    fn sync_skips_unchanged_files() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        std::fs::create_dir_all(src.join("data/pack/function")).unwrap();
        std::fs::create_dir_all(dest.join("data/pack/function")).unwrap();
        std::fs::write(src.join("data/pack/function/load.mcfunction"), "say hi").unwrap();
        std::fs::write(dest.join("data/pack/function/load.mcfunction"), "say hi").unwrap();

        let stats = sync_dir(&src, &dest).unwrap();

        assert_eq!(stats.copied, 0);
        assert_eq!(stats.skipped, 1);
        assert_eq!(stats.pruned, 0);
    }

    #[test]
    fn sync_updates_changed_files() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        std::fs::create_dir_all(src.join("data/pack/function")).unwrap();
        std::fs::create_dir_all(dest.join("data/pack/function")).unwrap();
        std::fs::write(src.join("data/pack/function/tick.mcfunction"), "say new").unwrap();
        std::fs::write(dest.join("data/pack/function/tick.mcfunction"), "say old").unwrap();

        let stats = sync_dir(&src, &dest).unwrap();

        assert_eq!(stats.copied, 1);
        assert_eq!(
            std::fs::read_to_string(dest.join("data/pack/function/tick.mcfunction")).unwrap(),
            "say new"
        );
    }

    #[test]
    fn sync_prunes_stale_managed_outputs() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        std::fs::create_dir_all(src.join("data/pack/function")).unwrap();
        std::fs::create_dir_all(dest.join("data/pack/function")).unwrap();
        std::fs::write(src.join("data/pack/function/load.mcfunction"), "say live").unwrap();
        std::fs::write(dest.join("data/pack/function/old.mcfunction"), "say stale").unwrap();

        let stats = sync_dir(&src, &dest).unwrap();

        assert_eq!(stats.copied, 1);
        assert_eq!(stats.pruned, 1);
        assert!(!dest.join("data/pack/function/old.mcfunction").exists());
    }

    #[test]
    fn sync_does_not_prune_outside_managed_root() {
        let temp = tempfile::tempdir().unwrap();
        let src = temp.path().join("dist/pack");
        let dest = temp.path().join("server/world/datapacks/pack");
        let other = temp.path().join("server/world/datapacks/manual_pack");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::create_dir_all(&dest).unwrap();
        std::fs::create_dir_all(&other).unwrap();
        std::fs::write(other.join("keep.mcfunction"), "say keep").unwrap();

        sync_dir(&src, &dest).unwrap();

        assert!(other.join("keep.mcfunction").exists());
    }
}
