//! Typed references to Minecraft resources owned by a datapack.
//!
//! The canonical resource-reference API uses registry-specific identifiers,
//! not duplicate wrapper types. Each identifier validates `namespace:path` at
//! construction time and cannot be confused with another Minecraft resource
//! kind. `DialogId` also provides [`DialogId::local`] and
//! [`DialogId::try_local`] for a dialog generated by the current Sand project.
//!
//! ```rust,ignore
//! use sand_core::resource_ref::{DialogId, FunctionId, PredicateId};
//! use sand_core::condition::Condition;
//!
//! let can_cast = PredicateId::custom("my_pack:can_cast".parse()?);
//! let heal = FunctionId::custom("my_pack:heal".parse()?);
//! let dialog = DialogId::local("welcome");
//!
//! let condition = Condition::predicate(can_cast);
//! ```

pub use sand_components::{
    AdvancementId, DialogId, FunctionId, LootTableId, PredicateId, RecipeId,
};

#[cfg(test)]
mod tests {
    use super::*;
    use crate::condition::Condition;

    #[test]
    fn typed_resource_ids_validate_and_render() {
        let function = FunctionId::custom("my_pack:heal".parse().unwrap());
        let predicate = PredicateId::custom("my_pack:can_cast".parse().unwrap());
        let advancement = AdvancementId::custom("my_pack:first_join".parse().unwrap());
        let loot = LootTableId::custom("my_pack:mob/zombie".parse().unwrap());
        let recipe = RecipeId::custom("my_pack:iron_sword".parse().unwrap());

        assert_eq!(function.to_string(), "my_pack:heal");
        assert_eq!(predicate.to_string(), "my_pack:can_cast");
        assert_eq!(advancement.to_string(), "my_pack:first_join");
        assert_eq!(loot.to_string(), "my_pack:mob/zombie");
        assert_eq!(recipe.to_string(), "my_pack:iron_sword");
    }

    #[test]
    fn local_dialog_is_typed_and_dynamic_paths_can_fail() {
        assert_eq!(
            DialogId::local("welcome").to_string(),
            "__sand_local:welcome"
        );
        assert!(DialogId::try_local("not valid").is_err());
    }

    #[test]
    fn predicate_id_composes_with_conditions() {
        let predicate = PredicateId::custom("my_pack:can_cast".parse().unwrap());
        let condition = Condition::predicate(predicate);
        assert_eq!(
            condition.execute_commands(false, "say yes"),
            ["execute if predicate my_pack:can_cast run say yes"]
        );
    }
}
