//! Bounded, per-subject item-snapshot storage for `.within(...)` correlation
//! (#272).
//!
//! [`crate::item::ItemSnapshot`] is explicitly scoped to one synchronous
//! invocation (see its module doc's "Lifetime" section) — its storage is one
//! deterministic, non-per-player command-storage path, safe only because
//! Minecraft never interleaves two players' synchronous call trees within
//! one capture/consume cycle. That safety argument stops holding the moment
//! a value must survive *across* ticks: a bounded `.within(...)` child may
//! observe a source occurrence several ticks after it happened, by which
//! point other players (or the same player, again) may have run through the
//! source's own capture and overwritten that one global path. Persisting an
//! item snapshot across a tick boundary therefore needs genuine per-subject
//! storage, not [`crate::item::ItemSnapshot`]'s global-path convention.
//!
//! Command storage (`data storage <id> <path>`) has no native per-player
//! keying. Entity NBT does: `data ... entity <selector> <path>` is scoped to
//! whichever entity `<selector>` resolves to. This module stores the bounded
//! copy on the subject entity itself (`@s`, i.e. whichever player the
//! generated command sequence is currently executing as) via
//! [`crate::state::storage::EntityNbt`] — this is what makes cross-player
//! leakage structurally impossible rather than merely unlikely: two
//! players' entities never share NBT storage.
//!
//! [`BoundedItemSchema`] derives a deterministic per-subject NBT root path
//! from `(source_event_label, role, hand)`, the same
//! `tick_event_resource_key` FNV-1a scheme every other Sand-generated
//! resource key uses. [`BoundedItemSnapshot`] is the read-side handle a
//! bounded child resolves through
//! [`crate::participant::EventParticipantPlan::inherit_item_within`] —
//! structurally the item-side counterpart of
//! [`crate::item::ItemSnapshot`], just backed by entity NBT instead of
//! command storage.
//!
//! `persist_commands`/`expire_commands` are the write side, generated by
//! the export pipeline (`sand-core/src/compiler/export/pipeline.rs`) rather
//! than by any one event's own `crate::participant::EventParticipantPlan::build`
//! — see that module's doc for exactly where in the generated per-player
//! call tree they are spliced, and why that placement (not
//! `pre_observation`/`post_observation`) is the only place safe from the
//! same cross-player-interleaving hazard described above.

use sand_commands::Selector;

use crate::events::graph::tick_event_resource_key;
use crate::item::ItemSnapshot;
use crate::item::snapshot::SnapshotReliability;
use crate::participant::role::{ItemParticipantRole, ParticipantHand};
use crate::state::storage::{EntityNbt, NbtPath, NbtRef, UntypedNbt};

/// Deterministic, collision-checked identity for one bounded item entry's
/// per-subject entity-NBT storage. `(source_event_label, role, hand)`
/// determines the key — three distinct declarations that all name the same
/// source/role/hand always resolve to the same storage, and any distinct
/// triple always resolves to a different one, via the same FNV-1a scheme
/// [`crate::item::snapshot::SnapshotSchema`] uses for its own keys.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoundedItemSchema {
    key: String,
}

impl BoundedItemSchema {
    /// `source_event_label` should be `std::any::type_name::<Source>()` —
    /// the same convention every other generated participant-transport key
    /// uses — so two distinct source event types can never collide even
    /// when they declare the identical role/hand.
    pub(crate) fn new(
        source_event_label: &str,
        role: ItemParticipantRole,
        hand: ParticipantHand,
    ) -> Self {
        Self {
            key: tick_event_resource_key(&format!(
                "{source_event_label}::bounded_item::{role:?}::{hand:?}"
            )),
        }
    }

    fn root_path(&self) -> NbtPath {
        NbtPath::new(format!("__sand_bounded_item.{}", self.key))
    }

    fn entity_nbt() -> EntityNbt {
        EntityNbt::target(Selector::self_())
    }

    fn base(&self) -> NbtRef<UntypedNbt> {
        Self::entity_nbt().path(self.root_path())
    }
}

/// A read-only handle to a bounded, per-subject item snapshot — the
/// item-side counterpart of [`ItemSnapshot`] for values that must survive
/// across a `.within(...)` correlation window rather than just one
/// synchronous invocation. See the [module doc](self) for the full storage
/// and safety contract.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoundedItemSnapshot {
    schema: BoundedItemSchema,
    source_kind: &'static str,
    reliability: SnapshotReliability,
}

impl BoundedItemSnapshot {
    /// Reconstruct the handle a bounded declaration resolves to, given the
    /// same `(source_event_label, role, hand)` `persist_commands` was
    /// generated with. `pub(crate)` — reached by
    /// [`crate::participant::EventParticipantPlan::resolve_bounded_item`],
    /// never constructed directly by handler code.
    pub(crate) fn reconstruct(
        source_event_label: &str,
        role: ItemParticipantRole,
        hand: ParticipantHand,
        source_kind: &'static str,
        reliability: SnapshotReliability,
    ) -> Self {
        Self {
            schema: BoundedItemSchema::new(source_event_label, role, hand),
            source_kind,
            reliability,
        }
    }

    /// The reliability this snapshot's *item data* carries, preserved
    /// unchanged from the source capture — persisting a copy across a
    /// bounded window changes nothing about how trustworthy the item data
    /// itself is, only how long the copy remains readable (see
    /// [`crate::participant::ParticipantLifetime::BoundedWindow`] for the
    /// lifetime half of that distinction).
    pub fn reliability(&self) -> SnapshotReliability {
        self.reliability
    }

    /// The [`crate::item::ItemLocation::kind`] the *source* snapshot was
    /// originally captured from.
    pub fn source_kind(&self) -> &'static str {
        self.source_kind
    }

    /// `if data entity @s <path>{present:1b}` — true when the source
    /// occurrence that most recently wrote this storage actually had an
    /// item present at capture time. Absence here is never conflated with
    /// "the window has not been refreshed yet" — see the [module
    /// doc](self); `persist_commands` always writes a definite
    /// present/absent value on every source occurrence.
    pub fn is_present(&self) -> crate::condition::Condition {
        let base = self.schema.base();
        crate::condition::Condition::NbtExists {
            target: base.location().clone(),
            path: NbtPath::raw(format!("{}{{present:1b}}", base.path_value().as_str())),
        }
    }

    /// The negation of [`Self::is_present`].
    pub fn is_absent(&self) -> crate::condition::Condition {
        crate::condition::Condition::negate(self.is_present())
    }

    /// The typed NBT path to the persisted item compound.
    pub fn item_path(&self) -> NbtRef<UntypedNbt> {
        self.schema.base().field("item")
    }

    /// The typed NBT path to the persisted item's `id` field.
    pub fn id_path(&self) -> NbtRef<UntypedNbt> {
        self.item_path().field("id")
    }

    /// The typed NBT path to the persisted item's `count` field.
    pub fn count_path(&self) -> NbtRef<UntypedNbt> {
        self.item_path().field("count")
    }

    /// The typed NBT path to the persisted item's version-appropriate
    /// component/tag data.
    pub fn components_path(&self) -> NbtRef<UntypedNbt> {
        self.item_path().field("components")
    }

    /// Commands that unconditionally reset this bounded snapshot's storage
    /// back to explicit absence, for explicit/manual reset paths (e.g. a
    /// pack author clearing state on player logout, or any handler wanting
    /// to invalidate a snapshot early rather than waiting for expiry or
    /// replacement). Identical in shape to [`ItemSnapshot::cleanup_commands`]
    /// — cheap, deterministic, and idempotent to call unconditionally.
    /// `expire_commands` (generated automatically by the export pipeline)
    /// runs the same two commands on window expiry; this method exposes the
    /// identical reset for callers who want to trigger it themselves.
    pub fn reset_commands(&self) -> Vec<String> {
        reset_to_absence(&self.schema)
    }
}

/// The two commands that unconditionally reset `schema`'s storage to
/// explicit absence — shared by `persist_commands`'s leading reset step,
/// `expire_commands`, and [`BoundedItemSnapshot::reset_commands`], so all
/// three can never drift out of sync with each other.
fn reset_to_absence(schema: &BoundedItemSchema) -> Vec<String> {
    let base = schema.base();
    vec![
        base.field("present").set_value(false).to_string(),
        base.field("item").set_raw("{}").to_string(),
    ]
}

/// Build the commands that persist `source`'s currently-captured item into
/// `schema`'s per-subject bounded storage: unconditional reset to explicit
/// absence, then a presence-gated copy and presence-gated mark — the exact
/// same reset-then-conditionally-write shape
/// [`ItemSnapshot::capture`](crate::item::ItemSnapshot::capture) documents,
/// generalized to a per-subject destination instead of `source`'s original
/// capture destination. This is what gives repeated source occurrences
/// atomic replacement semantics: every occurrence starts from a clean reset,
/// so a bounded child can never observe a torn mix of an old and new item.
///
/// `pub(crate)` — called only from the export pipeline
/// (`sand-core/src/compiler/export/pipeline.rs`), spliced into the source
/// event's own generated dispatch function immediately after its occurrence
/// mark is set (guaranteed to still be the source's own synchronous
/// per-player call tree — see this module's doc for why nowhere else is
/// safe).
pub(crate) fn persist_commands(schema: &BoundedItemSchema, source: &ItemSnapshot) -> Vec<String> {
    let mut commands = reset_to_absence(schema);
    let base = schema.base();
    let item = base.field("item");
    let present = base.field("present");
    commands.extend(
        source
            .is_present()
            .execute_commands(false, &item.copy_from(&source.item_path()).to_string()),
    );
    commands.extend(
        source
            .is_present()
            .execute_commands(false, &present.set_value(true).to_string()),
    );
    commands
}

/// Build the commands that clear `schema`'s per-subject bounded storage on
/// window expiry — identical to [`BoundedItemSnapshot::reset_commands`]'s
/// output, exposed as a free function so the export pipeline can generate it
/// without needing a live [`BoundedItemSnapshot`] value (expiry is keyed
/// purely by `(source_event_label, role, hand)`, independent of which child,
/// if any, ever resolves a handle for it).
pub(crate) fn expire_commands(schema: &BoundedItemSchema) -> Vec<String> {
    reset_to_absence(schema)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::item::ItemLocation;
    use crate::item::snapshot::SnapshotSchema;

    fn source_snapshot() -> ItemSnapshot {
        let (snapshot, _) = ItemSnapshot::capture(
            &ItemLocation::PlayerMainHand,
            SnapshotSchema::new("test:participants", "test::SourceEvent"),
            SnapshotReliability::ExactPostTrigger,
        )
        .unwrap();
        snapshot
    }

    #[test]
    fn schema_key_is_deterministic_and_distinct_per_triple() {
        let a = BoundedItemSchema::new(
            "EventA",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
        );
        let b = BoundedItemSchema::new(
            "EventA",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
        );
        let c = BoundedItemSchema::new(
            "EventA",
            ItemParticipantRole::Weapon,
            ParticipantHand::OffHand,
        );
        let d = BoundedItemSchema::new(
            "EventB",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
        );
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_ne!(a, d);
    }

    #[test]
    fn persist_commands_reset_before_conditionally_copying_and_marking() {
        let schema = BoundedItemSchema::new(
            "SourceEvent",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
        );
        let commands = persist_commands(&schema, &source_snapshot());
        assert_eq!(commands.len(), 4, "{commands:#?}");
        assert!(commands[0].starts_with("data modify entity @s __sand_bounded_item."));
        assert!(commands[0].contains("present"));
        assert!(commands[0].ends_with("set value 0b"));
        assert!(commands[1].contains("item"));
        assert!(commands[1].ends_with("set value {}"));
        assert!(commands[2].starts_with("execute if data storage test:participants"));
        assert!(commands[2].contains("run data modify entity @s __sand_bounded_item."));
        assert!(commands[2].contains("item"));
        assert!(commands[3].starts_with("execute if data storage test:participants"));
        assert!(commands[3].ends_with("set value 1b"));
    }

    #[test]
    fn expire_and_reset_commands_are_identical() {
        let schema = BoundedItemSchema::new(
            "SourceEvent",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
        );
        let snapshot = BoundedItemSnapshot::reconstruct(
            "SourceEvent",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
            "player_main_hand",
            SnapshotReliability::ExactPostTrigger,
        );
        assert_eq!(expire_commands(&schema), snapshot.reset_commands());
    }

    #[test]
    fn is_present_and_is_absent_are_exact_negations() {
        let snapshot = BoundedItemSnapshot::reconstruct(
            "SourceEvent",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
            "player_main_hand",
            SnapshotReliability::ExactPostTrigger,
        );
        assert_eq!(
            snapshot.is_absent(),
            crate::condition::Condition::negate(snapshot.is_present())
        );
    }

    #[test]
    fn typed_field_paths_are_nested_under_the_item_compound() {
        let snapshot = BoundedItemSnapshot::reconstruct(
            "SourceEvent",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
            "player_main_hand",
            SnapshotReliability::ExactPostTrigger,
        );
        assert!(
            snapshot
                .id_path()
                .as_str()
                .starts_with(snapshot.item_path().as_str())
        );
        assert!(snapshot.id_path().as_str().ends_with(".id"));
        assert!(snapshot.count_path().as_str().ends_with(".count"));
        assert!(snapshot.components_path().as_str().ends_with(".components"));
    }

    #[test]
    fn repeated_persist_command_generation_is_deterministic() {
        let schema = BoundedItemSchema::new(
            "SourceEvent",
            ItemParticipantRole::Weapon,
            ParticipantHand::MainHand,
        );
        assert_eq!(
            persist_commands(&schema, &source_snapshot()),
            persist_commands(&schema, &source_snapshot())
        );
    }
}
