//! Export coverage proving `observe_correlated_attacker`'s generated
//! commands — reset, presence-gated mark+bind, caller body, cleanup — land
//! in the documented order once embedded into a real `SandEvent` and run
//! through the actual export pipeline (#230 Phase 9).
//!
//! Real intended usage is an advancement-backed event such as
//! `EntityDamagePlayerEvent` (`EntityHurtPlayer`) or `PlayerKillEvent`
//! (`EntityKilledPlayer`), where the author embeds this call at the start
//! of their handler body. This test uses a tick-backed event instead —
//! `EventSetup::pre_observation` is the harness Phase 7's own export test
//! already proved works end-to-end for exactly this "commands generated by
//! a standalone function, embedded manually into a SandEvent" pattern — the
//! command-generation logic under test (`observe_correlated_attacker`)
//! does not itself depend on which dispatch kind embeds it.

use sand_core::condition::Condition;
use sand_core::entity::EntityContext;
use sand_core::entity::kind::PlayerKind;
use sand_core::events::{EventSetup, SandEvent, SandEventDispatch};
use sand_core::participant::{
    EntityParticipantRole, ObservationSchema, observe_correlated_attacker,
};
use sand_core::version::{MinecraftVersion, VersionProfile};
use sand_core::{EventDescriptor, EventDispatch};
use std::any::TypeId;

struct OnPlayerHurtCheck;

impl SandEvent for OnPlayerHurtCheck {
    fn dispatch() -> impl Into<SandEventDispatch> {
        SandEventDispatch::tick()
            .as_players()
            .when(Condition::raw("score @s p9_trigger matches 1.."))
    }

    fn setup() -> EventSetup {
        let profile = VersionProfile::resolve(&MinecraftVersion::parse("1.21.4").unwrap()).unwrap();
        let ctx: EntityContext<PlayerKind> = EntityContext::default();
        let commands = observe_correlated_attacker(
            &ctx,
            &profile,
            ObservationSchema::new(
                "attackerpack:observations",
                std::any::type_name::<OnPlayerHurtCheck>(),
            ),
            EntityParticipantRole::Attacker,
            |_observation| vec!["say attacker observed".to_string()],
        )
        .expect("1.21.4 supports execute on attacker");
        EventSetup {
            objectives: vec!["scoreboard objectives add p9_trigger dummy".into()],
            pre_observation: commands,
            post_observation: vec!["scoreboard players set @s p9_trigger 0".into()],
        }
    }
}

fn no_trigger() -> Option<sand_core::AdvancementTrigger> {
    None
}
fn no_condition() -> Option<String> {
    None
}
fn no_chain() -> Option<sand_core::events::ChainEventDispatch> {
    None
}
fn revoke_true() -> bool {
    true
}
fn on_player_hurt_check_tick() -> Option<sand_core::events::TickEventDispatch> {
    match OnPlayerHurtCheck::dispatch().into() {
        SandEventDispatch::Tick(tick) => Some(tick),
        _ => None,
    }
}
fn type_id() -> TypeId {
    TypeId::of::<OnPlayerHurtCheck>()
}
fn type_name() -> &'static str {
    std::any::type_name::<OnPlayerHurtCheck>()
}
fn body() -> Vec<String> {
    vec!["say checked".to_string()]
}
fn setup() -> EventSetup {
    OnPlayerHurtCheck::setup()
}

sand_core::inventory::submit! {
    EventDescriptor {
        path: "on_player_hurt_check",
        id_override: None,
        make: body,
        dispatch: EventDispatch::Custom {
            make_trigger: no_trigger,
            make_condition: no_condition,
            make_tick: on_player_hurt_check_tick,
            make_chain: no_chain,
            make_tracked: || None,
            revoke: revoke_true,
            event_type_id: type_id,
            event_type_name: type_name,
            make_setup: setup,
        },
    }
}

fn records() -> Vec<serde_json::Value> {
    let json = sand_core::try_export_components_json("attackerpack").expect("export succeeds");
    serde_json::from_str(&json).expect("valid export JSON")
}

fn function<'a>(records: &'a [serde_json::Value], path: &str) -> &'a str {
    records
        .iter()
        .find(|record| record["dir"] == "function" && record["path"] == path)
        .and_then(|record| record["content"].as_str())
        .unwrap_or_else(|| panic!("missing function {path}"))
}

fn check_key() -> String {
    let mut hash: u32 = 2_166_136_261;
    for byte in std::any::type_name::<OnPlayerHurtCheck>().bytes() {
        hash ^= u32::from(byte);
        hash = hash.wrapping_mul(16_777_619);
    }
    format!("{hash:08x}")
}

#[test]
fn observation_commands_run_before_condition_test_and_cleanup_runs_before_post_observation() {
    let records = records();
    let check = function(&records, &format!("__sand_event_check/{}", check_key()));

    let reset_position = check
        .find("present set value 0b")
        .expect("reset command is present");
    let mark_position = check
        .find("execute on attacker run")
        .expect("mark/bind command is present");
    let detection_position = check
        .find("execute as @a at @s")
        .expect("detection line is present");
    let body_position = check
        .find("say attacker observed")
        .expect("handler body command is present");
    let cleanup_position = check
        .find("tag @e[tag=__sand_observed_")
        .expect("observation cleanup command is present");
    let post_observation_position = check
        .find("scoreboard players set @s p9_trigger 0")
        .expect("post_observation cleanup is present");

    assert!(
        reset_position < mark_position,
        "reset must run before the mark/bind: {check}"
    );
    assert!(
        mark_position < body_position,
        "mark/bind must run before the caller body: {check}"
    );
    assert!(
        body_position < cleanup_position,
        "caller body must run before observation cleanup: {check}"
    );
    assert!(
        reset_position < detection_position,
        "observation setup must run before the condition test: {check}"
    );
    assert!(
        cleanup_position < post_observation_position,
        "observation cleanup must run before post_observation cleanup: {check}"
    );

    let first_line = check.lines().next().unwrap();
    assert!(
        first_line.contains("present set value 0b"),
        "observation reset must be the first command in the check function: {first_line}"
    );
}

#[test]
fn repeated_export_is_identical() {
    let first = sand_core::try_export_components_json("attackerpack").unwrap();
    let second = sand_core::try_export_components_json("attackerpack").unwrap();
    assert_eq!(first, second);
}
