//! High-level scoreboard-based ability cooldown.
//!
//! This is the typed state API counterpart to [`crate::cmd::Cooldown`].
//! The two types have the same conceptual purpose but different constructors:
//! - `state::Cooldown` takes `(&'static str, Ticks)` and hides the `Objective` plumbing.
//! - `cmd::Cooldown` takes `(&'static Objective, u32)` for lower-level control.
//!
//! # API hierarchy (see [#146](https://github.com/ThatOneToast/sand/issues/146))
//!
//! 1. **Typed normal API** — `try_*` methods (e.g. [`Cooldown::try_start`],
//!    [`Cooldown::try_ready`]) take a typed [`sand_commands::ScoreHolder`]
//!    (an entity selector, `@s`, a literal player name, or a `#`-prefixed
//!    fake player) and validate it before generating any command text.
//!    Prefer these in new code.
//! 2. **Validated compatibility adapter** — [`sand_commands::scoreboard::Objective`]
//!    offers the same validated surface directly against
//!    [`sand_commands::ObjectiveName`]/[`sand_commands::ScoreHolder`] for
//!    callers that don't need `Cooldown`'s ready/active ergonomics.
//! 3. **Raw escape hatch** — the plain (infallible) methods (e.g.
//!    [`Cooldown::start`], [`Cooldown::ready`]) accept any `impl Display`/`&str`
//!    and interpolate it into command text without validation. They remain
//!    available for compatibility and for advanced/modded selector syntax
//!    Sand cannot yet type-check.
//!
//! Every `try_*` method delegates to its raw counterpart once validation
//! succeeds, so the typed and compatibility paths render byte-identically.

use crate::condition::Condition;
use crate::state::flag::{validate_holder, validate_single_holder};
use crate::state::score::objective_name;
use crate::state::timer::Ticks;

use sand_commands::{CommandResult, ScoreHolder};

// ── Cooldown ──────────────────────────────────────────────────────────────────

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::Cooldown",
    aliases = ["sand::prelude::Cooldown"],
    module = "sand::state",
    summary = "A scoreboard-backed ability cooldown timer with typed condition support.",
    context = "A scoreboard-backed ability cooldown timer with typed condition support. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::Cooldown;",
)]
/// A scoreboard-backed ability cooldown timer with typed condition support.
///
/// ```rust,ignore
/// use sand_core::state::{Cooldown, Ticks};
///
/// static DASH: Cooldown = Cooldown::new("dash", Ticks::new(60));
///
/// let load_cmds = vec![DASH.define()];
/// let tick_cmds = vec![DASH.tick_all_players()];
///
/// // Condition: cooldown is ready (score == 0)
/// let cond = DASH.ready("@s");
/// ```
pub struct Cooldown {
    name: &'static str,
    duration: Ticks,
}

impl Cooldown {
    /// Create a cooldown with the given objective name and duration.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::new",
        aliases = ["sand::prelude::Cooldown::new"],
        module = "sand::state",
        kind = "method",
        summary = "Create a cooldown with the given objective name and duration.",
        context = "Create a cooldown with the given objective name and duration. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(name = "`name` provides the author-visible text value used to create a cooldown with the given objective name and duration.", duration = "`duration` provides the Minecraft tick duration used to create a cooldown with the given objective name and duration."),
        returns = "A newly constructed `Cooldown` configured to create a cooldown with the given objective name and duration.",
        example = "use sand::prelude::*;\n\nfn demonstrate(name: & 'static str, duration: sand::state::Ticks)  {\n    let cooldown = sand::state::Cooldown::new(name, duration);\n}",
    )]
    pub const fn new(name: &'static str, duration: Ticks) -> Self {
        Self { name, duration }
    }

    /// Return the actual scoreboard objective name.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::objective_name",
        aliases = ["sand::prelude::Cooldown::objective_name"],
        module = "sand::state",
        kind = "method",
        summary = "Return the actual scoreboard objective name.",
        context = "Return the actual scoreboard objective name. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Return the actual scoreboard objective name.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown)  {\n    let objective_name = cooldown_value.objective_name();\n}",
    )]
    pub fn objective_name(&self) -> String {
        objective_name(self.name)
    }

    /// `scoreboard objectives add <obj> dummy` — register the objective.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::define",
        aliases = ["sand::prelude::Cooldown::define"],
        module = "sand::state",
        kind = "method",
        summary = "`scoreboard objectives add <obj> dummy` — register the objective.",
        context = "`scoreboard objectives add <obj> dummy` — register the objective. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to emit the documented `scoreboard objectives add <obj> dummy` — register the objective form.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown)  {\n    let define = cooldown_value.define();\n}",
    )]
    pub fn define(&self) -> String {
        format!("scoreboard objectives add {} dummy", self.objective_name())
    }

    /// Set the cooldown score to the configured duration for `selector`.
    ///
    /// Raw compatibility escape hatch: `selector` is an unvalidated string,
    /// interpolated directly into generated commands. Prefer
    /// [`Cooldown::try_start`] in new code — see
    /// [#146](https://github.com/ThatOneToast/sand/issues/146).
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::start",
        aliases = ["sand::prelude::Cooldown::start"],
        module = "sand::state",
        kind = "method",
        summary = "Set the cooldown score to the configured duration for `selector`.",
        context = "Set the cooldown score to the configured duration for `selector`. Raw compatibility escape hatch: `selector` is an unvalidated string, interpolated directly into generated commands. Prefer [`Cooldown::try_start`] in new code — see [#146](https://github.com/ThatOneToast/sand/issues/146).",
        minecraft = "Raw compatibility escape hatch: `selector` is an unvalidated string, interpolated directly into generated commands. Prefer [`Cooldown::try_start`] in new code — see [#146](https://github.com/ThatOneToast/sand/issues/146).",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "Set the cooldown score to the configured duration for `selector`."),
        returns = "The string value produced to set the cooldown score to the configured duration for `selector`.",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let start = cooldown_value.start(selector);\n}",
    )]
    pub fn start(&self, selector: impl std::fmt::Display) -> String {
        format!(
            "scoreboard players set {} {} {}",
            selector,
            self.objective_name(),
            self.duration.get()
        )
    }

    /// Validated counterpart to [`Cooldown::start`] — takes a typed
    /// [`sand_commands::ScoreHolder`] and validates it before generating the
    /// `scoreboard players set` command, instead of interpolating an
    /// unvalidated `Display` value.
    ///
    /// `scoreboard players set` accepts multiple targets, so multi-entity
    /// selectors and the `*` wildcard are permitted here (unlike
    /// [`Cooldown::try_guard`], which builds a score *condition*).
    ///
    /// ```
    /// use sand_core::state::{Cooldown, Ticks};
    /// use sand_commands::ScoreHolder;
    ///
    /// static DASH: Cooldown = Cooldown::new("dash", Ticks::new(60));
    ///
    /// assert_eq!(
    ///     DASH.try_start(ScoreHolder::self_()).unwrap(),
    ///     "scoreboard players set @s dash 60"
    /// );
    /// assert!(DASH.try_start(ScoreHolder::fake("bad holder")).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_start",
        aliases = ["sand::prelude::Cooldown::try_start"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value.",
        context = "Validated counterpart to [`Cooldown::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value. `scoreboard players set` accepts multiple targets, so multi-entity selectors and the `*` wildcard are permitted here (unlike [`Cooldown::try_guard`], which builds a score *condition*).",
        minecraft = "`scoreboard players set` accepts multiple targets, so multi-entity selectors and the `*` wildcard are permitted here (unlike [`Cooldown::try_guard`], which builds a score *condition*).",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value; otherwise, the documented validation or export diagnostic.",
        example = "use {sand::state::Cooldown, sand::state::Ticks};\nuse sand::command::ScoreHolder;\nstatic DASH: Cooldown = Cooldown::new(\"dash\", Ticks::new(60));\nassert_eq!(\nDASH.try_start(ScoreHolder::self_()).unwrap(),\n\"scoreboard players set @s dash 60\"\n);\nassert!(DASH.try_start(ScoreHolder::fake(\"bad holder\")).is_err());",
    )]
    pub fn try_start(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_holder(&holder, "Cooldown::try_start")?;
        Ok(self.start(holder.to_string()))
    }

    /// Reset the cooldown to 0 for `selector` (immediately ready).
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_stop`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::stop",
        aliases = ["sand::prelude::Cooldown::stop"],
        module = "sand::state",
        kind = "method",
        summary = "Reset the cooldown to 0 for `selector` (immediately ready).",
        context = "Reset the cooldown to 0 for `selector` (immediately ready). Raw compatibility escape hatch — prefer [`Cooldown::try_stop`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "Reset the cooldown to 0 for `selector` (immediately ready)."),
        returns = "The string value produced to reset the cooldown to 0 for `selector` (immediately ready).",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let stop = cooldown_value.stop(selector);\n}",
    )]
    pub fn stop(&self, selector: impl std::fmt::Display) -> String {
        format!(
            "scoreboard players set {} {} 0",
            selector,
            self.objective_name()
        )
    }

    /// Validated counterpart to [`Cooldown::stop`] — see
    /// [`Cooldown::try_start`]. Multi-target holders are permitted.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_stop",
        aliases = ["sand::prelude::Cooldown::try_stop"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::stop`] — see [`Cooldown::try_start`]. Multi-target holders are permitted.",
        context = "Validated counterpart to [`Cooldown::stop`] — see [`Cooldown::try_start`]. Multi-target holders are permitted. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::stop`] — see [`Cooldown::try_start`]. Multi-target holders are permitted."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::stop`] — see [`Cooldown::try_start`]. Multi-target holders are permitted; otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_stop = cooldown_value.try_stop(holder);\n}",
    )]
    pub fn try_stop(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_holder(&holder, "Cooldown::try_stop")?;
        Ok(self.stop(holder.to_string()))
    }

    /// Decrement the cooldown by 1 tick for one score holder (only if score > 0).
    ///
    /// Use [`tick_all_players`](Self::tick_all_players) instead of passing a
    /// multi-player selector such as `@a` here.
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_tick`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::tick",
        aliases = ["sand::prelude::Cooldown::tick"],
        module = "sand::state",
        kind = "method",
        summary = "Decrement the cooldown by 1 tick for one score holder (only if score > 0).",
        context = "Decrement the cooldown by 1 tick for one score holder (only if score > 0). Use [`tick_all_players`](Self::tick_all_players) instead of passing a multi-player selector such as `@a` here. Raw compatibility escape hatch — prefer [`Cooldown::try_tick`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Use [`tick_all_players`](Self::tick_all_players) instead of passing a multi-player selector such as `@a` here."],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to decrement the cooldown by 1 tick for one score holder (only if score > 0)."),
        returns = "The string value produced to decrement the cooldown by 1 tick for one score holder (only if score > 0).",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let tick = cooldown_value.tick(selector);\n}",
    )]
    pub fn tick(&self, selector: impl std::fmt::Display) -> String {
        let selector = selector.to_string();
        let obj = self.objective_name();
        format!(
            "execute if score {selector} {obj} matches 1.. run scoreboard players remove {selector} {obj} 1"
        )
    }

    /// Validated counterpart to [`Cooldown::tick`] — takes a typed
    /// [`sand_commands::ScoreHolder`].
    ///
    /// The generated command is guarded by `execute if score <holder> …`,
    /// which requires exactly one score holder, so the `*` wildcard and
    /// multi-entity selectors are rejected via
    /// [`sand_commands::ScoreHolder::validate_single`] — use
    /// [`Cooldown::tick_all_players`] for the per-player `@a` form.
    ///
    /// ```
    /// use sand_core::state::{Cooldown, Ticks};
    /// use sand_commands::ScoreHolder;
    /// use sand_commands::selector::Selector;
    ///
    /// static DASH: Cooldown = Cooldown::new("dash", Ticks::new(60));
    ///
    /// assert_eq!(DASH.try_tick(ScoreHolder::self_()).unwrap(), DASH.tick("@s"));
    /// assert!(DASH.try_tick(ScoreHolder::entity(Selector::all_players())).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_tick",
        aliases = ["sand::prelude::Cooldown::try_tick"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::tick`] — takes a typed [`sand::command::ScoreHolder`].",
        context = "Validated counterpart to [`Cooldown::tick`] — takes a typed [`sand::command::ScoreHolder`]. The generated command is guarded by `execute if score <holder> …`, which requires exactly one score holder, so the `*` wildcard and multi-entity selectors are rejected via [`sand::command::ScoreHolder::validate_single`] — use [`Cooldown::tick_all_players`] for the per-player `@a` form.",
        minecraft = "The generated command is guarded by `execute if score <holder> …`, which requires exactly one score holder, so the `*` wildcard and multi-entity selectors are rejected via [`sand::command::ScoreHolder::validate_single`] — use [`Cooldown::tick_all_players`] for the per-player `@a` form.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::tick`] — takes a typed [`sand::command::ScoreHolder`]."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::tick`] — takes a typed [`sand::command::ScoreHolder`]; otherwise, the documented validation or export diagnostic.",
        example = "use {sand::state::Cooldown, sand::state::Ticks};\nuse sand::command::ScoreHolder;\nuse sand::command::Selector;\nstatic DASH: Cooldown = Cooldown::new(\"dash\", Ticks::new(60));\nassert_eq!(DASH.try_tick(ScoreHolder::self_()).unwrap(), DASH.tick(\"@s\"));\nassert!(DASH.try_tick(ScoreHolder::entity(Selector::all_players())).is_err());",
    )]
    pub fn try_tick(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_single_holder(&holder, "Cooldown::try_tick")?;
        Ok(self.tick(holder.to_string()))
    }

    /// Guard clause: return early if the cooldown is still active (score > 0).
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_guard`].
    ///
    /// Produces: `execute if score <selector> <obj> matches 1.. run return 0`
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::guard",
        aliases = ["sand::prelude::Cooldown::guard"],
        module = "sand::state",
        kind = "method",
        summary = "Guard clause: return early if the cooldown is still active (score > 0).",
        context = "Guard clause: return early if the cooldown is still active (score > 0). Raw compatibility escape hatch — prefer [`Cooldown::try_guard`]. Produces: `execute if score <selector> <obj> matches 1.. run return 0`",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to guard clause: return early if the cooldown is still active (score > 0)."),
        returns = "The string value produced to guard clause: return early if the cooldown is still active (score > 0).",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let guard = cooldown_value.guard(selector);\n}",
    )]
    pub fn guard(&self, selector: impl std::fmt::Display) -> String {
        format!(
            "execute if score {} {} matches 1.. run return 0",
            selector,
            self.objective_name()
        )
    }

    /// Validated counterpart to [`Cooldown::guard`] — takes a typed
    /// [`sand_commands::ScoreHolder`], which must resolve to exactly one score
    /// holder because the guard lowers to `execute if score <holder> …`.
    ///
    /// ```
    /// use sand_core::state::{Cooldown, Ticks};
    /// use sand_commands::ScoreHolder;
    ///
    /// static DASH: Cooldown = Cooldown::new("dash", Ticks::new(60));
    ///
    /// assert_eq!(
    ///     DASH.try_guard(ScoreHolder::self_()).unwrap(),
    ///     "execute if score @s dash matches 1.. run return 0"
    /// );
    /// assert!(DASH.try_guard(ScoreHolder::wildcard()).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_guard",
        aliases = ["sand::prelude::Cooldown::try_guard"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::guard`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`.",
        context = "Validated counterpart to [`Cooldown::guard`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::guard`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::guard`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`; otherwise, the documented validation or export diagnostic.",
        example = "use {sand::state::Cooldown, sand::state::Ticks};\nuse sand::command::ScoreHolder;\nstatic DASH: Cooldown = Cooldown::new(\"dash\", Ticks::new(60));\nassert_eq!(\nDASH.try_guard(ScoreHolder::self_()).unwrap(),\n\"execute if score @s dash matches 1.. run return 0\"\n);\nassert!(DASH.try_guard(ScoreHolder::wildcard()).is_err());",
    )]
    pub fn try_guard(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_single_holder(&holder, "Cooldown::try_guard")?;
        Ok(self.guard(holder.to_string()))
    }

    /// Condition: cooldown is ready (`if score <sel> <obj> matches 0`).
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_ready`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::ready",
        aliases = ["sand::prelude::Cooldown::ready"],
        module = "sand::state",
        kind = "method",
        summary = "Condition: cooldown is ready (`if score <sel> <obj> matches 0`).",
        context = "Condition: cooldown is ready (`if score <sel> <obj> matches 0`). Raw compatibility escape hatch — prefer [`Cooldown::try_ready`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to condition cooldown is ready (`if score <sel> <obj> matches 0`)."),
        returns = "The `Condition` value produced to condition cooldown is ready (`if score <sel> <obj> matches 0`).",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: & str)  {\n    let ready = cooldown_value.ready(selector);\n}",
    )]
    pub fn ready(&self, selector: &str) -> Condition {
        Condition::score(
            selector.to_string(),
            self.objective_name(),
            crate::condition::ScoreRange::Eq(0),
        )
    }

    /// Validated counterpart to [`Cooldown::ready`] — takes a typed
    /// [`sand_commands::ScoreHolder`], which must resolve to exactly one score
    /// holder because the result lowers to `execute if score <holder> …`.
    ///
    /// ```
    /// use sand_core::execute_when::when;
    /// use sand_core::state::{Cooldown, Ticks};
    /// use sand_commands::ScoreHolder;
    ///
    /// static DASH: Cooldown = Cooldown::new("dash", Ticks::new(60));
    ///
    /// let cond = DASH.try_ready(ScoreHolder::self_()).unwrap();
    /// assert_eq!(
    ///     when(cond).then_one("say ok"),
    ///     vec!["execute if score @s dash matches 0 run say ok"]
    /// );
    /// assert!(DASH.try_ready(ScoreHolder::wildcard()).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_ready",
        aliases = ["sand::prelude::Cooldown::try_ready"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::ready`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`.",
        context = "Validated counterpart to [`Cooldown::ready`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::ready`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::ready`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`; otherwise, the documented validation or export diagnostic.",
        example = "use sand::execute_when::when;\nuse {sand::state::Cooldown, sand::state::Ticks};\nuse sand::command::ScoreHolder;\nstatic DASH: Cooldown = Cooldown::new(\"dash\", Ticks::new(60));\nlet cond = DASH.try_ready(ScoreHolder::self_()).unwrap();\nassert_eq!(\nwhen(cond).then_one(\"say ok\"),\nvec![\"execute if score @s dash matches 0 run say ok\"]\n);\nassert!(DASH.try_ready(ScoreHolder::wildcard()).is_err());",
    )]
    pub fn try_ready(&self, holder: impl Into<ScoreHolder>) -> CommandResult<Condition> {
        let holder = holder.into();
        validate_single_holder(&holder, "Cooldown::try_ready")?;
        Ok(self.ready(&holder.to_string()))
    }

    /// Condition: cooldown is active (`if score <sel> <obj> matches 1..`).
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_active`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::active",
        aliases = ["sand::prelude::Cooldown::active"],
        module = "sand::state",
        kind = "method",
        summary = "Condition: cooldown is active (`if score <sel> <obj> matches 1..`).",
        context = "Condition: cooldown is active (`if score <sel> <obj> matches 1..`). Raw compatibility escape hatch — prefer [`Cooldown::try_active`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to condition cooldown is active (`if score <sel> <obj> matches 1..`)."),
        returns = "The `Condition` value produced to condition cooldown is active (`if score <sel> <obj> matches 1..`).",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: & str)  {\n    let active = cooldown_value.active(selector);\n}",
    )]
    pub fn active(&self, selector: &str) -> Condition {
        Condition::score(
            selector.to_string(),
            self.objective_name(),
            crate::condition::ScoreRange::Gte(1),
        )
    }

    /// Validated counterpart to [`Cooldown::active`] — see
    /// [`Cooldown::try_ready`]; the holder must resolve to exactly one score
    /// holder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_active",
        aliases = ["sand::prelude::Cooldown::try_active"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::active`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder.",
        context = "Validated counterpart to [`Cooldown::active`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::active`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::active`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder; otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_active = cooldown_value.try_active(holder);\n}",
    )]
    pub fn try_active(&self, holder: impl Into<ScoreHolder>) -> CommandResult<Condition> {
        let holder = holder.into();
        validate_single_holder(&holder, "Cooldown::try_active")?;
        Ok(self.active(&holder.to_string()))
    }

    /// Alias for [`ready`](Cooldown::ready) — more intuitive name when thinking about
    /// whether the timer has "expired" (counted down to zero).
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_expired`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::expired",
        aliases = ["sand::prelude::Cooldown::expired"],
        module = "sand::state",
        kind = "method",
        summary = "Alias for [`ready`](Cooldown::ready) — more intuitive name when thinking about whether the timer has \"expired\" (counted down to zero).",
        context = "Alias for [`ready`](Cooldown::ready) — more intuitive name when thinking about whether the timer has \"expired\" (counted down to zero). Raw compatibility escape hatch — prefer [`Cooldown::try_expired`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to use alias for [`ready`](Cooldown::ready) — more intuitive name when thinking about whether the timer has \"expired\" (counted down to zero)."),
        returns = "The `Condition` value produced to use alias for [`ready`](Cooldown::ready) — more intuitive name when thinking about whether the timer has \"expired\" (counted down to zero).",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: & str)  {\n    let expired = cooldown_value.expired(selector);\n}",
    )]
    pub fn expired(&self, selector: &str) -> Condition {
        self.ready(selector)
    }

    /// Validated counterpart to [`Cooldown::expired`] — see
    /// [`Cooldown::try_ready`]; the holder must resolve to exactly one score
    /// holder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_expired",
        aliases = ["sand::prelude::Cooldown::try_expired"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::expired`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder.",
        context = "Validated counterpart to [`Cooldown::expired`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::expired`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::expired`] — see [`Cooldown::try_ready`]; the holder must resolve to exactly one score holder; otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_expired = cooldown_value.try_expired(holder);\n}",
    )]
    pub fn try_expired(&self, holder: impl Into<ScoreHolder>) -> CommandResult<Condition> {
        let holder = holder.into();
        validate_single_holder(&holder, "Cooldown::try_expired")?;
        Ok(self.expired(&holder.to_string()))
    }

    /// Alias for [`start`](Cooldown::start) — emphasizes the selector context.
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_start_for`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::start_for",
        aliases = ["sand::prelude::Cooldown::start_for"],
        module = "sand::state",
        kind = "method",
        summary = "Alias for [`start`](Cooldown::start) — emphasizes the selector context.",
        context = "Alias for [`start`](Cooldown::start) — emphasizes the selector context. Raw compatibility escape hatch — prefer [`Cooldown::try_start_for`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to use alias for [`start`](Cooldown::start) — emphasizes the selector context."),
        returns = "The string value produced to use alias for [`start`](Cooldown::start) — emphasizes the selector context.",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let start_for = cooldown_value.start_for(selector);\n}",
    )]
    pub fn start_for(&self, selector: impl std::fmt::Display) -> String {
        self.start(selector)
    }

    /// Validated counterpart to [`Cooldown::start_for`] — see
    /// [`Cooldown::try_start`]. Multi-target holders are permitted.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_start_for",
        aliases = ["sand::prelude::Cooldown::try_start_for"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::start_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted.",
        context = "Validated counterpart to [`Cooldown::start_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::start_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::start_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted; otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_start_for = cooldown_value.try_start_for(holder);\n}",
    )]
    pub fn try_start_for(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_holder(&holder, "Cooldown::try_start_for")?;
        Ok(self.start_for(holder.to_string()))
    }

    /// Alias for [`stop`](Cooldown::stop) — resets the cooldown to zero immediately.
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_reset_for`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::reset_for",
        aliases = ["sand::prelude::Cooldown::reset_for"],
        module = "sand::state",
        kind = "method",
        summary = "Alias for [`stop`](Cooldown::stop) — resets the cooldown to zero immediately.",
        context = "Alias for [`stop`](Cooldown::stop) — resets the cooldown to zero immediately. Raw compatibility escape hatch — prefer [`Cooldown::try_reset_for`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to use alias for [`stop`](Cooldown::stop) — resets the cooldown to zero immediately."),
        returns = "The string value produced to use alias for [`stop`](Cooldown::stop) — resets the cooldown to zero immediately.",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let reset_for = cooldown_value.reset_for(selector);\n}",
    )]
    pub fn reset_for(&self, selector: impl std::fmt::Display) -> String {
        self.stop(selector)
    }

    /// Validated counterpart to [`Cooldown::reset_for`] — see
    /// [`Cooldown::try_start`]. Multi-target holders are permitted.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_reset_for",
        aliases = ["sand::prelude::Cooldown::try_reset_for"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::reset_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted.",
        context = "Validated counterpart to [`Cooldown::reset_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::reset_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::reset_for`] — see [`Cooldown::try_start`]. Multi-target holders are permitted; otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_reset_for = cooldown_value.try_reset_for(holder);\n}",
    )]
    pub fn try_reset_for(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_holder(&holder, "Cooldown::try_reset_for")?;
        Ok(self.reset_for(holder.to_string()))
    }

    /// Tick the cooldown for all players (`@a`).
    ///
    /// Convenience for placing in a `#[datapack_component(Tick)]` function. Takes no
    /// score holder — the `@a`/`@s` pair is generated by Sand and is always
    /// valid, so there is no `try_*` counterpart.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::tick_all_players",
        aliases = ["sand::prelude::Cooldown::tick_all_players"],
        module = "sand::state",
        kind = "method",
        summary = "Tick the cooldown for all players (`@a`). Convenience for placing in a `#[datapack_component(Tick)]` function. Takes no score holder — the `@a`/`@s` pair is generated by Sand and is always valid, so there is no `try_*` counterpart.",
        context = "Tick the cooldown for all players (`@a`). Convenience for placing in a `#[datapack_component(Tick)]` function. Takes no score holder — the `@a`/`@s` pair is generated by Sand and is always valid, so there is no `try_*` counterpart. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Convenience for placing in a `#[datapack_component(Tick)]` function. Takes no score holder — the `@a`/`@s` pair is generated by Sand and is always valid, so there is no `try_*` counterpart.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to tick the cooldown for all players (`@a`). Convenience for placing in a `#[datapack_component(Tick)]` function. Takes no score holder — the `@a`/`@s` pair is generated by Sand and is always valid, so there is no `try_*` counterpart.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown)  {\n    let tick_all_players = cooldown_value.tick_all_players();\n}",
    )]
    pub fn tick_all_players(&self) -> String {
        let obj = self.objective_name();
        format!(
            "execute as @a if score @s {obj} matches 1.. run scoreboard players remove @s {obj} 1"
        )
    }

    /// Alias for [`guard`](Cooldown::guard) — guards if the cooldown is NOT ready.
    ///
    /// Returns early (`return 0`) if the cooldown is still active.
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_guard_active`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::guard_active",
        aliases = ["sand::prelude::Cooldown::guard_active"],
        module = "sand::state",
        kind = "method",
        summary = "Alias for [`guard`](Cooldown::guard) — guards if the cooldown is NOT ready.",
        context = "Alias for [`guard`](Cooldown::guard) — guards if the cooldown is NOT ready. Returns early (`return 0`) if the cooldown is still active. Raw compatibility escape hatch — prefer [`Cooldown::try_guard_active`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to use alias for [`guard`](Cooldown::guard) — guards if the cooldown is NOT ready."),
        returns = "Returns early (`return 0`) if the cooldown is still active.",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let guard_active = cooldown_value.guard_active(selector);\n}",
    )]
    pub fn guard_active(&self, selector: impl std::fmt::Display) -> String {
        self.guard(selector)
    }

    /// Validated counterpart to [`Cooldown::guard_active`] — see
    /// [`Cooldown::try_guard`]; the holder must resolve to exactly one score
    /// holder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_guard_active",
        aliases = ["sand::prelude::Cooldown::try_guard_active"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::guard_active`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder.",
        context = "Validated counterpart to [`Cooldown::guard_active`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::guard_active`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::guard_active`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder; otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_guard_active = cooldown_value.try_guard_active(holder);\n}",
    )]
    pub fn try_guard_active(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_single_holder(&holder, "Cooldown::try_guard_active")?;
        Ok(self.guard_active(holder.to_string()))
    }

    /// Guard clause: return early if the cooldown IS ready (score == 0).
    ///
    /// Useful when you only want to run logic while the cooldown is active.
    ///
    /// Raw compatibility escape hatch — prefer [`Cooldown::try_guard_ready`].
    ///
    /// Produces: `execute if score <selector> <obj> matches 0 run return 0`
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::guard_ready",
        aliases = ["sand::prelude::Cooldown::guard_ready"],
        module = "sand::state",
        kind = "method",
        summary = "Guard clause: return early if the cooldown IS ready (score == 0).",
        context = "Guard clause: return early if the cooldown IS ready (score == 0). Useful when you only want to run logic while the cooldown is active. Raw compatibility escape hatch — prefer [`Cooldown::try_guard_ready`]. Produces: `execute if score <selector> <obj> matches 0 run return 0`",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to guard clause: return early if the cooldown IS ready (score == 0)."),
        returns = "The string value produced to guard clause: return early if the cooldown IS ready (score == 0).",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown, selector: impl std::fmt::Display)  {\n    let guard_ready = cooldown_value.guard_ready(selector);\n}",
    )]
    pub fn guard_ready(&self, selector: impl std::fmt::Display) -> String {
        format!(
            "execute if score {} {} matches 0 run return 0",
            selector,
            self.objective_name()
        )
    }

    /// Validated counterpart to [`Cooldown::guard_ready`] — see
    /// [`Cooldown::try_guard`]; the holder must resolve to exactly one score
    /// holder.
    ///
    /// ```
    /// use sand_core::state::{Cooldown, Ticks};
    /// use sand_commands::ScoreHolder;
    ///
    /// static DASH: Cooldown = Cooldown::new("dash", Ticks::new(60));
    ///
    /// assert_eq!(
    ///     DASH.try_guard_ready(ScoreHolder::self_()).unwrap(),
    ///     "execute if score @s dash matches 0 run return 0"
    /// );
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::try_guard_ready",
        aliases = ["sand::prelude::Cooldown::try_guard_ready"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Cooldown::guard_ready`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder.",
        context = "Validated counterpart to [`Cooldown::guard_ready`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` supplies the holder value used to use validated counterpart to [`Cooldown::guard_ready`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder."),
        returns = "On success, the value produced to use validated counterpart to [`Cooldown::guard_ready`] — see [`Cooldown::try_guard`]; the holder must resolve to exactly one score holder; otherwise, the documented validation or export diagnostic.",
        example = "use {sand::state::Cooldown, sand::state::Ticks};\nuse sand::command::ScoreHolder;\nstatic DASH: Cooldown = Cooldown::new(\"dash\", Ticks::new(60));\nassert_eq!(\nDASH.try_guard_ready(ScoreHolder::self_()).unwrap(),\n\"execute if score @s dash matches 0 run return 0\"\n);",
    )]
    pub fn try_guard_ready(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_single_holder(&holder, "Cooldown::try_guard_ready")?;
        Ok(self.guard_ready(holder.to_string()))
    }

    /// Return the configured duration.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Cooldown::duration",
        aliases = ["sand::prelude::Cooldown::duration"],
        module = "sand::state",
        kind = "method",
        summary = "Return the configured duration.",
        context = "Return the configured duration. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Return the configured duration.",
        example = "use sand::prelude::*;\n\nfn demonstrate(cooldown_value: &sand::state::Cooldown)  {\n    let duration = cooldown_value.duration();\n}",
    )]
    pub fn duration(&self) -> Ticks {
        self.duration
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::condition::{ConditionKind, ScoreRange};

    static DASH: Cooldown = Cooldown::new("dash", Ticks::new(60));

    #[test]
    fn define_cmd() {
        assert_eq!(DASH.define(), "scoreboard objectives add dash dummy");
    }

    #[test]
    fn start_cmd() {
        assert_eq!(DASH.start("@s"), "scoreboard players set @s dash 60");
    }

    #[test]
    fn stop_cmd() {
        assert_eq!(DASH.stop("@s"), "scoreboard players set @s dash 0");
    }

    #[test]
    fn tick_cmd() {
        let cmd = DASH.tick("@s");
        assert!(cmd.contains("matches 1.."), "got: {cmd}");
        assert!(cmd.contains("remove @s dash 1"), "got: {cmd}");
    }

    #[test]
    fn tick_all_players_is_per_player_safe() {
        let command = DASH.tick_all_players();
        assert_eq!(command, DASH.tick_all_players());
        assert_eq!(
            command,
            "execute as @a if score @s dash matches 1.. run scoreboard players remove @s dash 1"
        );
        assert!(!command.contains("if score @a"));
        assert!(!command.contains("remove @a"));
    }

    #[test]
    fn guard_cmd() {
        let cmd = DASH.guard("@s");
        assert_eq!(cmd, "execute if score @s dash matches 1.. run return 0");
    }

    #[test]
    fn ready_condition() {
        let cond = DASH.ready("@s");
        match cond.kind() {
            ConditionKind::Score {
                selector,
                objective,
                range: ScoreRange::Eq(0),
            } => {
                assert_eq!(selector, "@s");
                assert_eq!(objective, "dash");
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn active_condition() {
        let cond = DASH.active("@s");
        match cond.kind() {
            ConditionKind::Score {
                range: ScoreRange::Gte(1),
                ..
            } => {}
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn expired_is_alias_for_ready() {
        let a = DASH.expired("@s");
        let b = DASH.ready("@s");
        // Both should be Eq(0)
        assert!(matches!(
            a.kind(),
            ConditionKind::Score {
                range: ScoreRange::Eq(0),
                ..
            }
        ));
        assert!(matches!(
            b.kind(),
            ConditionKind::Score {
                range: ScoreRange::Eq(0),
                ..
            }
        ));
    }

    #[test]
    fn start_for_is_start() {
        assert_eq!(DASH.start_for("@s"), DASH.start("@s"));
    }

    #[test]
    fn reset_for_is_stop() {
        assert_eq!(DASH.reset_for("@s"), DASH.stop("@s"));
    }

    #[test]
    fn tick_all_players() {
        assert_eq!(
            DASH.tick_all_players(),
            "execute as @a if score @s dash matches 1.. run scoreboard players remove @s dash 1"
        );
    }

    #[test]
    fn guard_ready_cmd() {
        let cmd = DASH.guard_ready("@s");
        assert_eq!(cmd, "execute if score @s dash matches 0 run return 0");
    }

    #[test]
    fn guard_active_is_guard() {
        assert_eq!(DASH.guard_active("@s"), DASH.guard("@s"));
    }
}
