//! Optional custom hooks for generated State component lifecycle work.

use crate::entity::{AnyEntity, EntityContext, EntityState, PlayerKind};

/// Context supplied while a component is initialized.
///
#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::StateInit",
    aliases = ["sand::prelude::StateInit"],
    module = "sand::state",
    summary = "Context supplied while a component is initialized.",
    context = "Context supplied while a component is initialized. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::StateInit;",
)]
#[derive(Debug, Clone, Copy)]
pub struct StateInit {
    holder: &'static str,
}
/// Context supplied for one eligible component tick.
///
#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::StateTick",
    aliases = ["sand::prelude::StateTick"],
    module = "sand::state",
    summary = "Context supplied for one eligible component tick.",
    context = "Context supplied for one eligible component tick. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::StateTick;",
)]
#[derive(Debug, Clone, Copy)]
pub struct StateTick {
    holder: &'static str,
}
/// Context supplied while owned runtime state is reconciled.
///
#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::StateReconcile",
    aliases = ["sand::prelude::StateReconcile"],
    module = "sand::state",
    summary = "Context supplied while owned runtime state is reconciled.",
    context = "Context supplied while owned runtime state is reconciled. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::StateReconcile;",
)]
#[derive(Debug, Clone, Copy)]
pub struct StateReconcile {
    holder: &'static str,
}
/// Context supplied before component-owned values are removed.
///
#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::StateCleanup",
    aliases = ["sand::prelude::StateCleanup"],
    module = "sand::state",
    summary = "Context supplied before component-owned values are removed.",
    context = "Context supplied before component-owned values are removed. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::StateCleanup;",
)]
#[derive(Debug, Clone, Copy)]
pub struct StateCleanup {
    holder: &'static str,
}

impl StateInit {
    /// Constructs generated initialization context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateInit::new",
        aliases = ["sand::prelude::StateInit::new"],
        module = "sand::state",
        kind = "method",
        summary = "Constructs generated initialization context.",
        context = "Constructs generated initialization context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` is used when constructing generated initialization context."),
        returns = "A `StateInit` representing generated initialization context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(holder: & 'static str)  {\n    let state_init = sand::state::StateInit::new(holder);\n}",
    )]
    pub const fn new(holder: &'static str) -> Self {
        Self { holder }
    }
    /// Score holder used by initialization.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateInit::holder",
        aliases = ["sand::prelude::StateInit::holder"],
        module = "sand::state",
        kind = "method",
        summary = "Score holder used by initialization.",
        context = "Score holder used by initialization. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to score holder used by initialization.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_init_value: sand::state::StateInit)  {\n    let holder = state_init_value.holder();\n}",
    )]
    #[must_use]
    pub const fn holder(self) -> &'static str {
        self.holder
    }
    /// Typed current-entity context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateInit::entity",
        aliases = ["sand::prelude::StateInit::entity"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-entity context.",
        context = "Typed current-entity context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext < AnyEntity >` value produced to typed current-entity context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_init_value: sand::state::StateInit)  {\n    let entity = state_init_value.entity();\n}",
    )]
    #[must_use]
    pub fn entity(self) -> EntityContext<AnyEntity> {
        EntityContext::default()
    }
    /// Typed current-player context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateInit::player",
        aliases = ["sand::prelude::StateInit::player"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-player context.",
        context = "Typed current-player context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext<PlayerKind>` value produced to typed current-player context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_init_value: sand::state::StateInit)  {\n    let player = state_init_value.player();\n}",
    )]
    #[must_use]
    pub fn player(self) -> EntityContext<PlayerKind> {
        EntityContext::<PlayerKind>::default()
    }
}
impl StateTick {
    /// Constructs generated tick context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateTick::new",
        aliases = ["sand::prelude::StateTick::new"],
        module = "sand::state",
        kind = "method",
        summary = "Constructs generated tick context.",
        context = "Constructs generated tick context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` is used when constructing generated tick context."),
        returns = "A `StateTick` representing generated tick context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(holder: & 'static str)  {\n    let state_tick = sand::state::StateTick::new(holder);\n}",
    )]
    pub const fn new(holder: &'static str) -> Self {
        Self { holder }
    }
    /// Score holder used by ticking.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateTick::holder",
        aliases = ["sand::prelude::StateTick::holder"],
        module = "sand::state",
        kind = "method",
        summary = "Score holder used by ticking.",
        context = "Score holder used by ticking. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to score holder used by ticking.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_tick_value: sand::state::StateTick)  {\n    let holder = state_tick_value.holder();\n}",
    )]
    #[must_use]
    pub const fn holder(self) -> &'static str {
        self.holder
    }
    /// Typed current-entity context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateTick::entity",
        aliases = ["sand::prelude::StateTick::entity"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-entity context.",
        context = "Typed current-entity context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext < AnyEntity >` value produced to typed current-entity context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_tick_value: sand::state::StateTick)  {\n    let entity = state_tick_value.entity();\n}",
    )]
    #[must_use]
    pub fn entity(self) -> EntityContext<AnyEntity> {
        EntityContext::default()
    }
    /// Typed current-player context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateTick::player",
        aliases = ["sand::prelude::StateTick::player"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-player context.",
        context = "Typed current-player context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext<PlayerKind>` value produced to typed current-player context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_tick_value: sand::state::StateTick)  {\n    let player = state_tick_value.player();\n}",
    )]
    #[must_use]
    pub fn player(self) -> EntityContext<PlayerKind> {
        EntityContext::<PlayerKind>::default()
    }
}
impl StateReconcile {
    /// Constructs generated reconciliation context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateReconcile::new",
        aliases = ["sand::prelude::StateReconcile::new"],
        module = "sand::state",
        kind = "method",
        summary = "Constructs generated reconciliation context.",
        context = "Constructs generated reconciliation context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` is used when constructing generated reconciliation context."),
        returns = "A `StateReconcile` representing generated reconciliation context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(holder: & 'static str)  {\n    let state_reconcile = sand::state::StateReconcile::new(holder);\n}",
    )]
    pub const fn new(holder: &'static str) -> Self {
        Self { holder }
    }
    /// Score holder used by reconciliation.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateReconcile::holder",
        aliases = ["sand::prelude::StateReconcile::holder"],
        module = "sand::state",
        kind = "method",
        summary = "Score holder used by reconciliation.",
        context = "Score holder used by reconciliation. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to score holder used by reconciliation.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_reconcile_value: sand::state::StateReconcile)  {\n    let holder = state_reconcile_value.holder();\n}",
    )]
    #[must_use]
    pub const fn holder(self) -> &'static str {
        self.holder
    }
    /// Typed current-entity context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateReconcile::entity",
        aliases = ["sand::prelude::StateReconcile::entity"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-entity context.",
        context = "Typed current-entity context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext < AnyEntity >` value produced to typed current-entity context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_reconcile_value: sand::state::StateReconcile)  {\n    let entity = state_reconcile_value.entity();\n}",
    )]
    #[must_use]
    pub fn entity(self) -> EntityContext<AnyEntity> {
        EntityContext::default()
    }
    /// Typed current-player context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateReconcile::player",
        aliases = ["sand::prelude::StateReconcile::player"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-player context.",
        context = "Typed current-player context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext<PlayerKind>` value produced to typed current-player context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_reconcile_value: sand::state::StateReconcile)  {\n    let player = state_reconcile_value.player();\n}",
    )]
    #[must_use]
    pub fn player(self) -> EntityContext<PlayerKind> {
        EntityContext::<PlayerKind>::default()
    }
}
impl StateCleanup {
    /// Constructs generated cleanup context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateCleanup::new",
        aliases = ["sand::prelude::StateCleanup::new"],
        module = "sand::state",
        kind = "method",
        summary = "Constructs generated cleanup context.",
        context = "Constructs generated cleanup context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` is used when constructing generated cleanup context."),
        returns = "A `StateCleanup` representing generated cleanup context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(holder: & 'static str)  {\n    let state_cleanup = sand::state::StateCleanup::new(holder);\n}",
    )]
    pub const fn new(holder: &'static str) -> Self {
        Self { holder }
    }
    /// Score holder used by cleanup.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateCleanup::holder",
        aliases = ["sand::prelude::StateCleanup::holder"],
        module = "sand::state",
        kind = "method",
        summary = "Score holder used by cleanup.",
        context = "Score holder used by cleanup. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to score holder used by cleanup.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_cleanup_value: sand::state::StateCleanup)  {\n    let holder = state_cleanup_value.holder();\n}",
    )]
    #[must_use]
    pub const fn holder(self) -> &'static str {
        self.holder
    }
    /// Typed current-entity context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateCleanup::entity",
        aliases = ["sand::prelude::StateCleanup::entity"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-entity context.",
        context = "Typed current-entity context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext < AnyEntity >` value produced to typed current-entity context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_cleanup_value: sand::state::StateCleanup)  {\n    let entity = state_cleanup_value.entity();\n}",
    )]
    #[must_use]
    pub fn entity(self) -> EntityContext<AnyEntity> {
        EntityContext::default()
    }
    /// Typed current-player context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateCleanup::player",
        aliases = ["sand::prelude::StateCleanup::player"],
        module = "sand::state",
        kind = "method",
        summary = "Typed current-player context.",
        context = "Typed current-player context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `EntityContext<PlayerKind>` value produced to typed current-player context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_cleanup_value: sand::state::StateCleanup)  {\n    let player = state_cleanup_value.player();\n}",
    )]
    #[must_use]
    pub fn player(self) -> EntityContext<PlayerKind> {
        EntityContext::<PlayerKind>::default()
    }
}

/// Context supplied while shared component dependencies are provisioned.
///
#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::StateProvision",
    aliases = ["sand::prelude::StateProvision"],
    module = "sand::state",
    summary = "Context supplied while shared component dependencies are provisioned.",
    context = "Context supplied while shared component dependencies are provisioned. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::StateProvision;",
)]
#[derive(Debug, Clone, Copy, Default)]
pub struct StateProvision;

/// Context supplied for one declared component migration transition.
///
#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::StateMigrate",
    aliases = ["sand::prelude::StateMigrate"],
    module = "sand::state",
    summary = "Context supplied for one declared component migration transition.",
    context = "Context supplied for one declared component migration transition. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::StateMigrate;",
)]
#[derive(Debug, Clone, Copy)]
pub struct StateMigrate {
    holder: &'static str,
    from: u32,
    to: u32,
}

impl StateMigrate {
    /// Constructs generated migration context.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateMigrate::new",
        aliases = ["sand::prelude::StateMigrate::new"],
        module = "sand::state",
        kind = "method",
        summary = "Constructs generated migration context.",
        context = "Constructs generated migration context. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` is used when constructing generated migration context.", from = "`from` is used when constructing generated migration context.", to = "`to` is used when constructing generated migration context."),
        returns = "A `StateMigrate` representing generated migration context.",
        example = "use sand::prelude::*;\n\nfn demonstrate(holder: & 'static str, from: u32, to: u32)  {\n    let state_migrate = sand::state::StateMigrate::new(holder, from, to);\n}",
    )]
    pub const fn new(holder: &'static str, from: u32, to: u32) -> Self {
        Self { holder, from, to }
    }

    /// Current score holder.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateMigrate::holder",
        aliases = ["sand::prelude::StateMigrate::holder"],
        module = "sand::state",
        kind = "method",
        summary = "Current score holder.",
        context = "Current score holder. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to current score holder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_migrate_value: sand::state::StateMigrate)  {\n    let holder = state_migrate_value.holder();\n}",
    )]
    #[must_use]
    pub const fn holder(self) -> &'static str {
        self.holder
    }

    /// Source version for this transition.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateMigrate::from",
        aliases = ["sand::prelude::StateMigrate::from"],
        module = "sand::state",
        kind = "method",
        summary = "Source version for this transition.",
        context = "Source version for this transition. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `u32` value produced to source version for this transition.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_migrate_value: sand::state::StateMigrate)  {\n    let from = state_migrate_value.from();\n}",
    )]
    #[must_use]
    pub const fn from(self) -> u32 {
        self.from
    }

    /// Destination version for this transition.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateMigrate::to",
        aliases = ["sand::prelude::StateMigrate::to"],
        module = "sand::state",
        kind = "method",
        summary = "Destination version for this transition.",
        context = "Destination version for this transition. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `u32` value produced to destination version for this transition.",
        example = "use sand::prelude::*;\n\nfn demonstrate(state_migrate_value: sand::state::StateMigrate)  {\n    let to = state_migrate_value.to();\n}",
    )]
    #[must_use]
    pub const fn to(self) -> u32 {
        self.to
    }
}

/// Optional custom behavior around an automatically generated State lifecycle.
///
/// Every hook defaults to no commands. Implementations are registered with
/// `#[state_lifecycle]`; State's generated provisioning, initialization,
/// version publication, and ownership-safe cleanup remain authoritative.
///
#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::StateLifecycle",
    aliases = ["sand::prelude::StateLifecycle"],
    module = "sand::state",
    summary = "Optional custom behavior around an automatically generated State lifecycle.",
    context = "Optional custom behavior around an automatically generated State lifecycle. Every hook defaults to no commands. Implementations are registered with `#[state_lifecycle]`; State's generated provisioning, initialization, version publication, and ownership-safe cleanup remain authoritative.",
    minecraft = "Every hook defaults to no commands. Implementations are registered with `#[state_lifecycle]`; State's generated provisioning, initialization, version publication, and ownership-safe cleanup remain authoritative.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::StateLifecycle;",
)]
pub trait StateLifecycle: EntityState {
    /// Add shared load-time dependencies beyond inferred field backends.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateLifecycle::provision", kind = "trait_method",
        aliases = ["sand::prelude::StateLifecycle::provision"],
        module = "sand::state",
        summary = "Add shared load-time dependencies beyond inferred field backends.",
        context = "Add shared load-time dependencies beyond inferred field backends. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(_ctx = "`ctx` provides the ctx added when building shared load-time dependencies beyond inferred field backends."),
        returns = "The ordered values produced to add shared load-time dependencies beyond inferred field backends.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::StateLifecycle>(ctx: sand::state::StateProvision)  {\n    let values = <T as sand::state::StateLifecycle>::provision(ctx);\n}",
    )]
    fn provision(_ctx: StateProvision) -> Vec<String> {
        Vec::new()
    }

    /// Run after missing owned values are initialized and before presence is published.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateLifecycle::initialize", kind = "trait_method",
        aliases = ["sand::prelude::StateLifecycle::initialize"],
        module = "sand::state",
        summary = "Run after missing owned values are initialized and before presence is published.",
        context = "Run after missing owned values are initialized and before presence is published. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(_ctx = "`ctx` provides the ctx used when running after missing owned values are initialized and before presence is published."),
        returns = "The ordered values produced to run after missing owned values are initialized and before presence is published.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::StateLifecycle>(ctx: sand::state::StateInit)  {\n    let values = <T as sand::state::StateLifecycle>::initialize(ctx);\n}",
    )]
    fn initialize(_ctx: StateInit) -> Vec<String> {
        Vec::new()
    }

    /// Run once for each eligible loaded owner at the planned cadence.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateLifecycle::tick", kind = "trait_method",
        aliases = ["sand::prelude::StateLifecycle::tick"],
        module = "sand::state",
        summary = "Run once for each eligible loaded owner at the planned cadence.",
        context = "Run once for each eligible loaded owner at the planned cadence. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(_ctx = "`ctx` provides the ctx used when running once for each eligible loaded owner at the planned cadence."),
        returns = "The ordered values produced to run once for each eligible loaded owner at the planned cadence.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::StateLifecycle>(ctx: sand::state::StateTick)  {\n    let values = <T as sand::state::StateLifecycle>::tick(ctx);\n}",
    )]
    fn tick(_ctx: StateTick) -> Vec<String> {
        Vec::new()
    }

    /// Reconcile component-owned native properties.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateLifecycle::reconcile", kind = "trait_method",
        aliases = ["sand::prelude::StateLifecycle::reconcile"],
        module = "sand::state",
        summary = "Reconcile component-owned native properties.",
        context = "Reconcile component-owned native properties. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(_ctx = "`ctx` is used to reconcile component-owned native properties."),
        returns = "The ordered values produced to reconcile component-owned native properties.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::StateLifecycle>(ctx: sand::state::StateReconcile)  {\n    let values = <T as sand::state::StateLifecycle>::reconcile(ctx);\n}",
    )]
    fn reconcile(_ctx: StateReconcile) -> Vec<String> {
        Vec::new()
    }

    /// Run one explicitly registered version transition.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateLifecycle::migrate", kind = "trait_method",
        aliases = ["sand::prelude::StateLifecycle::migrate"],
        module = "sand::state",
        summary = "Run one explicitly registered version transition.",
        context = "Run one explicitly registered version transition. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(_ctx = "`ctx` provides the ctx used when running one explicitly registered version transition."),
        returns = "The ordered values produced to run one explicitly registered version transition.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::StateLifecycle>(ctx: sand::state::StateMigrate)  {\n    let values = <T as sand::state::StateLifecycle>::migrate(ctx);\n}",
    )]
    fn migrate(_ctx: StateMigrate) -> Vec<String> {
        Vec::new()
    }

    /// Run before component-owned values and bookkeeping are removed.
    ///
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::StateLifecycle::cleanup", kind = "trait_method",
        aliases = ["sand::prelude::StateLifecycle::cleanup"],
        module = "sand::state",
        summary = "Run before component-owned values and bookkeeping are removed.",
        context = "Run before component-owned values and bookkeeping are removed. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(_ctx = "`ctx` provides the ctx used when running before component-owned values and bookkeeping are removed."),
        returns = "The ordered values produced to run before component-owned values and bookkeeping are removed.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::StateLifecycle>(ctx: sand::state::StateCleanup)  {\n    let values = <T as sand::state::StateLifecycle>::cleanup(ctx);\n}",
    )]
    fn cleanup(_ctx: StateCleanup) -> Vec<String> {
        Vec::new()
    }
}
