//! Tick-based duration and timer utilities.
//!
//! # API hierarchy (see [#146](https://github.com/ThatOneToast/sand/issues/146))
//!
//! 1. **Typed normal API** — `try_*` methods (e.g. [`Timer::try_start`],
//!    [`Timer::try_active`]) take a typed [`sand_commands::ScoreHolder`]
//!    (an entity selector, `@s`, a literal player name, or a `#`-prefixed
//!    fake player) and validate it before generating any command text.
//!    Prefer these in new code.
//! 2. **Validated compatibility adapter** — [`sand_commands::scoreboard::Objective`]
//!    offers the same validated surface directly against
//!    [`sand_commands::ObjectiveName`]/[`sand_commands::ScoreHolder`] for
//!    callers that don't need `Timer`'s countdown ergonomics.
//! 3. **Raw escape hatch** — the plain (infallible) methods (e.g.
//!    [`Timer::start`], [`Timer::active`]) accept any `impl Display`/`&str`
//!    and interpolate it into command text without validation. They remain
//!    available for compatibility and for advanced/modded selector syntax
//!    Sand cannot yet type-check.
//!
//! Every `try_*` method delegates to its raw counterpart once validation
//! succeeds, so the typed and compatibility paths render byte-identically.

pub use sand_components::Ticks;

use crate::state::flag::{validate_holder, validate_single_holder};
use sand_commands::{CommandResult, ScoreHolder};

// ── Timer ─────────────────────────────────────────────────────────────────────

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::Timer",
    aliases = ["sand::prelude::Timer"],
    module = "sand::state",
    summary = "A scoreboard-backed countdown timer. A `Timer` counts down from a starting value to zero. It does not generate conditions; use [`Cooldown`](super::cooldown::Cooldown) when you need ready/active conditions.",
    context = "A scoreboard-backed countdown timer. A `Timer` counts down from a starting value to zero. It does not generate conditions; use [`Cooldown`](super::cooldown::Cooldown) when you need ready/active conditions. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::Timer;",
)]
/// A scoreboard-backed countdown timer.
///
/// A `Timer` counts down from a starting value to zero. It does not generate
/// conditions; use [`Cooldown`](super::cooldown::Cooldown) when you need
/// ready/active conditions.
///
/// ```rust,ignore
/// use sand_core::state::{Timer, Ticks};
///
/// static BLINK: Timer = Timer::new("blink_cd", Ticks::seconds(5));
///
/// let cmds = vec![
///     BLINK.define(),
///     BLINK.start("@s"),
///     BLINK.tick_all_players(),
/// ];
/// ```
pub struct Timer {
    name: &'static str,
    duration: Ticks,
}

impl Timer {
    /// Create a new timer with the given objective name and duration.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::new",
        aliases = ["sand::prelude::Timer::new"],
        module = "sand::state",
        kind = "method",
        summary = "Create a new timer with the given objective name and duration.",
        context = "Create a new timer with the given objective name and duration. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(name = "`name` is used when creating a new timer with the given objective name and duration.", duration = "`duration` provides the Minecraft tick duration used to create a new timer with the given objective name and duration."),
        returns = "A `Timer` representing a new timer with the given objective name and duration.",
        example = "use sand::prelude::*;\n\nfn demonstrate(name: & 'static str, duration: sand::state::Ticks)  {\n    let timer = sand::state::Timer::new(name, duration);\n}",
    )]
    pub const fn new(name: &'static str, duration: Ticks) -> Self {
        Self { name, duration }
    }

    /// Return the actual scoreboard objective name.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::objective_name",
        aliases = ["sand::prelude::Timer::objective_name"],
        module = "sand::state",
        kind = "method",
        summary = "Return the actual scoreboard objective name.",
        context = "Return the actual scoreboard objective name. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Return the actual scoreboard objective name.",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer)  {\n    let objective_name = timer_value.objective_name();\n}",
    )]
    pub fn objective_name(&self) -> String {
        super::score::objective_name(self.name)
    }

    /// `scoreboard objectives add <obj> dummy`
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::define",
        aliases = ["sand::prelude::Timer::define"],
        module = "sand::state",
        kind = "method",
        summary = "`scoreboard objectives add <obj> dummy`",
        context = "`scoreboard objectives add <obj> dummy` This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to emit the documented `scoreboard objectives add <obj> dummy` form.",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer)  {\n    let define = timer_value.define();\n}",
    )]
    pub fn define(&self) -> String {
        format!("scoreboard objectives add {} dummy", self.objective_name())
    }

    /// Set the timer to the configured duration for `selector`.
    ///
    /// Raw compatibility escape hatch: `selector` is an unvalidated string,
    /// interpolated directly into generated commands. Prefer
    /// [`Timer::try_start`] in new code — see
    /// [#146](https://github.com/ThatOneToast/sand/issues/146).
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::start",
        aliases = ["sand::prelude::Timer::start"],
        module = "sand::state",
        kind = "method",
        summary = "Set the timer to the configured duration for `selector`.",
        context = "Set the timer to the configured duration for `selector`. Raw compatibility escape hatch: `selector` is an unvalidated string, interpolated directly into generated commands. Prefer [`Timer::try_start`] in new code — see [#146](https://github.com/ThatOneToast/sand/issues/146).",
        minecraft = "Raw compatibility escape hatch: `selector` is an unvalidated string, interpolated directly into generated commands. Prefer [`Timer::try_start`] in new code — see [#146](https://github.com/ThatOneToast/sand/issues/146).",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "Set the timer to the configured duration for `selector`."),
        returns = "The string value produced to set the timer to the configured duration for `selector`.",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, selector: impl std::fmt::Display)  {\n    let start = timer_value.start(selector);\n}",
    )]
    pub fn start(&self, selector: impl std::fmt::Display) -> String {
        format!(
            "scoreboard players set {} {} {}",
            selector,
            self.objective_name(),
            self.duration.get()
        )
    }

    /// Validated counterpart to [`Timer::start`] — takes a typed
    /// [`sand_commands::ScoreHolder`] and validates it before generating the
    /// `scoreboard players set` command, instead of interpolating an
    /// unvalidated `Display` value.
    ///
    /// `scoreboard players set` accepts multiple targets, so multi-entity
    /// selectors and the `*` wildcard are permitted here (unlike
    /// [`Timer::try_tick`], which builds a score *condition*).
    ///
    /// ```
    /// use sand_core::state::{Ticks, Timer};
    /// use sand_commands::ScoreHolder;
    ///
    /// static BLINK: Timer = Timer::new("blink_cd", Ticks::new(100));
    ///
    /// assert_eq!(
    ///     BLINK.try_start(ScoreHolder::self_()).unwrap(),
    ///     "scoreboard players set @s blink_cd 100"
    /// );
    /// assert!(BLINK.try_start(ScoreHolder::fake("bad holder")).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::try_start",
        aliases = ["sand::prelude::Timer::try_start"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Timer::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value.",
        context = "Validated counterpart to [`Timer::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value. `scoreboard players set` accepts multiple targets, so multi-entity selectors and the `*` wildcard are permitted here (unlike [`Timer::try_tick`], which builds a score *condition*).",
        minecraft = "`scoreboard players set` accepts multiple targets, so multi-entity selectors and the `*` wildcard are permitted here (unlike [`Timer::try_tick`], which builds a score *condition*).",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` sets the holder for validated counterpart to [`Timer::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value."),
        returns = "On success, the value produced to use validated counterpart to [`Timer::start`] — takes a typed [`sand::command::ScoreHolder`] and validates it before generating the `scoreboard players set` command, instead of interpolating an unvalidated `Display` value; otherwise, the documented validation or export diagnostic.",
        example = "use {sand::state::Ticks, sand::state::Timer};\nuse sand::command::ScoreHolder;\nstatic BLINK: Timer = Timer::new(\"blink_cd\", Ticks::new(100));\nassert_eq!(\nBLINK.try_start(ScoreHolder::self_()).unwrap(),\n\"scoreboard players set @s blink_cd 100\"\n);\nassert!(BLINK.try_start(ScoreHolder::fake(\"bad holder\")).is_err());",
    )]
    pub fn try_start(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_holder(&holder, "Timer::try_start")?;
        Ok(self.start(holder.to_string()))
    }

    /// Decrement the timer by 1 tick for one score holder (only if > 0).
    ///
    /// Use [`tick_all_players`](Self::tick_all_players) instead of passing a
    /// multi-player selector such as `@a` here.
    ///
    /// Raw compatibility escape hatch — prefer [`Timer::try_tick`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::tick",
        aliases = ["sand::prelude::Timer::tick"],
        module = "sand::state",
        kind = "method",
        summary = "Decrement the timer by 1 tick for one score holder (only if > 0).",
        context = "Decrement the timer by 1 tick for one score holder (only if > 0). Use [`tick_all_players`](Self::tick_all_players) instead of passing a multi-player selector such as `@a` here. Raw compatibility escape hatch — prefer [`Timer::try_tick`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Use [`tick_all_players`](Self::tick_all_players) instead of passing a multi-player selector such as `@a` here."],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to decrement the timer by 1 tick for one score holder (only if > 0)."),
        returns = "The string value produced to decrement the timer by 1 tick for one score holder (only if > 0).",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, selector: impl std::fmt::Display)  {\n    let tick = timer_value.tick(selector);\n}",
    )]
    pub fn tick(&self, selector: impl std::fmt::Display) -> String {
        let selector = selector.to_string();
        let obj = self.objective_name();
        format!(
            "execute if score {selector} {obj} matches 1.. run scoreboard players remove {selector} {obj} 1"
        )
    }

    /// Validated counterpart to [`Timer::tick`] — takes a typed
    /// [`sand_commands::ScoreHolder`].
    ///
    /// The generated command is guarded by `execute if score <holder> …`,
    /// which requires exactly one score holder, so the `*` wildcard and
    /// multi-entity selectors are rejected via
    /// [`sand_commands::ScoreHolder::validate_single`] — use
    /// [`Timer::tick_all_players`] for the per-player `@a` form.
    ///
    /// ```
    /// use sand_core::state::{Ticks, Timer};
    /// use sand_commands::ScoreHolder;
    /// use sand_commands::selector::Selector;
    ///
    /// static BLINK: Timer = Timer::new("blink_cd", Ticks::new(100));
    ///
    /// assert_eq!(BLINK.try_tick(ScoreHolder::self_()).unwrap(), BLINK.tick("@s"));
    /// assert!(BLINK.try_tick(ScoreHolder::entity(Selector::all_players())).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::try_tick",
        aliases = ["sand::prelude::Timer::try_tick"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Timer::tick`] — takes a typed [`sand::command::ScoreHolder`].",
        context = "Validated counterpart to [`Timer::tick`] — takes a typed [`sand::command::ScoreHolder`]. The generated command is guarded by `execute if score <holder> …`, which requires exactly one score holder, so the `*` wildcard and multi-entity selectors are rejected via [`sand::command::ScoreHolder::validate_single`] — use [`Timer::tick_all_players`] for the per-player `@a` form.",
        minecraft = "The generated command is guarded by `execute if score <holder> …`, which requires exactly one score holder, so the `*` wildcard and multi-entity selectors are rejected via [`sand::command::ScoreHolder::validate_single`] — use [`Timer::tick_all_players`] for the per-player `@a` form.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` sets the holder for validated counterpart to [`Timer::tick`] — takes a typed [`sand::command::ScoreHolder`]."),
        returns = "On success, the value produced to use validated counterpart to [`Timer::tick`] — takes a typed [`sand::command::ScoreHolder`]; otherwise, the documented validation or export diagnostic.",
        example = "use {sand::state::Ticks, sand::state::Timer};\nuse sand::command::ScoreHolder;\nuse sand::command::Selector;\nstatic BLINK: Timer = Timer::new(\"blink_cd\", Ticks::new(100));\nassert_eq!(BLINK.try_tick(ScoreHolder::self_()).unwrap(), BLINK.tick(\"@s\"));\nassert!(BLINK.try_tick(ScoreHolder::entity(Selector::all_players())).is_err());",
    )]
    pub fn try_tick(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_single_holder(&holder, "Timer::try_tick")?;
        Ok(self.tick(holder.to_string()))
    }

    /// Decrement this timer independently for every online player.
    ///
    /// Takes no score holder — the `@a`/`@s` pair is generated by Sand and is
    /// always valid, so there is no `try_*` counterpart.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::tick_all_players",
        aliases = ["sand::prelude::Timer::tick_all_players"],
        module = "sand::state",
        kind = "method",
        summary = "Decrement this timer independently for every online player.",
        context = "Decrement this timer independently for every online player. Takes no score holder — the `@a`/`@s` pair is generated by Sand and is always valid, so there is no `try_*` counterpart.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to decrement this timer independently for every online player.",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer)  {\n    let tick_all_players = timer_value.tick_all_players();\n}",
    )]
    pub fn tick_all_players(&self) -> String {
        let obj = self.objective_name();
        format!(
            "execute as @a if score @s {obj} matches 1.. run scoreboard players remove @s {obj} 1"
        )
    }

    /// Reset the timer to zero for `selector`.
    ///
    /// Raw compatibility escape hatch — prefer [`Timer::try_reset`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::reset",
        aliases = ["sand::prelude::Timer::reset"],
        module = "sand::state",
        kind = "method",
        summary = "Reset the timer to zero for `selector`. Raw compatibility escape hatch — prefer [`Timer::try_reset`].",
        context = "Reset the timer to zero for `selector`. Raw compatibility escape hatch — prefer [`Timer::try_reset`]. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "Reset the timer to zero for `selector`."),
        returns = "The string value produced to reset the timer to zero for `selector`. Raw compatibility escape hatch — prefer [`Timer::try_reset`].",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, selector: impl std::fmt::Display)  {\n    let reset = timer_value.reset(selector);\n}",
    )]
    pub fn reset(&self, selector: impl std::fmt::Display) -> String {
        format!(
            "scoreboard players set {} {} 0",
            selector,
            self.objective_name()
        )
    }

    /// Validated counterpart to [`Timer::reset`] — see [`Timer::try_start`].
    /// Multi-target holders are permitted (`scoreboard players set` accepts
    /// multiple targets).
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::try_reset",
        aliases = ["sand::prelude::Timer::try_reset"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Timer::reset`] — see [`Timer::try_start`]. Multi-target holders are permitted (`scoreboard players set` accepts multiple targets).",
        context = "Validated counterpart to [`Timer::reset`] — see [`Timer::try_start`]. Multi-target holders are permitted (`scoreboard players set` accepts multiple targets). This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` sets the holder for validated counterpart to [`Timer::reset`] — see [`Timer::try_start`]. Multi-target holders are permitted (`scoreboard players set` accepts multiple targets)."),
        returns = "On success, the value produced to use validated counterpart to [`Timer::reset`] — see [`Timer::try_start`]. Multi-target holders are permitted (`scoreboard players set` accepts multiple targets); otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_reset = timer_value.try_reset(holder);\n}",
    )]
    pub fn try_reset(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_holder(&holder, "Timer::try_reset")?;
        Ok(self.reset(holder.to_string()))
    }

    /// Condition: timer has expired (score == 0).
    ///
    /// Use this to check if the timer has counted down to zero.
    ///
    /// Raw compatibility escape hatch — prefer [`Timer::try_expired`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::expired",
        aliases = ["sand::prelude::Timer::expired"],
        module = "sand::state",
        kind = "method",
        summary = "Condition: timer has expired (score == 0). Use this to check if the timer has counted down to zero.",
        context = "Condition: timer has expired (score == 0). Use this to check if the timer has counted down to zero. Raw compatibility escape hatch — prefer [`Timer::try_expired`].",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Use this to check if the timer has counted down to zero."],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to condition timer has expired (score == 0). Use this to check if the timer has counted down to zero."),
        returns = "The `sand :: condition :: Condition` value produced to condition timer has expired (score == 0). Use this to check if the timer has counted down to zero.",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, selector: & str)  {\n    let expired = timer_value.expired(selector);\n}",
    )]
    pub fn expired(&self, selector: &str) -> crate::condition::Condition {
        crate::condition::Condition::score(
            selector.to_string(),
            self.objective_name(),
            crate::condition::ScoreRange::Eq(0),
        )
    }

    /// Validated counterpart to [`Timer::expired`] — takes a typed
    /// [`sand_commands::ScoreHolder`], which must resolve to exactly one score
    /// holder because the result lowers to `execute if score <holder> …`.
    ///
    /// ```
    /// use sand_core::execute_when::when;
    /// use sand_core::state::{Ticks, Timer};
    /// use sand_commands::ScoreHolder;
    ///
    /// static BLINK: Timer = Timer::new("blink_cd", Ticks::new(100));
    ///
    /// let cond = BLINK.try_expired(ScoreHolder::self_()).unwrap();
    /// assert_eq!(
    ///     when(cond).then_one("say ok"),
    ///     vec!["execute if score @s blink_cd matches 0 run say ok"]
    /// );
    /// assert!(BLINK.try_expired(ScoreHolder::wildcard()).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::try_expired",
        aliases = ["sand::prelude::Timer::try_expired"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Timer::expired`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`.",
        context = "Validated counterpart to [`Timer::expired`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` sets the holder for validated counterpart to [`Timer::expired`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`."),
        returns = "On success, the value produced to use validated counterpart to [`Timer::expired`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the result lowers to `execute if score <holder> …`; otherwise, the documented validation or export diagnostic.",
        example = "use sand::execute_when::when;\nuse {sand::state::Ticks, sand::state::Timer};\nuse sand::command::ScoreHolder;\nstatic BLINK: Timer = Timer::new(\"blink_cd\", Ticks::new(100));\nlet cond = BLINK.try_expired(ScoreHolder::self_()).unwrap();\nassert_eq!(\nwhen(cond).then_one(\"say ok\"),\nvec![\"execute if score @s blink_cd matches 0 run say ok\"]\n);\nassert!(BLINK.try_expired(ScoreHolder::wildcard()).is_err());",
    )]
    pub fn try_expired(
        &self,
        holder: impl Into<ScoreHolder>,
    ) -> CommandResult<crate::condition::Condition> {
        let holder = holder.into();
        validate_single_holder(&holder, "Timer::try_expired")?;
        Ok(self.expired(&holder.to_string()))
    }

    /// Condition: timer is still running (score >= 1).
    ///
    /// Raw compatibility escape hatch — prefer [`Timer::try_active`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::active",
        aliases = ["sand::prelude::Timer::active"],
        module = "sand::state",
        kind = "method",
        summary = "Condition: timer is still running (score >= 1). Raw compatibility escape hatch — prefer [`Timer::try_active`].",
        context = "Condition: timer is still running (score >= 1). Raw compatibility escape hatch — prefer [`Timer::try_active`]. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to condition timer is still running (score >= 1). Raw compatibility escape hatch — prefer [`Timer::try_active`]."),
        returns = "The `sand :: condition :: Condition` value produced to condition timer is still running (score >= 1). Raw compatibility escape hatch — prefer [`Timer::try_active`].",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, selector: & str)  {\n    let active = timer_value.active(selector);\n}",
    )]
    pub fn active(&self, selector: &str) -> crate::condition::Condition {
        crate::condition::Condition::score(
            selector.to_string(),
            self.objective_name(),
            crate::condition::ScoreRange::Gte(1),
        )
    }

    /// Validated counterpart to [`Timer::active`] — see
    /// [`Timer::try_expired`]; the holder must resolve to exactly one score
    /// holder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::try_active",
        aliases = ["sand::prelude::Timer::try_active"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Timer::active`] — see [`Timer::try_expired`]; the holder must resolve to exactly one score holder.",
        context = "Validated counterpart to [`Timer::active`] — see [`Timer::try_expired`]; the holder must resolve to exactly one score holder. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` sets the holder for validated counterpart to [`Timer::active`] — see [`Timer::try_expired`]; the holder must resolve to exactly one score holder."),
        returns = "On success, the value produced to use validated counterpart to [`Timer::active`] — see [`Timer::try_expired`]; the holder must resolve to exactly one score holder; otherwise, the documented validation or export diagnostic.",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, holder: impl Into < sand::command::ScoreHolder >)  {\n    let try_active = timer_value.try_active(holder);\n}",
    )]
    pub fn try_active(
        &self,
        holder: impl Into<ScoreHolder>,
    ) -> CommandResult<crate::condition::Condition> {
        let holder = holder.into();
        validate_single_holder(&holder, "Timer::try_active")?;
        Ok(self.active(&holder.to_string()))
    }

    /// Guard clause: return early if the timer is still running (score >= 1).
    ///
    /// Raw compatibility escape hatch — prefer [`Timer::try_guard_active`].
    ///
    /// Produces: `execute if score <selector> <obj> matches 1.. run return 0`
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::guard_active",
        aliases = ["sand::prelude::Timer::guard_active"],
        module = "sand::state",
        kind = "method",
        summary = "Guard clause: return early if the timer is still running (score >= 1).",
        context = "Guard clause: return early if the timer is still running (score >= 1). Raw compatibility escape hatch — prefer [`Timer::try_guard_active`]. Produces: `execute if score <selector> <obj> matches 1.. run return 0`",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to guard clause: return early if the timer is still running (score >= 1)."),
        returns = "The string value produced to guard clause: return early if the timer is still running (score >= 1).",
        example = "use std::fmt;\nuse sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer, selector: impl std::fmt::Display)  {\n    let guard_active = timer_value.guard_active(selector);\n}",
    )]
    pub fn guard_active(&self, selector: impl std::fmt::Display) -> String {
        format!(
            "execute if score {} {} matches 1.. run return 0",
            selector,
            self.objective_name()
        )
    }

    /// Validated counterpart to [`Timer::guard_active`] — takes a typed
    /// [`sand_commands::ScoreHolder`], which must resolve to exactly one score
    /// holder because the guard lowers to `execute if score <holder> …`.
    ///
    /// ```
    /// use sand_core::state::{Ticks, Timer};
    /// use sand_commands::ScoreHolder;
    ///
    /// static BLINK: Timer = Timer::new("blink_cd", Ticks::new(100));
    ///
    /// assert_eq!(
    ///     BLINK.try_guard_active(ScoreHolder::self_()).unwrap(),
    ///     "execute if score @s blink_cd matches 1.. run return 0"
    /// );
    /// assert!(BLINK.try_guard_active(ScoreHolder::wildcard()).is_err());
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::try_guard_active",
        aliases = ["sand::prelude::Timer::try_guard_active"],
        module = "sand::state",
        kind = "method",
        summary = "Validated counterpart to [`Timer::guard_active`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`.",
        context = "Validated counterpart to [`Timer::guard_active`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(holder = "`holder` sets the holder for validated counterpart to [`Timer::guard_active`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`."),
        returns = "On success, the value produced to use validated counterpart to [`Timer::guard_active`] — takes a typed [`sand::command::ScoreHolder`], which must resolve to exactly one score holder because the guard lowers to `execute if score <holder> …`; otherwise, the documented validation or export diagnostic.",
        example = "use {sand::state::Ticks, sand::state::Timer};\nuse sand::command::ScoreHolder;\nstatic BLINK: Timer = Timer::new(\"blink_cd\", Ticks::new(100));\nassert_eq!(\nBLINK.try_guard_active(ScoreHolder::self_()).unwrap(),\n\"execute if score @s blink_cd matches 1.. run return 0\"\n);\nassert!(BLINK.try_guard_active(ScoreHolder::wildcard()).is_err());",
    )]
    pub fn try_guard_active(&self, holder: impl Into<ScoreHolder>) -> CommandResult<String> {
        let holder = holder.into();
        validate_single_holder(&holder, "Timer::try_guard_active")?;
        Ok(self.guard_active(holder.to_string()))
    }

    /// Return the configured duration.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Timer::duration",
        aliases = ["sand::prelude::Timer::duration"],
        module = "sand::state",
        kind = "method",
        summary = "Return the configured duration.",
        context = "Return the configured duration. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Return the configured duration.",
        example = "use sand::prelude::*;\n\nfn demonstrate(timer_value: &sand::state::Timer)  {\n    let duration = timer_value.duration();\n}",
    )]
    pub fn duration(&self) -> Ticks {
        self.duration
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ticks_new() {
        assert_eq!(Ticks::new(60).get(), 60);
    }

    #[test]
    fn ticks_seconds() {
        assert_eq!(Ticks::seconds(3).get(), 60);
    }

    #[test]
    fn ticks_minutes() {
        assert_eq!(Ticks::minutes(1).get(), 1200);
    }

    #[test]
    fn ticks_as_seconds() {
        assert_eq!(Ticks::new(60).as_seconds(), 3);
        assert_eq!(Ticks::new(25).as_seconds(), 1); // floor division
    }

    static BLINK: Timer = Timer::new("blink_cd", Ticks::new(100));

    #[test]
    fn timer_define() {
        assert_eq!(BLINK.define(), "scoreboard objectives add blink_cd dummy");
    }

    #[test]
    fn timer_start() {
        assert_eq!(BLINK.start("@s"), "scoreboard players set @s blink_cd 100");
    }

    #[test]
    fn timer_tick() {
        let cmd = BLINK.tick("@s");
        assert!(cmd.contains("matches 1.."), "got: {cmd}");
        assert!(cmd.contains("remove @s blink_cd 1"), "got: {cmd}");
    }

    #[test]
    fn timer_tick_all_players_is_per_player_safe() {
        let command = BLINK.tick_all_players();
        assert_eq!(command, BLINK.tick_all_players());
        assert_eq!(
            command,
            "execute as @a if score @s blink_cd matches 1.. run scoreboard players remove @s blink_cd 1"
        );
        assert!(!command.contains("if score @a"));
        assert!(!command.contains("remove @a"));
        assert_eq!(
            BLINK.tick("@s"),
            "execute if score @s blink_cd matches 1.. run scoreboard players remove @s blink_cd 1"
        );
    }

    #[test]
    fn timer_reset() {
        assert_eq!(BLINK.reset("@s"), "scoreboard players set @s blink_cd 0");
    }

    #[test]
    fn timer_expired_condition() {
        use crate::condition::{ConditionKind, ScoreRange};
        let cond = BLINK.expired("@s");
        match cond.kind() {
            ConditionKind::Score {
                selector,
                objective,
                range: ScoreRange::Eq(0),
            } => {
                assert_eq!(selector, "@s");
                assert_eq!(objective, "blink_cd");
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn timer_active_condition() {
        use crate::condition::{ConditionKind, ScoreRange};
        let cond = BLINK.active("@s");
        assert!(matches!(
            cond.kind(),
            ConditionKind::Score {
                range: ScoreRange::Gte(1),
                ..
            }
        ));
    }

    #[test]
    fn timer_guard_active() {
        let cmd = BLINK.guard_active("@s");
        assert_eq!(cmd, "execute if score @s blink_cd matches 1.. run return 0");
    }
}
