//! Enum-backed typed gameplay states backed by scoreboard objectives.
//!
//! Provides [`GameState<S>`] — a scoreboard-backed variable where valid values
//! are the variants of a user-defined enum implementing [`TypedGameState`].
//!
//! # Example
//!
//! ```rust,ignore
//! use sand_core::state::{GameState, TypedGameState};
//!
//! #[derive(Clone, Copy, PartialEq, Eq)]
//! pub enum BossPhase { Idle = 0, Fighting = 1, Enraged = 2 }
//!
//! impl TypedGameState for BossPhase {
//!     fn to_score(self) -> i32 { self as i32 }
//!     fn from_score(n: i32) -> Option<Self> {
//!         match n {
//!             0 => Some(Self::Idle),
//!             1 => Some(Self::Fighting),
//!             2 => Some(Self::Enraged),
//!             _ => None,
//!         }
//!     }
//! }
//!
//! static PHASE: GameState<BossPhase> = GameState::with_default_score("boss_phase", 0);
//!
//! // In your load function:
//! let load_cmd = PHASE.define(); // "scoreboard objectives add boss_phase dummy"
//!
//! // Set state:
//! let set_cmd = PHASE.of("@s").set(BossPhase::Enraged);
//! // "scoreboard players set @s boss_phase 2"
//!
//! // Check state:
//! let cond = PHASE.of("@s").is(BossPhase::Fighting);
//! // Condition: if score @s boss_phase matches 1
//!
//! // Reset to the configured default:
//! let reset_cmd = PHASE.of("@s").reset();
//! // "scoreboard players set @s boss_phase 0"
//!
//! // Negative check:
//! let not_cond = PHASE.of("@s").is_not(BossPhase::Idle);
//! // Condition: unless score @s boss_phase matches 0
//! ```

use std::marker::PhantomData;

use crate::condition::{Condition, ScoreRange};

use super::score::objective_name;

// ── TypedGameState ─────────────────────────────────────────────────────────────

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::TypedGameState",
    aliases = ["sand::prelude::TypedGameState"],
    module = "sand::state",
    summary = "Implement this trait on an enum to use it as a typed gameplay state.",
    context = "Implement this trait on an enum to use it as a typed gameplay state. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::TypedGameState;",
)]
/// Implement this trait on an enum to use it as a typed gameplay state.
///
/// # Example
/// ```rust,ignore
/// #[derive(Clone, Copy, PartialEq, Eq)]
/// pub enum BossPhase { Idle = 0, Fighting = 1, Enraged = 2 }
///
/// impl TypedGameState for BossPhase {
///     fn to_score(self) -> i32 { self as i32 }
///     fn from_score(n: i32) -> Option<Self> {
///         match n { 0 => Some(Self::Idle), 1 => Some(Self::Fighting), 2 => Some(Self::Enraged), _ => None }
///     }
/// }
/// ```
pub trait TypedGameState: Copy + Eq + 'static {
    /// Map this variant to its scoreboard integer representation.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::TypedGameState::to_score",
        aliases = ["sand::prelude::TypedGameState::to_score"],
        module = "sand::state",
        summary = "Map this variant to its scoreboard integer representation.",
        context = "Map this variant to its scoreboard integer representation. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `i32` value produced to map this variant to its scoreboard integer representation.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::TypedGameState>(typed_game_state_value: T)  {\n    let to_score = typed_game_state_value.to_score();\n}",
    )]
    fn to_score(self) -> i32;

    /// Attempt to construct this variant from a scoreboard integer.
    ///
    /// Returns `None` if `n` does not correspond to any valid variant.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::TypedGameState::from_score",
        aliases = ["sand::prelude::TypedGameState::from_score"],
        module = "sand::state",
        summary = "Attempt to construct this variant from a scoreboard integer.",
        context = "Attempt to construct this variant from a scoreboard integer. Returns `None` if `n` does not correspond to any valid variant.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(n = "Returns `None` if `n` does not correspond to any valid variant."),
        returns = "Returns `None` if `n` does not correspond to any valid variant.",
        example = "use sand::prelude::*;\n\nfn demonstrate<T: sand::state::TypedGameState>(n: i32)  {\n    let from_score = <T as sand::state::TypedGameState>::from_score(n);\n}",
    )]
    fn from_score(n: i32) -> Option<Self>;
}

// ── GameState ─────────────────────────────────────────────────────────────────

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::GameState",
    aliases = ["sand::prelude::GameState"],
    module = "sand::state",
    summary = "A scoreboard-backed typed gameplay state variable.",
    context = "A scoreboard-backed typed gameplay state variable. Declare once as a `static` and use throughout your datapack: `GameState<S>` stores only a `&'static str` and a `PhantomData<fn() -> S>`. The function-pointer phantom keeps auto-trait derivation sound — `fn() -> S` is always `Send + Sync` regardless of `S`, which is correct because the struct does not actually store or move a value of type `S`.",
    minecraft = "Declare once as a `static` and use throughout your datapack:",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::GameState;",
)]
/// A scoreboard-backed typed gameplay state variable.
///
/// Declare once as a `static` and use throughout your datapack:
///
/// ```rust,ignore
/// static PHASE: GameState<BossPhase> = GameState::new("boss_phase");
/// ```
///
/// # Thread safety
///
/// `GameState<S>` stores only a `&'static str` and a `PhantomData<fn() -> S>`.
/// The function-pointer phantom keeps auto-trait derivation sound — `fn() -> S`
/// is always `Send + Sync` regardless of `S`, which is correct because the
/// struct does not actually store or move a value of type `S`.
pub struct GameState<S: TypedGameState> {
    name: &'static str,
    default_score: Option<i32>,
    _marker: PhantomData<fn() -> S>,
}

impl<S: TypedGameState> GameState<S> {
    /// Declare a new typed state variable with the given objective name.
    ///
    /// Names longer than 16 characters are automatically hashed to a stable
    /// 16-character objective name (see [`GameState::objective_name`]).
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameState::new",
        aliases = ["sand::prelude::GameState::new"],
        module = "sand::state",
        kind = "method",
        summary = "Declare a new typed state variable with the given objective name.",
        context = "Declare a new typed state variable with the given objective name. Names longer than 16 characters are automatically hashed to a stable 16-character objective name (see [`GameState::objective_name`]).",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(name = "`name` provides the author-visible text value used to declare a new typed state variable with the given objective name."),
        returns = "A newly constructed `GameState` configured to declare a new typed state variable with the given objective name.",
        example = "use sand::prelude::*;\n\nfn demonstrate<S : sand::state::TypedGameState + 'static>(name: & 'static str)  {\n    let game_state = sand::state::GameState ::< S >::new(name);\n}",
    )]
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            default_score: None,
            _marker: PhantomData,
        }
    }

    /// Declare a new typed state variable with a reset/default score.
    ///
    /// [`GameStateRef::reset`] restores this score instead of clearing the
    /// scoreboard entry. This keeps user-facing code free of magic scoreboard
    /// integers at call sites while making the stored default explicit at the
    /// declaration.
    ///
    /// ```rust,ignore
    /// static PHASE: GameState<BossPhase> =
    ///     GameState::with_default_score("boss_phase", 0);
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameState::with_default_score",
        aliases = ["sand::prelude::GameState::with_default_score"],
        module = "sand::state",
        kind = "method",
        summary = "Declare a new typed state variable with a reset/default score.",
        context = "Declare a new typed state variable with a reset/default score. [`GameStateRef::reset`] restores this score instead of clearing the scoreboard entry. This keeps user-facing code free of magic scoreboard integers at call sites while making the stored default explicit at the declaration.",
        minecraft = "[`GameStateRef::reset`] restores this score instead of clearing the scoreboard entry. This keeps user-facing code free of magic scoreboard integers at call sites while making the stored default explicit at the declaration.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(name = "`name` provides the author-visible text value used to declare a new typed state variable with a reset/default score.", default_score = "`default_score` supplies the default score value used to declare a new typed state variable with a reset/default score."),
        returns = "A newly constructed `GameState` configured to declare a new typed state variable with a reset/default score.",
        example = "static PHASE: GameState<BossPhase> =\nGameState::with_default_score(\"boss_phase\", 0);",
    )]
    pub const fn with_default_score(name: &'static str, default_score: i32) -> Self {
        Self {
            name,
            default_score: Some(default_score),
            _marker: PhantomData,
        }
    }

    /// Return the actual scoreboard objective name used in commands.
    ///
    /// This is either `name` directly (≤16 chars) or a stable FNV-1a hash (>16 chars).
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameState::objective_name",
        aliases = ["sand::prelude::GameState::objective_name"],
        module = "sand::state",
        kind = "method",
        summary = "Return the actual scoreboard objective name used in commands.",
        context = "Return the actual scoreboard objective name used in commands. This is either `name` directly (≤16 chars) or a stable FNV-1a hash (>16 chars).",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Return the actual scoreboard objective name used in commands.",
        example = "use sand::prelude::*;\n\nfn demonstrate<S : sand::state::TypedGameState + 'static>(game_state_value: &sand::state::GameState < S >)  {\n    let command = game_state_value.objective_name();\n}",
    )]
    pub fn objective_name(&self) -> String {
        objective_name(self.name)
    }

    /// Return the configured default score, if this state has one.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameState::default_score",
        aliases = ["sand::prelude::GameState::default_score"],
        module = "sand::state",
        kind = "method",
        summary = "Return the configured default score, if this state has one.",
        context = "Return the configured default score, if this state has one. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Return the configured default score, if this state has one.",
        example = "use sand::prelude::*;\n\nfn demonstrate<S : sand::state::TypedGameState + 'static>(game_state_value: &sand::state::GameState < S >)  {\n    let default_score = game_state_value.default_score();\n}",
    )]
    pub fn default_score(&self) -> Option<i32> {
        self.default_score
    }

    /// `scoreboard objectives add <obj> dummy` — register the objective.
    ///
    /// Call this in your `load` function.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameState::define",
        aliases = ["sand::prelude::GameState::define"],
        module = "sand::state",
        kind = "method",
        summary = "`scoreboard objectives add <obj> dummy` — register the objective.",
        context = "`scoreboard objectives add <obj> dummy` — register the objective. Call this in your `load` function.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Call this in your `load` function."],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to emit the documented `scoreboard objectives add <obj> dummy` — register the objective form.",
        example = "use sand::prelude::*;\n\nfn demonstrate<S : sand::state::TypedGameState + 'static>(game_state_value: &sand::state::GameState < S >)  {\n    let define = game_state_value.define();\n}",
    )]
    pub fn define(&self) -> String {
        format!("scoreboard objectives add {} dummy", self.objective_name())
    }

    /// Bind this state to a selector to produce a typed accessor.
    ///
    /// ```rust,ignore
    /// let ref_ = PHASE.of("@s");
    /// let cmd = ref_.set(BossPhase::Enraged);
    /// ```
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameState::of",
        aliases = ["sand::prelude::GameState::of"],
        module = "sand::state",
        kind = "method",
        summary = "Bind this state to a selector to produce a typed accessor.",
        context = "Bind this state to a selector to produce a typed accessor. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(selector = "`selector` provides the Minecraft target selection used to bind this state to a selector to produce a typed accessor."),
        returns = "The `GameStateRef < 'a , S >` value produced to bind this state to a selector to produce a typed accessor.",
        example = "let ref_ = PHASE.of(\"@s\");\nlet cmd = ref_.set(BossPhase::Enraged);",
    )]
    pub fn of<'a>(&'a self, selector: &str) -> GameStateRef<'a, S> {
        GameStateRef {
            state: self,
            selector: selector.to_string(),
        }
    }
}

// ── GameStateRef ──────────────────────────────────────────────────────────────

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::GameStateRef",
    aliases = ["sand::prelude::GameStateRef"],
    module = "sand::state",
    summary = "A [`GameState`] bound to a selector — provides typed get/set/check helpers.",
    context = "A [`GameState`] bound to a selector — provides typed get/set/check helpers. Produced by [`GameState::of`].",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::GameStateRef;",
)]
/// A [`GameState`] bound to a selector — provides typed get/set/check helpers.
///
/// Produced by [`GameState::of`].
pub struct GameStateRef<'a, S: TypedGameState> {
    state: &'a GameState<S>,
    selector: String,
}

impl<'a, S: TypedGameState> GameStateRef<'a, S> {
    /// Returns the entity selector whose scoreboard value stores this game state.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameStateRef::selector",
        aliases = ["sand::prelude::GameStateRef::selector"],
        module = "sand::state",
        kind = "method",
        summary = "Returns the entity selector whose scoreboard value stores this game state.",
        context = "Returns the entity selector whose scoreboard value stores this game state. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Returns the entity selector whose scoreboard value stores this game state.",
        example = "use sand::prelude::*;\n\nfn demonstrate<'a, S : sand::state::TypedGameState + 'static>(game_state_ref_value: &sand::state::GameStateRef < 'a , S >)  {\n    let selector = game_state_ref_value.selector();\n}",
    )]
    pub fn selector(&self) -> &str {
        &self.selector
    }

    /// Start a compact one-off typed transition.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameStateRef::transition",
        aliases = ["sand::prelude::GameStateRef::transition"],
        module = "sand::state",
        kind = "method",
        summary = "Start a compact one-off typed transition.",
        context = "Start a compact one-off typed transition. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The `sand :: state :: StateTransitionBuilder < 'a , S >` value produced to start a compact one-off typed transition.",
        example = "use sand::prelude::*;\n\nfn demonstrate<'a, S : sand::state::TypedGameState + 'static>(game_state_ref_value: sand::state::GameStateRef < 'a , S >)  {\n    let transition = game_state_ref_value.transition();\n}",
    )]
    pub fn transition(&'a self) -> crate::state::StateTransitionBuilder<'a, S> {
        crate::state::StateTransitionBuilder::new(self)
    }

    /// `scoreboard players set <sel> <obj> <variant.to_score()>`
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameStateRef::set",
        aliases = ["sand::prelude::GameStateRef::set"],
        module = "sand::state",
        kind = "method",
        summary = "`scoreboard players set <sel> <obj> <variant.to_score()>`",
        context = "`scoreboard players set <sel> <obj> <variant.to_score()>` This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(variant = "`variant` supplies the variant value used to emit the documented `scoreboard players set <sel> <obj> <variant.to_score()>` form."),
        returns = "The string value produced to emit the documented `scoreboard players set <sel> <obj> <variant.to_score()>` form.",
        example = "use sand::prelude::*;\n\nfn demonstrate<'a, S : sand::state::TypedGameState + 'static>(game_state_ref_value: &sand::state::GameStateRef < 'a , S >, variant: S)  {\n    let set = game_state_ref_value.set(variant);\n}",
    )]
    pub fn set(&self, variant: S) -> String {
        self.set_score(variant.to_score())
    }

    fn set_score(&self, score: i32) -> String {
        format!(
            "scoreboard players set {} {} {}",
            self.selector,
            self.state.objective_name(),
            score
        )
    }

    /// Reset this selector's state.
    ///
    /// For states declared with [`GameState::with_default_score`], this writes
    /// the configured default score. For states declared with [`GameState::new`],
    /// this clears the scoreboard entry with `scoreboard players reset`.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameStateRef::reset",
        aliases = ["sand::prelude::GameStateRef::reset"],
        module = "sand::state",
        kind = "method",
        summary = "Reset this selector's state. For states declared with [`GameState::with_default_score`], this writes the configured default score. For states declared with [`GameState::new`], this clears the scoreboard entry with `scoreboard players reset`.",
        context = "Reset this selector's state. For states declared with [`GameState::with_default_score`], this writes the configured default score. For states declared with [`GameState::new`], this clears the scoreboard entry with `scoreboard players reset`. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "For states declared with [`GameState::with_default_score`], this writes the configured default score. For states declared with [`GameState::new`], this clears the scoreboard entry with `scoreboard players reset`.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to reset this selector's state. For states declared with [`GameState::with_default_score`], this writes the configured default score. For states declared with [`GameState::new`], this clears the scoreboard entry with `scoreboard players reset`.",
        example = "use sand::prelude::*;\n\nfn demonstrate<'a, S : sand::state::TypedGameState + 'static>(game_state_ref_value: &sand::state::GameStateRef < 'a , S >)  {\n    let reset = game_state_ref_value.reset();\n}",
    )]
    pub fn reset(&self) -> String {
        match self.state.default_score() {
            Some(default_score) => self.set_score(default_score),
            None => self.clear(),
        }
    }

    /// Clear this selector's scoreboard entry regardless of any default state.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameStateRef::clear",
        aliases = ["sand::prelude::GameStateRef::clear"],
        module = "sand::state",
        kind = "method",
        summary = "Clear this selector's scoreboard entry regardless of any default state.",
        context = "Clear this selector's scoreboard entry regardless of any default state. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "The string value produced to clear this selector's scoreboard entry regardless of any default state.",
        example = "use sand::prelude::*;\n\nfn demonstrate<'a, S : sand::state::TypedGameState + 'static>(game_state_ref_value: &sand::state::GameStateRef < 'a , S >)  {\n    let clear = game_state_ref_value.clear();\n}",
    )]
    pub fn clear(&self) -> String {
        format!(
            "scoreboard players reset {} {}",
            self.selector,
            self.state.objective_name()
        )
    }

    /// Condition: state equals the given variant.
    ///
    /// Renders as `if score <sel> <obj> matches <variant.to_score()>`.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameStateRef::is",
        aliases = ["sand::prelude::GameStateRef::is"],
        module = "sand::state",
        kind = "method",
        summary = "Condition: state equals the given variant. Renders as `if score <sel> <obj> matches <variant.to_score()>`.",
        context = "Condition: state equals the given variant. Renders as `if score <sel> <obj> matches <variant.to_score()>`. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(variant = "`variant` supplies the variant value used to condition state equals the given variant. Renders as `if score <sel> <obj> matches <variant.to_score()>`."),
        returns = "The `Condition` value produced to condition state equals the given variant. Renders as `if score <sel> <obj> matches <variant.to_score()>`.",
        example = "use sand::prelude::*;\n\nfn demonstrate<'a, S : sand::state::TypedGameState + 'static>(game_state_ref_value: &sand::state::GameStateRef < 'a , S >, variant: S)  {\n    let is = game_state_ref_value.is(variant);\n}",
    )]
    pub fn is(&self, variant: S) -> Condition {
        Condition::score(
            self.selector.clone(),
            self.state.objective_name(),
            ScoreRange::Eq(variant.to_score()),
        )
    }

    /// Condition: state does NOT equal the given variant.
    ///
    /// Renders as `unless score <sel> <obj> matches <variant.to_score()>`.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::GameStateRef::is_not",
        aliases = ["sand::prelude::GameStateRef::is_not"],
        module = "sand::state",
        kind = "method",
        summary = "Condition: state does NOT equal the given variant.",
        context = "Condition: state does NOT equal the given variant. Renders as `unless score <sel> <obj> matches <variant.to_score()>`.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(variant = "`variant` supplies the variant value used to condition state does NOT equal the given variant."),
        returns = "The `Condition` value produced to condition state does NOT equal the given variant.",
        example = "use sand::prelude::*;\n\nfn demonstrate<'a, S : sand::state::TypedGameState + 'static>(game_state_ref_value: &sand::state::GameStateRef < 'a , S >, variant: S)  {\n    let is_not = game_state_ref_value.is_not(variant);\n}",
    )]
    pub fn is_not(&self, variant: S) -> Condition {
        !self.is(variant)
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::Cell;

    // ── BossPhase example ─────────────────────────────────────────────────────

    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    enum BossPhase {
        Idle = 0,
        Fighting = 1,
        Enraged = 2,
    }

    impl TypedGameState for BossPhase {
        fn to_score(self) -> i32 {
            self as i32
        }
        fn from_score(n: i32) -> Option<Self> {
            match n {
                0 => Some(Self::Idle),
                1 => Some(Self::Fighting),
                2 => Some(Self::Enraged),
                _ => None,
            }
        }
    }

    static PHASE: GameState<BossPhase> = GameState::new("boss_phase");

    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    struct LocalOnlyState(*const Cell<i32>);

    impl TypedGameState for LocalOnlyState {
        fn to_score(self) -> i32 {
            0
        }

        fn from_score(_n: i32) -> Option<Self> {
            None
        }
    }

    static LOCAL_ONLY: GameState<LocalOnlyState> = GameState::new("local_only");

    #[test]
    fn define_cmd() {
        assert_eq!(PHASE.define(), "scoreboard objectives add boss_phase dummy");
    }

    #[test]
    fn game_state_new_preserves_auto_traits_for_local_only_state() {
        assert_eq!(
            LOCAL_ONLY.define(),
            "scoreboard objectives add local_only dummy"
        );
    }

    #[test]
    fn set_enraged() {
        let cmd = PHASE.of("@s").set(BossPhase::Enraged);
        assert_eq!(cmd, "scoreboard players set @s boss_phase 2");
    }

    #[test]
    fn reset_without_default_clears_score() {
        let cmd = PHASE.of("@s").reset();
        assert_eq!(cmd, "scoreboard players reset @s boss_phase");
    }

    #[test]
    fn clear_always_removes_score() {
        let cmd = PHASE.of("@s").clear();
        assert_eq!(cmd, "scoreboard players reset @s boss_phase");
    }

    #[test]
    fn default_score_is_none_for_new_state() {
        assert_eq!(PHASE.default_score(), None);
    }

    #[test]
    fn is_fighting_condition() {
        let cond = PHASE.of("@s").is(BossPhase::Fighting);
        let cmds = cond.execute_commands(false, "say ok");
        assert_eq!(cmds.len(), 1);
        assert_eq!(
            cmds[0],
            "execute if score @s boss_phase matches 1 run say ok"
        );
    }

    #[test]
    fn is_not_idle_condition_uses_unless() {
        let cond = PHASE.of("@s").is_not(BossPhase::Idle);
        let cmds = cond.execute_commands(false, "say ok");
        assert_eq!(cmds.len(), 1);
        assert!(
            cmds[0].contains("unless"),
            "is_not should render as 'unless', got: {}",
            cmds[0]
        );
        assert!(cmds[0].contains("matches 0"), "got: {}", cmds[0]);
    }

    #[test]
    fn round_trip_from_score() {
        let variant = BossPhase::Enraged;
        let back = BossPhase::from_score(variant.to_score());
        assert_eq!(back, Some(BossPhase::Enraged));
    }

    #[test]
    fn from_score_invalid_returns_none() {
        assert_eq!(BossPhase::from_score(99), None);
        assert_eq!(BossPhase::from_score(-1), None);
    }

    #[test]
    fn long_name_hashed_to_16_chars() {
        // Name > 16 chars should be hashed deterministically to ≤ 16 chars.
        static LONG_STATE: GameState<BossPhase> =
            GameState::new("this_is_a_very_long_state_name_exceeding_limit");
        let name = LONG_STATE.objective_name();
        assert!(
            name.len() <= 16,
            "expected ≤16 chars, got {} chars: {name}",
            name.len()
        );
        // Deterministic — calling again produces the same value.
        assert_eq!(LONG_STATE.objective_name(), name);
        // Hashed names start with 's' (same convention as ScoreVar).
        assert!(
            name.starts_with('s'),
            "hashed name should start with 's', got: {name}"
        );
    }

    // ── MenuState example (second enum showing reusability) ───────────────────

    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    enum MenuState {
        MainMenu = 0,
        Playing = 1,
        Paused = 2,
    }

    impl TypedGameState for MenuState {
        fn to_score(self) -> i32 {
            self as i32
        }
        fn from_score(n: i32) -> Option<Self> {
            match n {
                0 => Some(Self::MainMenu),
                1 => Some(Self::Playing),
                2 => Some(Self::Paused),
                _ => None,
            }
        }
    }

    static MENU: GameState<MenuState> = GameState::new("menu_state");
    static MENU_WITH_DEFAULT: GameState<MenuState> =
        GameState::with_default_score("menu_default", 0);

    #[test]
    fn menu_state_define() {
        assert_eq!(MENU.define(), "scoreboard objectives add menu_state dummy");
    }

    #[test]
    fn menu_state_set_playing() {
        let cmd = MENU.of("@s").set(MenuState::Playing);
        assert_eq!(cmd, "scoreboard players set @s menu_state 1");
    }

    #[test]
    fn with_default_score_records_default_score() {
        assert_eq!(MENU_WITH_DEFAULT.default_score(), Some(0));
    }

    #[test]
    fn reset_with_default_sets_default_variant() {
        let cmd = MENU_WITH_DEFAULT.of("@s").reset();
        assert_eq!(cmd, "scoreboard players set @s menu_default 0");
    }

    #[test]
    fn clear_with_default_still_removes_score() {
        let cmd = MENU_WITH_DEFAULT.of("@s").clear();
        assert_eq!(cmd, "scoreboard players reset @s menu_default");
    }

    #[test]
    fn menu_state_is_paused() {
        let cond = MENU.of("@s").is(MenuState::Paused);
        let cmds = cond.execute_commands(false, "say paused");
        assert_eq!(
            cmds[0],
            "execute if score @s menu_state matches 2 run say paused"
        );
    }

    #[test]
    fn menu_state_round_trip() {
        for variant in [MenuState::MainMenu, MenuState::Playing, MenuState::Paused] {
            assert_eq!(MenuState::from_score(variant.to_score()), Some(variant));
        }
    }
}
