use std::fmt;
use std::str::FromStr;

use serde::{Serialize, Serializer, ser::SerializeMap};

use crate::error::Result;
use crate::registry::{PotionRegistryId, StatusEffectId};
use crate::resource_location::ResourceLocation;

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::state::Ticks",
    aliases = ["sand::prelude::Ticks"],
    module = "sand::state",
    summary = "A duration expressed in Minecraft game ticks (20 ticks = 1 second).",
    context = "A duration expressed in Minecraft game ticks (20 ticks = 1 second). This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
    minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
    use_when = ["Working with typed gameplay state or composing state transitions"],
    avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
    example = "use sand::state::Ticks;",
)]
/// A duration expressed in Minecraft game ticks (20 ticks = 1 second).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct Ticks(u32);

impl Ticks {
    /// Creates a typed tick duration from the supplied tick count.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Ticks::new",
        aliases = ["sand::prelude::Ticks::new"],
        module = "sand::state",
        kind = "method",
        summary = "Creates a typed tick duration from the supplied tick count.",
        context = "Creates a typed tick duration from the supplied tick count. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(ticks = "`ticks` provides the Minecraft tick duration used to create a typed tick duration from the supplied tick count."),
        returns = "A `Ticks` representing a typed tick duration from the supplied tick count.",
        example = "use sand::prelude::*;\n\nfn demonstrate(ticks: u32)  {\n    let ticks = sand::state::Ticks::new(ticks);\n}",
    )]
    pub const fn new(ticks: u32) -> Self {
        Self(ticks)
    }

    /// Convert seconds to ticks (`seconds * 20`).
    ///
    /// Saturates at `u32::MAX` instead of panicking (debug builds) or
    /// silently wrapping (release builds) on overflow — see #148. A duration
    /// large enough to saturate is already far beyond any meaningful game
    /// duration, so clamping is safe and avoids a build-profile-dependent
    /// footgun for a `const fn` used in `static` contexts.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Ticks::seconds",
        aliases = ["sand::prelude::Ticks::seconds"],
        module = "sand::state",
        kind = "method",
        summary = "Convert seconds to ticks (`seconds * 20`). Saturates at `u32::MAX` instead of panicking (debug builds) or silently wrapping (release builds) on overflow — see #148. A duration large enough to saturate is already far beyond any meaningful game duration, so clamping is safe and avoids a build-profile-dependent footgun for a `const fn` used in `static` contexts.",
        context = "Convert seconds to ticks (`seconds * 20`). Saturates at `u32::MAX` instead of panicking (debug builds) or silently wrapping (release builds) on overflow — see #148. A duration large enough to saturate is already far beyond any meaningful game duration, so clamping is safe and avoids a build-profile-dependent footgun for a `const fn` used in `static` contexts. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(seconds = "`seconds` is used to convert seconds to ticks (`seconds * 20`). Saturates at `u32::MAX` instead of panicking (debug builds) or silently wrapping (release builds) on overflow — see #148. A duration large enough to saturate is already far beyond any meaningful game duration, so clamping is safe and avoids a build-profile-dependent footgun for a `const fn` used in `static` contexts."),
        returns = "A `Ticks` representing seconds to ticks (`seconds * 20`). Saturates at `u32::MAX` instead of panicking (debug builds) or silently wrapping (release builds) on overflow — see #148. A duration large enough to saturate is already far beyond any meaningful game duration, so clamping is safe and avoids a build-profile-dependent footgun for a `const fn` used in `static` contexts.",
        example = "use sand::prelude::*;\n\nfn demonstrate(seconds: u32)  {\n    let ticks = sand::state::Ticks::seconds(seconds);\n}",
    )]
    pub const fn seconds(seconds: u32) -> Self {
        Self(seconds.saturating_mul(20))
    }

    /// Convert minutes to ticks (`minutes * 1200`). See [`seconds`](Self::seconds)
    /// for the overflow-saturation policy.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Ticks::minutes",
        aliases = ["sand::prelude::Ticks::minutes"],
        module = "sand::state",
        kind = "method",
        summary = "Convert minutes to ticks (`minutes * 1200`). See [`seconds`](Self::seconds) for the overflow-saturation policy.",
        context = "Convert minutes to ticks (`minutes * 1200`). See [`seconds`](Self::seconds) for the overflow-saturation policy. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        params(minutes = "`minutes` is used to convert minutes to ticks (`minutes * 1200`). See [`seconds`](Self::seconds) for the overflow-saturation policy."),
        returns = "A `Ticks` representing minutes to ticks (`minutes * 1200`). See [`seconds`](Self::seconds) for the overflow-saturation policy.",
        example = "use sand::prelude::*;\n\nfn demonstrate(minutes: u32)  {\n    let ticks = sand::state::Ticks::minutes(minutes);\n}",
    )]
    pub const fn minutes(minutes: u32) -> Self {
        Self(minutes.saturating_mul(1200))
    }

    /// Returns the underlying tick count.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Ticks::get",
        aliases = ["sand::prelude::Ticks::get"],
        module = "sand::state",
        kind = "method",
        summary = "Returns the underlying tick count.",
        context = "Returns the underlying tick count. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Returns the underlying tick count.",
        example = "use sand::prelude::*;\n\nfn demonstrate(ticks_value: sand::state::Ticks)  {\n    let get = ticks_value.get();\n}",
    )]
    pub const fn get(self) -> u32 {
        self.0
    }

    /// Returns this typed tick duration converted to whole seconds.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::state::Ticks::as_seconds",
        aliases = ["sand::prelude::Ticks::as_seconds"],
        module = "sand::state",
        kind = "method",
        summary = "Returns this typed tick duration converted to whole seconds.",
        context = "Returns this typed tick duration converted to whole seconds. This declaration provides the typed scoreboard or lifecycle primitives used directly and by #[derive(State)]; generated schema registration remains private.",
        minecraft = "Operations render validated scoreboard commands or conditions against the selected score holder, with lifecycle setup emitted at load when required.",
        use_when = ["Working with typed gameplay state or composing state transitions"],
        avoid_when = ["Manually reproducing metadata generated by #[derive(State)]"],
        returns = "Returns this typed tick duration converted to whole seconds.",
        example = "use sand::prelude::*;\n\nfn demonstrate(ticks_value: sand::state::Ticks)  {\n    let as_seconds = ticks_value.as_seconds();\n}",
    )]
    pub const fn as_seconds(self) -> u32 {
        self.0 / 20
    }
}

impl fmt::Display for Ticks {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl Serialize for Ticks {
    fn serialize<S: Serializer>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error> {
        serializer.serialize_u32(self.0)
    }
}

macro_rules! vanilla_registry_enum {
    (
        $(#[$meta:meta])*
        $name:ident {
            $($variant:ident => $path:literal),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub enum $name {
            $(
                #[doc = concat!("The vanilla Minecraft `", $path, "` registry entry.")]
                $variant,
            )+
            Custom(ResourceLocation),
        }

        // This macro is the authoritative generator for these facade APIs.
        // Keep the installed catalog beside the generated Rust declarations so
        // a new enum variant cannot become public without contract metadata.
        ::sand_api_contract::inventory::submit! {
            ::sand_api_contract::ApiRegistration {
                canonical_path: concat!("sand::registry::", stringify!($name)),
                aliases: &[concat!("sand::prelude::", stringify!($name))],
                canonical_module: "sand::registry",
                kind: ::sand_api_contract::ApiKind::Enum,
                signature: concat!("pub enum ", stringify!($name)),
                summary: "Names a typed vanilla Minecraft registry entry.",
                context: "This generated enum keeps supported vanilla identifiers discoverable and typo-resistant while retaining an explicit Custom escape hatch for modded data.",
                minecraft: "Serializes to the corresponding Minecraft namespace:path registry identifier.",
                use_when: &["Selecting a known vanilla registry entry", "Passing a typed identifier to a Sand API"],
                avoid_when: &["Representing an arbitrary unvalidated resource location"],
                parameters: &[],
                returns: None,
                example: concat!("let id = sand::registry::", stringify!($name), "::custom(\"example:entry\")?;"),
                availability: &[],
            }
        }

        $(
            ::sand_api_contract::inventory::submit! {
                ::sand_api_contract::ApiRegistration {
                    canonical_path: concat!("sand::registry::", stringify!($name), "::", stringify!($variant)),
                    aliases: &[concat!("sand::prelude::", stringify!($name), "::", stringify!($variant))],
                    canonical_module: "sand::registry",
                    kind: ::sand_api_contract::ApiKind::Variant,
                    signature: concat!(stringify!($variant)),
                    summary: concat!("Selects Minecraft's `", $path, "` registry entry."),
                    context: "This typed variant is the canonical Sand spelling for one built-in Minecraft registry identifier.",
                    minecraft: concat!("Serializes as minecraft:", $path, "."),
                    use_when: &["Using this exact vanilla registry entry"],
                    avoid_when: &["Selecting a different registry entry or a modded identifier"],
                    parameters: &[],
                    returns: None,
                    example: concat!("let id = sand::registry::", stringify!($name), "::", stringify!($variant), ";"),
                    availability: &[],
                }
            }
        )+

        ::sand_api_contract::inventory::submit! {
            ::sand_api_contract::ApiRegistration {
                canonical_path: concat!("sand::registry::", stringify!($name), "::Custom"),
                aliases: &[concat!("sand::prelude::", stringify!($name), "::Custom")],
                canonical_module: "sand::registry",
                kind: ::sand_api_contract::ApiKind::Variant,
                signature: "Custom(ResourceLocation)",
                summary: "Carries a validated custom or modded registry identifier.",
                context: "The Custom variant preserves the typed API when an identifier is not one of Sand's known vanilla entries.",
                minecraft: "Serializes the contained namespace:path registry identifier unchanged.",
                use_when: &["Addressing a modded or otherwise non-vanilla registry entry"],
                avoid_when: &["A named vanilla variant is available"],
                parameters: &[],
                returns: None,
                example: concat!("let id = sand::registry::", stringify!($name), "::custom(\"example:entry\")?;"),
                availability: &[],
            }
        }
        ::sand_api_contract::inventory::submit! {
            ::sand_api_contract::ApiRegistration {
                canonical_path: concat!("sand::registry::", stringify!($name), "::Custom::0"),
                aliases: &[concat!("sand::prelude::", stringify!($name), "::Custom::0")],
                canonical_module: "sand::registry",
                kind: ::sand_api_contract::ApiKind::Field,
                signature: "ResourceLocation",
                summary: "Stores the validated custom registry location.",
                context: "This tuple field is the exact resource location carried by the Custom variant.",
                minecraft: "Uses the stored namespace:path identifier when Sand renders the registry reference.",
                use_when: &["Inspecting a Custom variant's validated location"],
                avoid_when: &["Constructing a built-in variant"],
                parameters: &[],
                returns: None,
                example: concat!("let id = sand::registry::", stringify!($name), "::custom(\"example:entry\")?;"),
                availability: &[],
            }
        }

        impl $name {
            /// Parse and wrap a custom or modded `namespace:path` ID.
            pub fn custom(id: impl AsRef<str>) -> Result<Self> {
                Ok(Self::Custom(id.as_ref().parse()?))
            }

            /// Wrap an already validated resource location as a custom/modded ID.
            pub fn from_resource_location(location: ResourceLocation) -> Self {
                Self::Custom(location)
            }

            pub fn as_resource_location(&self) -> ResourceLocation {
                match self {
                    $(Self::$variant => ResourceLocation::minecraft($path).expect("valid vanilla registry path"),)+
                    Self::Custom(location) => location.clone(),
                }
            }

            pub fn as_str(&self) -> String {
                self.as_resource_location().to_string()
            }
        }

        ::sand_api_contract::inventory::submit! {
            ::sand_api_contract::ApiRegistration {
                canonical_path: concat!("sand::registry::", stringify!($name), "::custom"),
                aliases: &[concat!("sand::prelude::", stringify!($name), "::custom")],
                canonical_module: concat!("sand::registry::", stringify!($name)),
                kind: ::sand_api_contract::ApiKind::Method,
                signature: concat!("pub fn custom(id: impl AsRef<str>) -> Result<", stringify!($name), ">"),
                summary: "Validates and wraps a custom registry identifier.",
                context: "This constructor keeps modded identifiers in the same typed family as known vanilla variants.",
                minecraft: "Validates Minecraft namespace:path syntax before serializing it as a registry reference.",
                use_when: &["Accepting a modded or data-driven registry ID"],
                avoid_when: &["A named vanilla variant is available"],
                parameters: &[::sand_api_contract::StaticApiParameter { name: "id", description: "The custom namespace:path registry identifier." }],
                returns: Some("The typed custom registry identifier, or a validation error."),
                example: concat!("let id = sand::registry::", stringify!($name), "::custom(\"example:entry\")?;"),
                availability: &[],
            }
        }
        ::sand_api_contract::inventory::submit! {
            ::sand_api_contract::ApiRegistration {
                canonical_path: concat!("sand::registry::", stringify!($name), "::from_resource_location"),
                aliases: &[concat!("sand::prelude::", stringify!($name), "::from_resource_location")],
                canonical_module: concat!("sand::registry::", stringify!($name)),
                kind: ::sand_api_contract::ApiKind::Method,
                signature: concat!("pub fn from_resource_location(location: ResourceLocation) -> ", stringify!($name)),
                summary: "Wraps an already validated location as a custom registry identifier.",
                context: "This avoids reparsing when an API already owns a ResourceLocation.",
                minecraft: "Uses the supplied namespace:path location as the registry reference.",
                use_when: &["Converting an existing ResourceLocation into this typed registry family"],
                avoid_when: &["Parsing an unchecked string; use custom instead"],
                parameters: &[::sand_api_contract::StaticApiParameter { name: "location", description: "The validated custom registry location." }],
                returns: Some("The matching Custom enum variant."),
                example: concat!("let id = sand::registry::", stringify!($name), "::from_resource_location(sand::ResourceLocation::minecraft(\"entry\")?);"),
                availability: &[],
            }
        }
        ::sand_api_contract::inventory::submit! {
            ::sand_api_contract::ApiRegistration {
                canonical_path: concat!("sand::registry::", stringify!($name), "::as_resource_location"),
                aliases: &[concat!("sand::prelude::", stringify!($name), "::as_resource_location")],
                canonical_module: concat!("sand::registry::", stringify!($name)),
                kind: ::sand_api_contract::ApiKind::Method,
                signature: "pub fn as_resource_location(&self) -> ResourceLocation",
                summary: "Returns this entry's validated resource location.",
                context: "This is the common typed identity representation used by Sand APIs that accept several registry kinds.",
                minecraft: "Returns the namespace:path value rendered in Minecraft data and commands.",
                use_when: &["Passing this registry entry to an API that accepts ResourceLocation"],
                avoid_when: &["Only display text is needed; use as_str or Display"],
                parameters: &[],
                returns: Some("The corresponding validated resource location."),
                example: concat!("let location = sand::registry::", stringify!($name), "::custom(\"example:entry\")?.as_resource_location();"),
                availability: &[],
            }
        }
        ::sand_api_contract::inventory::submit! {
            ::sand_api_contract::ApiRegistration {
                canonical_path: concat!("sand::registry::", stringify!($name), "::as_str"),
                aliases: &[concat!("sand::prelude::", stringify!($name), "::as_str")],
                canonical_module: concat!("sand::registry::", stringify!($name)),
                kind: ::sand_api_contract::ApiKind::Method,
                signature: "pub fn as_str(&self) -> String",
                summary: "Returns this entry as namespace:path text.",
                context: "Use this at text boundaries after keeping the identifier typed through the rest of the API.",
                minecraft: "Returns the exact registry identifier Minecraft reads.",
                use_when: &["Writing the identifier into a text-only integration"],
                avoid_when: &["Passing a typed registry ID to another Sand API"],
                parameters: &[],
                returns: Some("The namespace:path registry identifier text."),
                example: concat!("let name = sand::registry::", stringify!($name), "::custom(\"example:entry\")?.as_str();"),
                availability: &[],
            }
        }

        impl From<ResourceLocation> for $name {
            fn from(location: ResourceLocation) -> Self {
                Self::Custom(location)
            }
        }

        impl From<$name> for ResourceLocation {
            fn from(id: $name) -> Self {
                id.as_resource_location()
            }
        }

        impl FromStr for $name {
            type Err = crate::error::SandError;

            fn from_str(s: &str) -> Result<Self> {
                match s {
                    $(concat!("minecraft:", $path) => Ok(Self::$variant),)+
                    _ => Ok(Self::Custom(s.parse()?)),
                }
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}", self.as_resource_location())
            }
        }

        impl Serialize for $name {
            fn serialize<S: Serializer>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error> {
                serializer.serialize_str(&self.to_string())
            }
        }
    };
}

vanilla_registry_enum! {
    /// Typed Minecraft status effect identifier.
    EffectId {
        Absorption => "absorption",
        BadOmen => "bad_omen",
        Blindness => "blindness",
        ConduitPower => "conduit_power",
        Darkness => "darkness",
        DolphinGrace => "dolphins_grace",
        FireResistance => "fire_resistance",
        Glowing => "glowing",
        Haste => "haste",
        HealthBoost => "health_boost",
        HeroOfTheVillage => "hero_of_the_village",
        Hunger => "hunger",
        Infested => "infested",
        InstantDamage => "instant_damage",
        InstantHealth => "instant_health",
        Invisibility => "invisibility",
        JumpBoost => "jump_boost",
        Levitation => "levitation",
        Luck => "luck",
        MiningFatigue => "mining_fatigue",
        Nausea => "nausea",
        NightVision => "night_vision",
        Oozing => "oozing",
        Poison => "poison",
        RaidOmen => "raid_omen",
        Regeneration => "regeneration",
        Resistance => "resistance",
        Saturation => "saturation",
        SlowFalling => "slow_falling",
        Slowness => "slowness",
        Speed => "speed",
        Strength => "strength",
        TrialOmen => "trial_omen",
        Unluck => "unluck",
        WaterBreathing => "water_breathing",
        Weakness => "weakness",
        Weaving => "weaving",
        WindCharged => "wind_charged",
        Wither => "wither",
    }
}

impl From<EffectId> for StatusEffectId {
    fn from(id: EffectId) -> Self {
        id.as_resource_location().into()
    }
}

impl From<StatusEffectId> for EffectId {
    fn from(id: StatusEffectId) -> Self {
        Self::from_resource_location(id.into())
    }
}

vanilla_registry_enum! {
    /// Typed Minecraft potion identifier.
    PotionId {
        Water => "water",
        Mundane => "mundane",
        Thick => "thick",
        Awkward => "awkward",
        NightVision => "night_vision",
        LongNightVision => "long_night_vision",
        Invisibility => "invisibility",
        LongInvisibility => "long_invisibility",
        Leaping => "leaping",
        LongLeaping => "long_leaping",
        StrongLeaping => "strong_leaping",
        FireResistance => "fire_resistance",
        LongFireResistance => "long_fire_resistance",
        Swiftness => "swiftness",
        LongSwiftness => "long_swiftness",
        StrongSwiftness => "strong_swiftness",
        Slowness => "slowness",
        LongSlowness => "long_slowness",
        StrongSlowness => "strong_slowness",
        TurtleMaster => "turtle_master",
        LongTurtleMaster => "long_turtle_master",
        StrongTurtleMaster => "strong_turtle_master",
        WaterBreathing => "water_breathing",
        LongWaterBreathing => "long_water_breathing",
        Healing => "healing",
        StrongHealing => "strong_healing",
        Harming => "harming",
        StrongHarming => "strong_harming",
        Poison => "poison",
        LongPoison => "long_poison",
        StrongPoison => "strong_poison",
        Regeneration => "regeneration",
        LongRegeneration => "long_regeneration",
        StrongRegeneration => "strong_regeneration",
        Strength => "strength",
        LongStrength => "long_strength",
        StrongStrength => "strong_strength",
        Weakness => "weakness",
        LongWeakness => "long_weakness",
        Luck => "luck",
        SlowFalling => "slow_falling",
        LongSlowFalling => "long_slow_falling",
    }
}

impl From<PotionId> for PotionRegistryId {
    fn from(id: PotionId) -> Self {
        id.as_resource_location().into()
    }
}

impl From<PotionRegistryId> for PotionId {
    fn from(id: PotionRegistryId) -> Self {
        Self::from_resource_location(id.into())
    }
}

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::component::StatusEffectInstance",
    aliases = ["sand::prelude::StatusEffectInstance"],
    module = "sand::component",
    summary = "Structured status effect instance for item components and datapack JSON.",
    context = "Structured status effect instance for item components and datapack JSON. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
    minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
    use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
    avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
    example = "use sand::component::StatusEffectInstance;",
    fields(effect = "`effect` provides the effect identifier when structured status effect instance for item components and datapack JSON.", show_icon = "`show_icon` provides the show icon when structured status effect instance for item components and datapack JSON.", show_particles = "`show_particles` provides the show particles when structured status effect instance for item components and datapack JSON."),
)]
/// Structured status effect instance for item components and datapack JSON.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StatusEffectInstance {
    /// `effect` provides the effect identifier when structured status effect instance for item components and datapack JSON.
    pub effect: EffectId,
    pub(crate) duration: Option<Ticks>,
    pub(crate) amplifier: u8,
    pub(crate) ambient: bool,
    /// `show_particles` provides the show particles when structured status effect instance for item components and datapack JSON.
    pub show_particles: bool,
    /// `show_icon` provides the show icon when structured status effect instance for item components and datapack JSON.
    pub show_icon: bool,
}

impl StatusEffectInstance {
    /// Create an effect instance from either the enum-style [`EffectId`] or
    /// shared resource-location-backed [`StatusEffectId`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::new",
        aliases = ["sand::prelude::StatusEffectInstance::new"],
        module = "sand::component",
        kind = "method",
        summary = "Create an effect instance from either the enum-style [`EffectId`] or shared resource-location-backed [`StatusEffectId`].",
        context = "Create an effect instance from either the enum-style [`EffectId`] or shared resource-location-backed [`StatusEffectId`]. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(effect = "`effect` is used when creating an effect instance from either the enum-style [`EffectId`] or shared resource-location-backed [`StatusEffectId`]."),
        returns = "A `StatusEffectInstance` representing an effect instance from either the enum-style [`EffectId`] or shared resource-location-backed [`StatusEffectId`].",
        example = "use sand::prelude::*;\n\nfn demonstrate(effect: impl Into < sand::registry::EffectId >)  {\n    let status_effect_instance = sand::component::StatusEffectInstance::new(effect);\n}",
    )]
    pub fn new(effect: impl Into<EffectId>) -> Self {
        Self {
            effect: effect.into(),
            duration: None,
            amplifier: 0,
            ambient: false,
            show_particles: true,
            show_icon: true,
        }
    }

    /// Sets the Minecraft duration property on this typed status effect instance definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::duration",
        aliases = ["sand::prelude::StatusEffectInstance::duration"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft duration property on this typed status effect instance definition and returns the updated builder.",
        context = "Sets the Minecraft duration property on this typed status effect instance definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(duration = "`duration` provides the Minecraft tick duration used to set the Minecraft duration property on this typed status effect instance definition and returns the updated builder."),
        returns = "Sets the Minecraft duration property on this typed status effect instance definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(status_effect_instance_value: sand::component::StatusEffectInstance, duration: sand::state::Ticks)  {\n    let updated_status_effect_instance = status_effect_instance_value.duration(duration);\n}",
    )]
    pub fn duration(mut self, duration: Ticks) -> Self {
        self.duration = Some(duration);
        self
    }

    /// Sets the Minecraft seconds property on this typed status effect instance definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::seconds",
        aliases = ["sand::prelude::StatusEffectInstance::seconds"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft seconds property on this typed status effect instance definition and returns the updated builder.",
        context = "Sets the Minecraft seconds property on this typed status effect instance definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(seconds = "`seconds` provides the seconds applied when setting the Minecraft seconds property on this typed status effect instance definition and returns the updated builder."),
        returns = "Sets the Minecraft seconds property on this typed status effect instance definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(status_effect_instance_value: sand::component::StatusEffectInstance, seconds: u32)  {\n    let updated_status_effect_instance = status_effect_instance_value.seconds(seconds);\n}",
    )]
    pub fn seconds(self, seconds: u32) -> Self {
        self.duration(Ticks::seconds(seconds))
    }

    /// Sets the Minecraft amplifier property on this typed status effect instance definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::amplifier",
        aliases = ["sand::prelude::StatusEffectInstance::amplifier"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft amplifier property on this typed status effect instance definition and returns the updated builder.",
        context = "Sets the Minecraft amplifier property on this typed status effect instance definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(amplifier = "`amplifier` provides the amplifier applied when setting the Minecraft amplifier property on this typed status effect instance definition and returns the updated builder."),
        returns = "Sets the Minecraft amplifier property on this typed status effect instance definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(status_effect_instance_value: sand::component::StatusEffectInstance, amplifier: u8)  {\n    let updated_status_effect_instance = status_effect_instance_value.amplifier(amplifier);\n}",
    )]
    pub fn amplifier(mut self, amplifier: u8) -> Self {
        self.amplifier = amplifier;
        self
    }

    /// Sets the Minecraft ambient property on this typed status effect instance definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::ambient",
        aliases = ["sand::prelude::StatusEffectInstance::ambient"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft ambient property on this typed status effect instance definition and returns the updated builder.",
        context = "Sets the Minecraft ambient property on this typed status effect instance definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(ambient = "`ambient` provides the switch that enables or disables the behavior used to set the Minecraft ambient property on this typed status effect instance definition and returns the updated builder."),
        returns = "Sets the Minecraft ambient property on this typed status effect instance definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(status_effect_instance_value: sand::component::StatusEffectInstance, ambient: bool)  {\n    let updated_status_effect_instance = status_effect_instance_value.ambient(ambient);\n}",
    )]
    pub fn ambient(mut self, ambient: bool) -> Self {
        self.ambient = ambient;
        self
    }

    /// Sets the Minecraft particles property on this typed status effect instance definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::particles",
        aliases = ["sand::prelude::StatusEffectInstance::particles"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft particles property on this typed status effect instance definition and returns the updated builder.",
        context = "Sets the Minecraft particles property on this typed status effect instance definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(show_particles = "`show_particles` provides the switch that enables or disables the behavior used to set the Minecraft particles property on this typed status effect instance definition and returns the updated builder."),
        returns = "Sets the Minecraft particles property on this typed status effect instance definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(status_effect_instance_value: sand::component::StatusEffectInstance, show_particles: bool)  {\n    let updated_status_effect_instance = status_effect_instance_value.particles(show_particles);\n}",
    )]
    pub fn particles(mut self, show_particles: bool) -> Self {
        self.show_particles = show_particles;
        self
    }

    /// Sets the Minecraft icon property on this typed status effect instance definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::icon",
        aliases = ["sand::prelude::StatusEffectInstance::icon"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft icon property on this typed status effect instance definition and returns the updated builder.",
        context = "Sets the Minecraft icon property on this typed status effect instance definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(show_icon = "`show_icon` provides the switch that enables or disables the behavior used to set the Minecraft icon property on this typed status effect instance definition and returns the updated builder."),
        returns = "Sets the Minecraft icon property on this typed status effect instance definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(status_effect_instance_value: sand::component::StatusEffectInstance, show_icon: bool)  {\n    let updated_status_effect_instance = status_effect_instance_value.icon(show_icon);\n}",
    )]
    pub fn icon(mut self, show_icon: bool) -> Self {
        self.show_icon = show_icon;
        self
    }

    /// Returns the canonical Minecraft representation of this component value.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::StatusEffectInstance::to_snbt",
        aliases = ["sand::prelude::StatusEffectInstance::to_snbt"],
        module = "sand::component",
        kind = "method",
        summary = "Returns the canonical Minecraft representation of this component value.",
        context = "Returns the canonical Minecraft representation of this component value. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        returns = "Returns the canonical Minecraft representation of this component value.",
        example = "use sand::prelude::*;\n\nfn demonstrate(status_effect_instance_value: &sand::component::StatusEffectInstance)  {\n    let to_snbt = status_effect_instance_value.to_snbt();\n}",
    )]
    pub fn to_snbt(&self) -> String {
        let mut parts = vec![format!("id:\"{}\"", self.effect)];
        if let Some(duration) = self.duration {
            parts.push(format!("duration:{}", duration.get()));
        }
        if self.amplifier != 0 {
            parts.push(format!("amplifier:{}", self.amplifier));
        }
        if self.ambient {
            parts.push("ambient:true".to_string());
        }
        if !self.show_particles {
            parts.push("show_particles:false".to_string());
        }
        if !self.show_icon {
            parts.push("show_icon:false".to_string());
        }
        format!("{{{}}}", parts.join(","))
    }
}

impl Serialize for StatusEffectInstance {
    fn serialize<S: Serializer>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error> {
        let mut entries = 2;
        entries += usize::from(self.duration.is_some());
        entries += usize::from(self.ambient);
        entries += usize::from(!self.show_particles);
        entries += usize::from(!self.show_icon);

        let mut map = serializer.serialize_map(Some(entries))?;
        map.serialize_entry("id", &self.effect)?;
        if let Some(duration) = self.duration {
            map.serialize_entry("duration", &duration)?;
        }
        map.serialize_entry("amplifier", &self.amplifier)?;
        if self.ambient {
            map.serialize_entry("ambient", &self.ambient)?;
        }
        if !self.show_particles {
            map.serialize_entry("show_particles", &self.show_particles)?;
        }
        if !self.show_icon {
            map.serialize_entry("show_icon", &self.show_icon)?;
        }
        map.end()
    }
}

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::component::PotionContents",
    aliases = ["sand::prelude::PotionContents"],
    module = "sand::component",
    summary = "`minecraft:potion_contents` item component data.",
    context = "`minecraft:potion_contents` item component data. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
    minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
    use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
    avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
    example = "use sand::component::PotionContents;",
    fields(custom_effects = "`custom_effects` provides the custom effects when `minecraft:potion_contents` item component data."),
)]
/// `minecraft:potion_contents` item component data.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
pub struct PotionContents {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) potion: Option<PotionId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) custom_color: Option<u32>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    /// `custom_effects` provides the custom effects when `minecraft:potion_contents` item component data.
    pub custom_effects: Vec<StatusEffectInstance>,
}

impl PotionContents {
    /// Starts empty potion contents with no base potion, custom color, name, or custom effects.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::PotionContents::new",
        aliases = ["sand::prelude::PotionContents::new"],
        module = "sand::component",
        kind = "method",
        summary = "Starts empty potion contents with no base potion, custom color, name, or custom effects.",
        context = "Starts empty potion contents with no base potion, custom color, name, or custom effects. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        returns = "A `PotionContents` initialized to empty potion contents with no base potion, custom color, name, or custom effects.",
        example = "use sand::prelude::*;\n\nfn demonstrate()  {\n    let potion_contents = sand::component::PotionContents::new();\n}",
    )]
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the base potion using either the enum-style [`PotionId`] or shared
    /// resource-location-backed [`PotionRegistryId`].
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::PotionContents::potion",
        aliases = ["sand::prelude::PotionContents::potion"],
        module = "sand::component",
        kind = "method",
        summary = "Set the base potion using either the enum-style [`PotionId`] or shared resource-location-backed [`PotionRegistryId`].",
        context = "Set the base potion using either the enum-style [`PotionId`] or shared resource-location-backed [`PotionRegistryId`]. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(potion = "`potion` provides the potion applied when setting the base potion using either the enum-style [`PotionId`] or shared resource-location-backed [`PotionRegistryId`]."),
        returns = "The `PotionContents` value with the documented change applied to set the base potion using either the enum-style [`PotionId`] or shared resource-location-backed [`PotionRegistryId`].",
        example = "use sand::prelude::*;\n\nfn demonstrate(potion_contents_value: sand::component::PotionContents, potion: impl Into < sand::registry::PotionId >)  {\n    let updated_potion_contents = potion_contents_value.potion(potion);\n}",
    )]
    pub fn potion(mut self, potion: impl Into<PotionId>) -> Self {
        self.potion = Some(potion.into());
        self
    }

    /// Sets the Minecraft custom color property on this typed potion contents definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::PotionContents::custom_color",
        aliases = ["sand::prelude::PotionContents::custom_color"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft custom color property on this typed potion contents definition and returns the updated builder.",
        context = "Sets the Minecraft custom color property on this typed potion contents definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(color = "`color` provides the color applied when setting the Minecraft custom color property on this typed potion contents definition and returns the updated builder."),
        returns = "Sets the Minecraft custom color property on this typed potion contents definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(potion_contents_value: sand::component::PotionContents, color: u32)  {\n    let updated_potion_contents = potion_contents_value.custom_color(color);\n}",
    )]
    pub fn custom_color(mut self, color: u32) -> Self {
        self.custom_color = Some(color);
        self
    }

    /// Sets the Minecraft effect property on this typed potion contents definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::PotionContents::effect",
        aliases = ["sand::prelude::PotionContents::effect"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft effect property on this typed potion contents definition and returns the updated builder.",
        context = "Sets the Minecraft effect property on this typed potion contents definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(effect = "`effect` provides the effect applied when setting the Minecraft effect property on this typed potion contents definition and returns the updated builder."),
        returns = "Sets the Minecraft effect property on this typed potion contents definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(potion_contents_value: sand::component::PotionContents, effect: sand::component::StatusEffectInstance)  {\n    let updated_potion_contents = potion_contents_value.effect(effect);\n}",
    )]
    pub fn effect(mut self, effect: StatusEffectInstance) -> Self {
        self.custom_effects.push(effect);
        self
    }

    /// Sets the Minecraft custom effect property on this typed potion contents definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::PotionContents::custom_effect",
        aliases = ["sand::prelude::PotionContents::custom_effect"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft custom effect property on this typed potion contents definition and returns the updated builder.",
        context = "Sets the Minecraft custom effect property on this typed potion contents definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(effect = "`effect` provides the effect applied when setting the Minecraft custom effect property on this typed potion contents definition and returns the updated builder."),
        returns = "Sets the Minecraft custom effect property on this typed potion contents definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(potion_contents_value: sand::component::PotionContents, effect: sand::component::StatusEffectInstance)  {\n    let updated_potion_contents = potion_contents_value.custom_effect(effect);\n}",
    )]
    pub fn custom_effect(self, effect: StatusEffectInstance) -> Self {
        self.effect(effect)
    }

    /// Returns the canonical Minecraft representation of this component value.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::PotionContents::to_snbt",
        aliases = ["sand::prelude::PotionContents::to_snbt"],
        module = "sand::component",
        kind = "method",
        summary = "Returns the canonical Minecraft representation of this component value.",
        context = "Returns the canonical Minecraft representation of this component value. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        returns = "Returns the canonical Minecraft representation of this component value.",
        example = "use sand::prelude::*;\n\nfn demonstrate(potion_contents_value: &sand::component::PotionContents)  {\n    let to_snbt = potion_contents_value.to_snbt();\n}",
    )]
    pub fn to_snbt(&self) -> String {
        let mut parts = Vec::new();
        if let Some(ref potion) = self.potion {
            parts.push(format!("potion:\"{potion}\""));
        }
        if let Some(color) = self.custom_color {
            parts.push(format!("custom_color:{color}"));
        }
        if !self.custom_effects.is_empty() {
            let effects = self
                .custom_effects
                .iter()
                .map(StatusEffectInstance::to_snbt)
                .collect::<Vec<_>>()
                .join(",");
            parts.push(format!("custom_effects:[{effects}]"));
        }
        format!("{{{}}}", parts.join(","))
    }
}

#[sand_macros::api(
    registry = sand_api_contract,
    path = "sand::component::SuspiciousStewEffect",
    aliases = ["sand::prelude::SuspiciousStewEffect"],
    module = "sand::component",
    summary = "Suspicious stew effect entry. Vanilla's `minecraft:suspicious_stew_effects` component uses the field name `id` for the effect identifier (matching `to_snbt()` below); the JSON (`Serialize`) form is renamed to match so both representations agree — see #148.",
    context = "Suspicious stew effect entry. Vanilla's `minecraft:suspicious_stew_effects` component uses the field name `id` for the effect identifier (matching `to_snbt()` below); the JSON (`Serialize`) form is renamed to match so both representations agree — see #148. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
    minecraft = "Vanilla's `minecraft:suspicious_stew_effects` component uses the field name `id` for the effect identifier (matching `to_snbt()` below); the JSON (`Serialize`) form is renamed to match so both representations agree — see #148.",
    use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
    avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
    example = "use sand::component::SuspiciousStewEffect;",
    fields(duration = "`duration` provides the duration when suspicious stew effect entry. Vanilla's `minecraft:suspicious_stew_effects` component uses the field name `id` for the effect identifier (matching `to_snbt()` below); the JSON (`Serialize`) form is renamed to match so both representations agree — see #148.", effect = "`effect` provides the effect identifier when suspicious stew effect entry. Vanilla's `minecraft:suspicious_stew_effects` component uses the field name `id` for the effect identifier (matching `to_snbt()` below); the JSON (`Serialize`) form is renamed to match so both representations agree — see #148."),
)]
/// Suspicious stew effect entry.
///
/// Vanilla's `minecraft:suspicious_stew_effects` component uses the field
/// name `id` for the effect identifier (matching `to_snbt()` below); the JSON
/// (`Serialize`) form is renamed to match so both representations agree — see #148.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SuspiciousStewEffect {
    #[serde(rename = "id")]
    /// `effect` provides the effect identifier when suspicious stew effect entry. Vanilla's `minecraft:suspicious_stew_effects` component uses the field name `id` for the effect identifier (matching `to_snbt()` below); the JSON (`Serialize`) form is renamed to match so both representations agree — see #148.
    pub effect: EffectId,
    /// `duration` provides the duration when suspicious stew effect entry. Vanilla's `minecraft:suspicious_stew_effects` component uses the field name `id` for the effect identifier (matching `to_snbt()` below); the JSON (`Serialize`) form is renamed to match so both representations agree — see #148.
    pub duration: Ticks,
}

impl SuspiciousStewEffect {
    /// Creates one suspicious-stew status effect with its exact Minecraft tick duration.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::SuspiciousStewEffect::new",
        aliases = ["sand::prelude::SuspiciousStewEffect::new"],
        module = "sand::component",
        kind = "method",
        summary = "Creates one suspicious-stew status effect with its exact Minecraft tick duration.",
        context = "Creates one suspicious-stew status effect with its exact Minecraft tick duration. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(effect = "`effect` is used when creating one suspicious-stew status effect with its exact Minecraft tick duration.", duration = "`duration` provides the Minecraft tick duration used to create one suspicious-stew status effect with its exact Minecraft tick duration."),
        returns = "A `SuspiciousStewEffect` representing one suspicious-stew status effect with its exact Minecraft tick duration.",
        example = "use sand::prelude::*;\n\nfn demonstrate(effect: impl Into < sand::registry::EffectId >, duration: sand::state::Ticks)  {\n    let suspicious_stew_effect = sand::component::SuspiciousStewEffect::new(effect, duration);\n}",
    )]
    pub fn new(effect: impl Into<EffectId>, duration: Ticks) -> Self {
        Self {
            effect: effect.into(),
            duration,
        }
    }

    /// Sets the Minecraft seconds property on this typed suspicious stew effect definition and returns the updated builder.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::SuspiciousStewEffect::seconds",
        aliases = ["sand::prelude::SuspiciousStewEffect::seconds"],
        module = "sand::component",
        kind = "method",
        summary = "Sets the Minecraft seconds property on this typed suspicious stew effect definition and returns the updated builder.",
        context = "Sets the Minecraft seconds property on this typed suspicious stew effect definition and returns the updated builder. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        params(effect = "`effect` provides the effect applied when setting the Minecraft seconds property on this typed suspicious stew effect definition and returns the updated builder.", seconds = "`seconds` provides the seconds applied when setting the Minecraft seconds property on this typed suspicious stew effect definition and returns the updated builder."),
        returns = "Sets the Minecraft seconds property on this typed suspicious stew effect definition and returns the updated builder.",
        example = "use sand::prelude::*;\n\nfn demonstrate(effect: impl Into < sand::registry::EffectId >, seconds: u32)  {\n    let suspicious_stew_effect = sand::component::SuspiciousStewEffect::seconds(effect, seconds);\n}",
    )]
    pub fn seconds(effect: impl Into<EffectId>, seconds: u32) -> Self {
        Self::new(effect, Ticks::seconds(seconds))
    }

    /// Returns the canonical Minecraft representation of this component value.
    #[sand_macros::api(
        registry = sand_api_contract,
        path = "sand::component::SuspiciousStewEffect::to_snbt",
        aliases = ["sand::prelude::SuspiciousStewEffect::to_snbt"],
        module = "sand::component",
        kind = "method",
        summary = "Returns the canonical Minecraft representation of this component value.",
        context = "Returns the canonical Minecraft representation of this component value. This semantic component model describes a datapack resource or gameplay value; JSON serialization and exporter bookkeeping remain implementation details.",
        minecraft = "The value serializes to the matching version-aware Minecraft datapack JSON schema when the project is exported.",
        use_when = ["Defining a typed advancement, recipe, loot table, worldgen resource, item property, or related datapack component"],
        avoid_when = ["Injecting unchecked JSON when the typed schema can represent the resource"],
        returns = "Returns the canonical Minecraft representation of this component value.",
        example = "use sand::prelude::*;\n\nfn demonstrate(suspicious_stew_effect_value: &sand::component::SuspiciousStewEffect)  {\n    let to_snbt = suspicious_stew_effect_value.to_snbt();\n}",
    )]
    pub fn to_snbt(&self) -> String {
        format!(
            "{{id:\"{}\",duration:{}}}",
            self.effect,
            self.duration.get()
        )
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn effect_id_display_and_json() {
        assert_eq!(EffectId::Speed.to_string(), "minecraft:speed");
        assert_eq!(
            serde_json::to_value(EffectId::Regeneration).unwrap(),
            json!("minecraft:regeneration")
        );
    }

    #[test]
    fn effect_id_custom() {
        let id = EffectId::custom("mymod:arcane_burn").unwrap();
        assert_eq!(id.to_string(), "mymod:arcane_burn");
        assert_eq!(
            serde_json::to_value(id).unwrap(),
            json!("mymod:arcane_burn")
        );
    }

    #[test]
    fn generated_registry_method_catalog_signatures_are_declarations() {
        let compiled_surface_items =
            sand_api_contract::inventory::iter::<sand_api_contract::ApiRegistration>
                .into_iter()
                .count();
        let catalog = sand_api_contract::ApiCatalog::from_registrations(
            "test",
            sand_api_contract::ApiConfiguration {
                surface_profile: "test".into(),
                minecraft_version: "test".into(),
                cargo_features: Vec::new(),
                placeholder_codegen: false,
                compiled_surface_items,
            },
            sand_api_contract::inventory::iter::<sand_api_contract::ApiRegistration>,
        )
        .unwrap();
        for (path, signature) in [
            (
                "sand::registry::EffectId::custom",
                "pub fn custom(id: impl AsRef<str>) -> Result<EffectId>",
            ),
            (
                "sand::registry::EffectId::from_resource_location",
                "pub fn from_resource_location(location: ResourceLocation) -> EffectId",
            ),
            (
                "sand::registry::EffectId::as_resource_location",
                "pub fn as_resource_location(&self) -> ResourceLocation",
            ),
            (
                "sand::registry::EffectId::as_str",
                "pub fn as_str(&self) -> String",
            ),
        ] {
            assert_eq!(catalog.find(path).unwrap().signature, signature);
        }
    }

    #[test]
    fn compatibility_ids_convert_to_shared_registry_ids() {
        let effect: StatusEffectId = EffectId::Speed.into();
        let potion: PotionRegistryId = PotionId::LongSwiftness.into();
        assert_eq!(effect.to_string(), "minecraft:speed");
        assert_eq!(potion.to_string(), "minecraft:long_swiftness");

        let effect_compat: EffectId = effect.into();
        let potion_compat: PotionId = potion.into();
        assert_eq!(effect_compat.to_string(), "minecraft:speed");
        assert_eq!(potion_compat.to_string(), "minecraft:long_swiftness");
    }

    #[test]
    fn shared_registry_ids_work_in_existing_effect_builders() {
        let effect = StatusEffectInstance::new(StatusEffectId::minecraft("speed").unwrap());
        let potion = PotionContents::new()
            .potion(PotionRegistryId::minecraft("swiftness").unwrap())
            .effect(effect);
        assert_eq!(
            serde_json::to_value(potion).unwrap(),
            json!({
                "potion": "minecraft:swiftness",
                "custom_effects": [{
                    "id": "minecraft:speed",
                    "amplifier": 0
                }]
            })
        );
    }

    #[test]
    fn status_effect_instance_json_and_snbt() {
        let effect = StatusEffectInstance::new(EffectId::Speed)
            .duration(Ticks::seconds(10))
            .amplifier(1)
            .particles(false);
        assert_eq!(
            serde_json::to_value(&effect).unwrap(),
            json!({
                "id": "minecraft:speed",
                "duration": 200,
                "amplifier": 1,
                "show_particles": false
            })
        );
        assert_eq!(
            effect.to_snbt(),
            "{id:\"minecraft:speed\",duration:200,amplifier:1,show_particles:false}"
        );
    }

    #[test]
    fn potion_contents_json_and_snbt() {
        let contents = PotionContents::new()
            .potion(PotionId::LongSwiftness)
            .custom_color(0x55AAFF)
            .effect(StatusEffectInstance::new(EffectId::Haste).seconds(5));
        assert_eq!(
            serde_json::to_value(&contents).unwrap(),
            json!({
                "potion": "minecraft:long_swiftness",
                "custom_color": 5614335u32,
                "custom_effects": [{
                    "id": "minecraft:haste",
                    "duration": 100,
                    "amplifier": 0
                }]
            })
        );
        assert_eq!(
            contents.to_snbt(),
            "{potion:\"minecraft:long_swiftness\",custom_color:5614335,custom_effects:[{id:\"minecraft:haste\",duration:100}]}"
        );
    }

    #[test]
    fn potion_contents_empty_is_intentionally_permitted() {
        // An empty `minecraft:potion_contents` component (`{}`) is a valid
        // vanilla payload Sand does not reject — locking in current behavior
        // per #148's empty-PotionContents policy note.
        assert_eq!(PotionContents::new().to_snbt(), "{}");
    }

    #[test]
    fn ticks_seconds_and_minutes_saturate_instead_of_overflowing() {
        // #148: previously plain `u32` multiplication, which panics in debug
        // builds and silently wraps in release builds on overflow.
        assert_eq!(Ticks::seconds(u32::MAX).get(), u32::MAX);
        assert_eq!(Ticks::minutes(u32::MAX).get(), u32::MAX);
        // Normal values are unaffected.
        assert_eq!(Ticks::seconds(5).get(), 100);
        assert_eq!(Ticks::minutes(2).get(), 2400);
    }

    #[test]
    fn suspicious_stew_effect_json_and_snbt() {
        let effect = SuspiciousStewEffect::seconds(EffectId::NightVision, 7);
        assert_eq!(
            serde_json::to_value(&effect).unwrap(),
            json!({"id": "minecraft:night_vision", "duration": 140})
        );
        assert_eq!(
            effect.to_snbt(),
            "{id:\"minecraft:night_vision\",duration:140}"
        );
    }
}
