//! Generates a per-version list of real vanilla biome IDs for
//! `sand_core::build`'s registry validation (issue #356, follow-up to
//! #317).
//!
//! Biomes are **data-driven** content, not a network-protocol registry —
//! they never appear in `reports/registries.json` (confirmed empirically:
//! `minecraft:worldgen/biome` is absent from every cached `registries.json`
//! this codebase has generated against). The data generator instead reports
//! them indirectly via `reports/biome_parameters/minecraft/{overworld,
//! nether}.json` — the exact set of biome IDs referenced by each
//! dimension's default multi-noise placement. Unioning both files' `biome`
//! fields gives every Overworld- and Nether-placed biome for the target
//! version, sourced directly from the real data generator output (same
//! `ensure_reports`/cache infrastructure `registries.rs`/`blocks.rs` use —
//! no separate fetch path).
//!
//! The five fixed-position End biomes (`the_end`, `end_highlands`,
//! `end_midlands`, `small_end_islands`, `end_barrens`) use a different,
//! non-noise placement algorithm and never appear in a `biome_parameters`
//! report; they're appended as a small, stable, hand-maintained list (this
//! set has been unchanged since 1.9 and is extremely unlikely to change).

use std::collections::BTreeSet;
use std::path::Path;

use serde::Deserialize;

use crate::error::Result;

/// The five fixed-position End biomes. Not part of any noise-parameter
/// report (see module docs) — stable across every version Sand supports.
const FIXED_END_BIOMES: &[&str] = &[
    "minecraft:the_end",
    "minecraft:end_highlands",
    "minecraft:end_midlands",
    "minecraft:small_end_islands",
    "minecraft:end_barrens",
];

/// The two `biome_parameters` report files that enumerate noise-placed
/// biomes, relative to `reports_dir`.
const BIOME_PARAMETER_REPORTS: &[&str] = &[
    "biome_parameters/minecraft/overworld.json",
    "biome_parameters/minecraft/nether.json",
];

#[derive(Deserialize)]
struct BiomeParameters {
    biomes: Vec<BiomeParameterEntry>,
}

#[derive(Deserialize)]
struct BiomeParameterEntry {
    biome: String,
}

/// Parses both `biome_parameters` reports and writes `biomes.rs` (a
/// `pub(crate) static VANILLA_BIOMES: &[&str]` constant, sorted and
/// deduplicated, plus a `pub(crate) static CODEGEN_MINECRAFT_VERSION: &str`
/// recording exactly which version this data was generated for) to
/// `out_dir`.
///
/// Unlike `registries::generate`, this does not produce a public typed
/// enum or an API-provider manifest — the output is crate-internal
/// validation data for `sand_core::build`, not part of `sand::vanilla`'s
/// authoring surface (see the module docs for why: biomes aren't a stable
/// network registry the way items/blocks are, so a typed
/// `sand::vanilla::Biome` enum is deliberately not part of this issue's
/// scope).
pub fn generate(reports_dir: &Path, out_dir: &Path, minecraft_version: &str) -> Result<()> {
    let mut biomes: BTreeSet<String> = FIXED_END_BIOMES.iter().map(|s| s.to_string()).collect();

    for report in BIOME_PARAMETER_REPORTS {
        let path = reports_dir.join(report);
        let Ok(content) = std::fs::read_to_string(&path) else {
            // A dimension's biome_parameters report can legitimately be
            // absent (e.g. a future version restructures Nether placement)
            // -- skip rather than fail the whole codegen run over one
            // report this module doesn't strictly require.
            continue;
        };
        let parsed: BiomeParameters = serde_json::from_str(&content)?;
        for entry in parsed.biomes {
            biomes.insert(entry.biome);
        }
    }

    let mut code = String::from("// Generated by sand-build. Do not edit manually.\n\n");
    code.push_str("/// The exact Minecraft version this file's data was generated for.\n");
    code.push_str(&format!(
        "pub(crate) static CODEGEN_MINECRAFT_VERSION: &str = {minecraft_version:?};\n\n"
    ));
    code.push_str(
        "/// Real vanilla biome IDs for the target Minecraft version, sourced from\n\
         /// the data generator's `biome_parameters` reports plus the five fixed\n\
         /// End biomes. See `sand-build/src/codegen/biomes.rs` for how this is\n\
         /// derived.\n",
    );
    code.push_str("pub(crate) static VANILLA_BIOMES: &[&str] = &[\n");
    for biome in &biomes {
        code.push_str(&format!("    {biome:?},\n"));
    }
    code.push_str("];\n");

    std::fs::write(out_dir.join("biomes.rs"), code)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unions_overworld_and_nether_reports_plus_fixed_end_biomes() {
        let dir = tempfile::tempdir().unwrap();
        let params_dir = dir.path().join("biome_parameters/minecraft");
        std::fs::create_dir_all(&params_dir).unwrap();
        std::fs::write(
            params_dir.join("overworld.json"),
            r#"{"biomes":[{"biome":"minecraft:plains","parameters":{}},{"biome":"minecraft:desert","parameters":{}}]}"#,
        )
        .unwrap();
        std::fs::write(
            params_dir.join("nether.json"),
            r#"{"biomes":[{"biome":"minecraft:nether_wastes","parameters":{}},{"biome":"minecraft:plains","parameters":{}}]}"#,
        )
        .unwrap();

        let out = tempfile::tempdir().unwrap();
        generate(dir.path(), out.path(), "26.2").unwrap();
        let generated = std::fs::read_to_string(out.path().join("biomes.rs")).unwrap();

        assert!(generated.contains("\"minecraft:plains\""));
        assert!(generated.contains("\"minecraft:desert\""));
        assert!(generated.contains("\"minecraft:nether_wastes\""));
        assert!(generated.contains("\"minecraft:the_end\""));
        assert!(generated.contains("\"minecraft:end_barrens\""));
        // Deduplicated: "minecraft:plains" appears in both reports but
        // should be emitted exactly once.
        assert_eq!(generated.matches("\"minecraft:plains\"").count(), 1);
    }

    #[test]
    fn missing_report_files_do_not_fail_generation() {
        let dir = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        generate(dir.path(), out.path(), "26.2").unwrap();
        let generated = std::fs::read_to_string(out.path().join("biomes.rs")).unwrap();
        // Fixed End biomes are still present even with no reports at all.
        assert!(generated.contains("\"minecraft:the_end\""));
    }
}
