use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write as FmtWrite;
use std::path::Path;

use heck::{ToPascalCase, ToSnakeCase};
use serde::Deserialize;

use crate::error::Result;

#[derive(Deserialize)]
struct BlockData {
    #[serde(default)]
    properties: BTreeMap<String, Vec<String>>,
}

/// How a block property is represented in generated Rust code.
#[derive(Debug, Clone)]
enum PropKind {
    Bool,
    U8,
    Enum(String), // generated enum type name
}

/// Parse `blocks.json` and write `block_states.rs` to `out_dir`.
pub fn generate(reports_dir: &Path, out_dir: &Path) -> Result<()> {
    let path = reports_dir.join("blocks.json");
    let content = std::fs::read_to_string(&path)?;
    let blocks: BTreeMap<String, BlockData> = serde_json::from_str(&content)?;

    // ── Phase 1: collect unique (property_name, sorted_values) pairs ──────────
    // prop_name → set of unique value lists (already sorted).
    let mut name_to_value_sets: HashMap<String, BTreeSet<Vec<String>>> = HashMap::new();

    for block in blocks.values() {
        for (prop_name, values) in &block.properties {
            let mut sorted = values.clone();
            sorted.sort();
            name_to_value_sets
                .entry(prop_name.clone())
                .or_default()
                .insert(sorted);
        }
    }

    // ── Phase 2: assign a PropKind to each (name, sorted_values) key ──────────
    // key = (prop_name, sorted_values)
    let mut prop_map: HashMap<(String, Vec<String>), PropKind> = HashMap::new();

    for (prop_name, value_sets) in &name_to_value_sets {
        let sets: Vec<&Vec<String>> = value_sets.iter().collect();
        let multi = sets.len() > 1;
        for (idx, values) in sets.iter().enumerate() {
            let kind = classify_prop(prop_name, values, multi, idx);
            prop_map.insert((prop_name.clone(), (*values).clone()), kind);
        }
    }

    // ── Phase 3: collect enums to generate (sorted for stable output) ─────────
    // enum_name → sorted values
    let mut enums: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for ((_, values), kind) in &prop_map {
        if let PropKind::Enum(name) = kind {
            enums.entry(name.clone()).or_insert_with(|| values.clone());
        }
    }

    // ── Phase 4: emit source code ─────────────────────────────────────────────
    let mut code = String::new();
    writeln!(code, "// Generated by sand-build. Do not edit manually.").unwrap();
    writeln!(code).unwrap();

    for (enum_name, values) in &enums {
        emit_enum(&mut code, enum_name, values);
    }

    for (block_key, block_data) in &blocks {
        if block_data.properties.is_empty() {
            continue;
        }
        let block_path = block_key
            .split_once(':')
            .map(|(_, p)| p)
            .unwrap_or(block_key);
        let struct_name = format!("{}Properties", block_path.to_pascal_case());
        emit_block_struct(&mut code, &struct_name, &block_data.properties, &prop_map);
    }

    let out_path = out_dir.join("block_states.rs");
    std::fs::write(out_path, code)?;
    Ok(())
}

/// Determine how to represent a property given its name and sorted value list.
fn classify_prop(name: &str, values: &[String], multi: bool, idx: usize) -> PropKind {
    // Bool: exactly the two values "false" and "true" (sorted).
    if values == ["false", "true"] {
        return PropKind::Bool;
    }
    // Numeric: all values parse as u32.
    if values.iter().all(|v| v.parse::<u32>().is_ok()) {
        return PropKind::U8;
    }
    // Enum: derive a type name from the property name.
    let base = name.to_pascal_case();
    let enum_name = if multi {
        format!("{base}{idx}")
    } else {
        base
    };
    PropKind::Enum(enum_name)
}

fn emit_enum(code: &mut String, enum_name: &str, values: &[String]) {
    writeln!(code, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
    writeln!(code, "pub enum {enum_name} {{").unwrap();
    for v in values {
        let variant = value_to_variant(v);
        writeln!(code, "    {variant},").unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    writeln!(code, "impl {enum_name} {{").unwrap();
    writeln!(code, "    pub fn as_str(&self) -> &'static str {{").unwrap();
    writeln!(code, "        match self {{").unwrap();
    for v in values {
        let variant = value_to_variant(v);
        writeln!(code, "            Self::{variant} => {v:?},").unwrap();
    }
    writeln!(code, "        }}").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    writeln!(code, "impl core::fmt::Display for {enum_name} {{").unwrap();
    writeln!(
        code,
        "    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{"
    )
    .unwrap();
    writeln!(code, "        f.write_str(self.as_str())").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();
}

fn emit_block_struct(
    code: &mut String,
    struct_name: &str,
    props: &BTreeMap<String, Vec<String>>,
    prop_map: &HashMap<(String, Vec<String>), PropKind>,
) {
    writeln!(code, "#[derive(Debug, Clone, PartialEq)]").unwrap();
    writeln!(code, "pub struct {struct_name} {{").unwrap();

    for (prop_name, values) in props {
        let mut sorted = values.clone();
        sorted.sort();
        let kind = prop_map
            .get(&(prop_name.clone(), sorted))
            .expect("prop_map must contain all properties");
        let type_str = match kind {
            PropKind::Bool => "bool".to_string(),
            PropKind::U8 => "u8".to_string(),
            PropKind::Enum(name) => name.clone(),
        };
        let field = escape_keyword(&prop_name.to_snake_case());
        writeln!(code, "    pub {field}: {type_str},").unwrap();
    }

    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();
}

/// Convert a property value string like `"north"` to a PascalCase Rust variant.
fn value_to_variant(v: &str) -> String {
    let pascal = v.to_pascal_case();
    if pascal.starts_with(|c: char| c.is_ascii_digit()) {
        format!("_{pascal}")
    } else {
        pascal
    }
}

/// Wrap reserved Rust keywords in a raw identifier.
fn escape_keyword(name: &str) -> String {
    match name {
        "type" | "in" | "ref" | "mod" | "use" | "fn" | "let" | "for" | "if" | "as"
        | "loop" | "match" | "move" | "mut" | "pub" | "return" | "self" | "static"
        | "struct" | "trait" | "where" | "while" => format!("r#{name}"),
        _ => name.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_bool() {
        let kind = classify_prop(
            "open",
            &["false".to_string(), "true".to_string()],
            false,
            0,
        );
        assert!(matches!(kind, PropKind::Bool));
    }

    #[test]
    fn classify_u8() {
        let values: Vec<String> = (0u32..=7).map(|n| n.to_string()).collect();
        let kind = classify_prop("age", &values, false, 0);
        assert!(matches!(kind, PropKind::U8));
    }

    #[test]
    fn classify_enum() {
        let values = vec![
            "east".to_string(),
            "north".to_string(),
            "south".to_string(),
            "west".to_string(),
        ];
        let kind = classify_prop("facing", &values, false, 0);
        assert!(matches!(kind, PropKind::Enum(ref n) if n == "Facing"));
    }

    #[test]
    fn codegen_fixture() {
        let dir = tempfile::tempdir().unwrap();
        let reports = dir.path().join("reports");
        std::fs::create_dir_all(&reports).unwrap();

        let fixture = serde_json::json!({
            "minecraft:oak_door": {
                "properties": {
                    "facing": ["north", "south", "east", "west"],
                    "open": ["true", "false"],
                    "half": ["upper", "lower"],
                    "hinge": ["left", "right"],
                    "powered": ["true", "false"]
                },
                "states": []
            },
            "minecraft:stone": {
                "properties": {},
                "states": [{ "id": 1, "default": true }]
            }
        });
        std::fs::write(reports.join("blocks.json"), fixture.to_string()).unwrap();

        let out = dir.path().join("out");
        std::fs::create_dir_all(&out).unwrap();
        generate(&reports, &out).unwrap();

        let generated = std::fs::read_to_string(out.join("block_states.rs")).unwrap();

        // Shared enums generated
        assert!(generated.contains("pub enum Facing {"));
        assert!(generated.contains("pub enum Half {"));
        assert!(generated.contains("pub enum Hinge {"));
        // Bool properties should NOT produce an enum
        assert!(!generated.contains("pub enum Open {"));
        assert!(!generated.contains("pub enum Powered {"));
        // Block struct generated for oak_door
        assert!(generated.contains("pub struct OakDoorProperties {"));
        // Stone has no properties — no struct
        assert!(!generated.contains("pub struct StoneProperties {"));
        // Field types
        assert!(generated.contains("pub facing: Facing,"));
        assert!(generated.contains("pub open: bool,"));
        assert!(generated.contains("pub powered: bool,"));
    }
}
