use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;
use std::path::Path;

use heck::ToPascalCase;
use serde::Deserialize;

use crate::error::Result;

/// Registries to generate, as `(registry_key, EnumName, doc_comment)`.
const REGISTRIES: &[(&str, &str, &str)] = &[
    ("minecraft:item", "Item", "Minecraft item registry."),
    ("minecraft:block", "Block", "Minecraft block registry."),
    (
        "minecraft:entity_type",
        "EntityType",
        "Minecraft entity type registry.",
    ),
    (
        "minecraft:worldgen/biome",
        "Biome",
        "Minecraft biome registry.",
    ),
    (
        "minecraft:enchantment",
        "Enchantment",
        "Minecraft enchantment registry.",
    ),
    (
        "minecraft:sound_event",
        "SoundEvent",
        "Minecraft sound event registry.",
    ),
];

#[derive(Deserialize)]
struct RegistryData {
    entries: BTreeMap<String, EntryData>,
}

#[derive(Deserialize)]
struct EntryData {
    protocol_id: i32,
}

/// Parse `registries.json` and write `registries.rs` to `out_dir`.
pub fn generate(reports_dir: &Path, out_dir: &Path) -> Result<()> {
    let path = reports_dir.join("registries.json");
    let content = std::fs::read_to_string(&path)?;
    let all: BTreeMap<String, RegistryData> = serde_json::from_str(&content)?;

    let mut code = String::new();
    writeln!(code, "// Generated by sand-build. Do not edit manually.").unwrap();
    writeln!(code).unwrap();

    for &(registry_key, enum_name, doc) in REGISTRIES {
        let Some(registry) = all.get(registry_key) else {
            // Registry absent in this MC version — skip silently.
            continue;
        };

        // Sort entries by protocol_id for a stable, game-order enum.
        let mut entries: Vec<(&String, &EntryData)> = registry.entries.iter().collect();
        entries.sort_by_key(|(_, v)| v.protocol_id);

        write_enum(&mut code, enum_name, doc, &entries);
    }

    let out_path = out_dir.join("registries.rs");
    std::fs::write(out_path, code)?;
    Ok(())
}

fn write_enum(code: &mut String, enum_name: &str, doc: &str, entries: &[(&String, &EntryData)]) {
    writeln!(code, "/// {doc}").unwrap();
    writeln!(code, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
    writeln!(code, "pub enum {enum_name} {{").unwrap();

    for (key, _) in entries {
        let variant = resource_key_to_variant(key);
        writeln!(code, "    {variant},").unwrap();
    }

    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // resource_location() impl
    writeln!(code, "impl {enum_name} {{").unwrap();
    writeln!(
        code,
        "    pub fn resource_location(&self) -> &'static str {{"
    )
    .unwrap();
    writeln!(code, "        match self {{").unwrap();
    for (key, _) in entries {
        let variant = resource_key_to_variant(key);
        writeln!(code, "            Self::{variant} => {key:?},").unwrap();
    }
    writeln!(code, "        }}").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // Display impl
    writeln!(code, "impl core::fmt::Display for {enum_name} {{").unwrap();
    writeln!(
        code,
        "    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{"
    )
    .unwrap();
    writeln!(code, "        f.write_str(self.resource_location())").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();
}

/// Convert a resource location like `"minecraft:oak_log"` to a PascalCase
/// Rust identifier like `OakLog`. Prefixes digit-leading identifiers with `_`.
pub fn resource_key_to_variant(key: &str) -> String {
    // Strip namespace prefix (e.g. `minecraft:`).
    let path = key.split_once(':').map(|(_, p)| p).unwrap_or(key);
    // Replace `/` and `.` with `_` before case conversion.
    let normalized = path.replace(['/', '.'], "_");
    let pascal = normalized.to_pascal_case();
    // Rust identifiers cannot start with a digit.
    if pascal.starts_with(|c: char| c.is_ascii_digit()) {
        format!("_{pascal}")
    } else {
        pascal
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn variant_simple() {
        assert_eq!(resource_key_to_variant("minecraft:air"), "Air");
    }

    #[test]
    fn variant_snake() {
        assert_eq!(resource_key_to_variant("minecraft:oak_log"), "OakLog");
    }

    #[test]
    fn variant_no_namespace() {
        assert_eq!(resource_key_to_variant("stone"), "Stone");
    }

    #[test]
    fn variant_slash_in_path() {
        assert_eq!(
            resource_key_to_variant("minecraft:music_disc/13"),
            "MusicDisc13"
        );
    }

    #[test]
    fn codegen_fixture() {
        let dir = tempfile::tempdir().unwrap();
        let reports = dir.path().join("reports");
        std::fs::create_dir_all(&reports).unwrap();

        let fixture = serde_json::json!({
            "minecraft:item": {
                "entries": {
                    "minecraft:air": { "protocol_id": 0 },
                    "minecraft:stone": { "protocol_id": 1 }
                },
                "protocol_id": 0
            }
        });
        std::fs::write(reports.join("registries.json"), fixture.to_string()).unwrap();

        let out = dir.path().join("out");
        std::fs::create_dir_all(&out).unwrap();
        generate(&reports, &out).unwrap();

        let generated = std::fs::read_to_string(out.join("registries.rs")).unwrap();
        assert!(generated.contains("pub enum Item {"));
        assert!(generated.contains("Air,"));
        assert!(generated.contains("Stone,"));
        assert!(generated.contains("\"minecraft:air\""));
        assert!(generated.contains("\"minecraft:stone\""));
    }
}
