use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;
use std::path::Path;

use heck::ToPascalCase;
use sand_api_contract::{ApiEntry, ApiKind};
use serde::Deserialize;

use crate::api_provider::{ApiProviderCatalog, GeneratedProviderEntry};
use crate::error::Result;

/// Registries to generate, as `(registry_key, EnumName, doc_comment)`.
const REGISTRIES: &[(&str, &str, &str)] = &[
    ("minecraft:item", "Item", "Minecraft item registry."),
    ("minecraft:block", "Block", "Minecraft block registry."),
    (
        "minecraft:entity_type",
        "EntityType",
        "Minecraft entity type registry.",
    ),
    (
        "minecraft:worldgen/biome",
        "Biome",
        "Minecraft biome registry.",
    ),
    (
        "minecraft:enchantment",
        "Enchantment",
        "Minecraft enchantment registry.",
    ),
    (
        "minecraft:sound_event",
        "SoundEvent",
        "Minecraft sound event registry.",
    ),
];

#[derive(Deserialize)]
struct RegistryData {
    entries: BTreeMap<String, EntryData>,
}

#[derive(Deserialize)]
struct EntryData {
    protocol_id: i32,
}

/// Parse `registries.json` and write `registries.rs` to `out_dir`.
pub fn generate(reports_dir: &Path, out_dir: &Path, minecraft_version: &str) -> Result<()> {
    let path = reports_dir.join("registries.json");
    let content = std::fs::read_to_string(&path)?;
    let all: BTreeMap<String, RegistryData> = serde_json::from_str(&content)?;

    let mut code = String::new();
    let mut api_entries = Vec::new();
    writeln!(code, "// Generated by sand-build. Do not edit manually.").unwrap();
    writeln!(code).unwrap();

    for &(registry_key, enum_name, doc) in REGISTRIES {
        let Some(registry) = all.get(registry_key) else {
            // Registry absent in this MC version — skip silently.
            continue;
        };

        // Sort entries by protocol_id for a stable, game-order enum.
        let mut entries: Vec<(&String, &EntryData)> = registry.entries.iter().collect();
        entries.sort_by_key(|(_, v)| v.protocol_id);

        write_enum(&mut code, enum_name, doc, &entries);
        api_entries.extend(enum_api_entries(
            enum_name,
            registry_key,
            &entries,
            minecraft_version,
        ));
    }

    let out_path = out_dir.join("registries.rs");
    std::fs::write(out_path, code)?;
    ApiProviderCatalog::new("generated_registries", minecraft_version, api_entries)
        .write_json(&out_dir.join("registries.api.json"))?;
    Ok(())
}

fn enum_api_entries(
    enum_name: &str,
    registry_key: &str,
    entries: &[(&String, &EntryData)],
    minecraft_version: &str,
) -> Vec<GeneratedProviderEntry> {
    let enum_path = format!("sand::vanilla::{enum_name}");
    let registry_label = registry_key
        .strip_prefix("minecraft:")
        .unwrap_or(registry_key);
    let availability = vec![format!("minecraft = {minecraft_version}")];
    let example_variant = entries.first().map(|(key, _)| resource_key_to_variant(key));
    let enum_example = example_variant.as_ref().map_or_else(
        || format!("let value: Option<sand::vanilla::{enum_name}> = None;"),
        |variant| format!("let value = sand::vanilla::{enum_name}::{variant};"),
    );
    let method_example = example_variant.as_ref().map_or_else(
        || format!("let value: Option<sand::vanilla::{enum_name}> = None;"),
        |variant| format!("let id = sand::vanilla::{enum_name}::{variant}.resource_location();"),
    );
    let mut result = vec![GeneratedProviderEntry {
        definition_identity: format!("sand_core::generated::{enum_name}"),
        definition_kind: ApiKind::Enum,
        parent_identity: None,
        member_name: None,
        contract: ApiEntry {
            canonical_path: enum_path.clone(),
            aliases: Vec::new(),
            canonical_module: "sand::vanilla".into(),
            kind: ApiKind::Enum,
            signature: format!("pub enum {enum_name}"),
            summary: format!("Identifies entries in Minecraft's `{registry_key}` registry."),
            context: format!(
                "Sand generates this typed registry from Minecraft {minecraft_version} data so authors can select vanilla {registry_label} values without spelling resource-location strings."
            ),
            minecraft: format!(
                "Each variant renders the exact namespaced identifier accepted by Minecraft's `{registry_key}` registry."
            ),
            use_when: vec![format!(
                "Selecting a vanilla {registry_label} known to Minecraft {minecraft_version}"
            )],
            avoid_when: vec![format!(
                "Referencing custom or datapack-defined {registry_label} identifiers"
            )],
            parameters: Vec::new(),
            returns: None,
            example: enum_example,
            availability: availability.clone(),
        },
    }];

    result.push(GeneratedProviderEntry {
        definition_identity: format!("sand_core::generated::{enum_name}::resource_location"),
        definition_kind: ApiKind::Method,
        parent_identity: Some(format!("sand_core::generated::{enum_name}")),
        member_name: Some("resource_location".into()),
        contract: ApiEntry {
            canonical_path: format!("{enum_path}::resource_location"),
            aliases: Vec::new(),
            canonical_module: "sand::vanilla".into(),
            kind: ApiKind::Method,
            signature: "pub fn resource_location(&self) -> &'static str".into(),
            summary: format!("Returns this {enum_name} value's exact Minecraft resource location."),
            context: format!(
                "Generated variants retain their source key from the `{registry_key}` registry."
            ),
            minecraft:
                "Returns the namespaced identifier serialized into commands and datapack JSON."
                    .into(),
            use_when: vec!["Passing the vanilla identifier to a raw integration boundary".into()],
            avoid_when: vec!["A Sand API already accepts the typed registry enum directly".into()],
            parameters: Vec::new(),
            returns: Some("The static namespaced identifier from Minecraft's registry.".into()),
            example: method_example,
            availability: availability.clone(),
        },
    });

    result.extend(entries.iter().map(|(key, _)| {
        let variant = resource_key_to_variant(key);
        GeneratedProviderEntry {
            definition_identity: format!("sand_core::generated::{enum_name}::{variant}"),
            definition_kind: ApiKind::Variant,
            parent_identity: Some(format!("sand_core::generated::{enum_name}")),
            member_name: Some(variant.clone()),
            contract: ApiEntry {
            canonical_path: format!("{enum_path}::{variant}"),
            aliases: Vec::new(),
            canonical_module: "sand::vanilla".into(),
            kind: ApiKind::Variant,
            signature: variant.clone(),
            summary: format!("Selects the vanilla registry entry `{key}`."),
            context: format!(
                "This variant is generated from Minecraft {minecraft_version}'s `{registry_key}` registry."
            ),
            minecraft: format!("Serializes as `{key}` wherever this registry value is accepted."),
            use_when: vec![format!("Referring to the vanilla `{key}` entry")],
            avoid_when: vec!["Referring to custom content outside the vanilla registry".into()],
            parameters: Vec::new(),
            returns: None,
            example: format!("let value = sand::vanilla::{enum_name}::{variant};"),
                availability: availability.clone(),
            },
        }
    }));
    result
}

fn write_enum(code: &mut String, enum_name: &str, doc: &str, entries: &[(&String, &EntryData)]) {
    writeln!(code, "/// {doc}").unwrap();
    writeln!(code, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
    writeln!(code, "pub enum {enum_name} {{").unwrap();

    for (key, _) in entries {
        let variant = resource_key_to_variant(key);
        writeln!(code, "    {variant},").unwrap();
    }

    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // resource_location() impl
    writeln!(code, "impl {enum_name} {{").unwrap();
    writeln!(
        code,
        "    pub fn resource_location(&self) -> &'static str {{"
    )
    .unwrap();
    writeln!(code, "        match self {{").unwrap();
    for (key, _) in entries {
        let variant = resource_key_to_variant(key);
        writeln!(code, "            Self::{variant} => {key:?},").unwrap();
    }
    writeln!(code, "        }}").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // Display impl
    writeln!(code, "impl core::fmt::Display for {enum_name} {{").unwrap();
    writeln!(
        code,
        "    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{"
    )
    .unwrap();
    writeln!(code, "        f.write_str(self.resource_location())").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();
}

/// Convert a resource location like `"minecraft:oak_log"` to a PascalCase
/// Rust identifier like `OakLog`. Prefixes digit-leading identifiers with `_`.
pub fn resource_key_to_variant(key: &str) -> String {
    // Strip namespace prefix (e.g. `minecraft:`).
    let path = key.split_once(':').map(|(_, p)| p).unwrap_or(key);
    // Replace `/` and `.` with `_` before case conversion.
    let normalized = path.replace(['/', '.'], "_");
    let pascal = normalized.to_pascal_case();
    // Rust identifiers cannot start with a digit.
    if pascal.starts_with(|c: char| c.is_ascii_digit()) {
        format!("_{pascal}")
    } else {
        pascal
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn variant_simple() {
        assert_eq!(resource_key_to_variant("minecraft:air"), "Air");
    }

    #[test]
    fn variant_snake() {
        assert_eq!(resource_key_to_variant("minecraft:oak_log"), "OakLog");
    }

    #[test]
    fn variant_no_namespace() {
        assert_eq!(resource_key_to_variant("stone"), "Stone");
    }

    #[test]
    fn variant_slash_in_path() {
        assert_eq!(
            resource_key_to_variant("minecraft:music_disc/13"),
            "MusicDisc13"
        );
    }

    #[test]
    fn codegen_fixture() {
        let dir = tempfile::tempdir().unwrap();
        let reports = dir.path().join("reports");
        std::fs::create_dir_all(&reports).unwrap();

        let fixture = serde_json::json!({
            "minecraft:item": {
                "entries": {
                    "minecraft:air": { "protocol_id": 0 },
                    "minecraft:stone": { "protocol_id": 1 }
                },
                "protocol_id": 0
            }
        });
        std::fs::write(reports.join("registries.json"), fixture.to_string()).unwrap();

        let out = dir.path().join("out");
        std::fs::create_dir_all(&out).unwrap();
        generate(&reports, &out, "test-version").unwrap();

        let generated = std::fs::read_to_string(out.join("registries.rs")).unwrap();
        assert!(generated.contains("pub enum Item {"));
        assert!(generated.contains("Air,"));
        assert!(generated.contains("Stone,"));
        assert!(generated.contains("\"minecraft:air\""));
        assert!(generated.contains("\"minecraft:stone\""));

        let provider = crate::read_api_provider(&out.join("registries.api.json")).unwrap();
        assert_eq!(provider.provider, "generated_registries");
        assert_eq!(provider.minecraft_version, "test-version");
        assert_eq!(provider.entries.len(), 4);
        assert!(provider.entries.iter().any(|entry| {
            entry.contract.canonical_path == "sand::vanilla::Item::Stone"
                && entry.contract.minecraft.contains("`minecraft:stone`")
                && entry.definition_identity == "sand_core::generated::Item::Stone"
        }));

        let rust_enum_count = generated
            .lines()
            .filter(|line| line.trim_start().starts_with("pub enum "))
            .count();
        let rust_method_count = generated
            .lines()
            .filter(|line| line.trim_start().starts_with("pub fn resource_location("))
            .count();
        let rust_variant_count = generated
            .lines()
            .filter(|line| {
                let trimmed = line.trim();
                line.starts_with("    ")
                    && !line.starts_with("        ")
                    && trimmed.ends_with(',')
                    && !trimmed.contains(':')
            })
            .count();
        assert_eq!(
            provider.entries.len(),
            rust_enum_count + rust_method_count + rust_variant_count,
            "every generated public enum, variant, and method needs provider metadata"
        );

        let second_out = dir.path().join("out-second");
        std::fs::create_dir_all(&second_out).unwrap();
        generate(&reports, &second_out, "test-version").unwrap();
        assert_eq!(
            std::fs::read(out.join("registries.api.json")).unwrap(),
            std::fs::read(second_out.join("registries.api.json")).unwrap(),
            "provider metadata must be byte-for-byte deterministic"
        );
    }
}
