//! High-level HUD layout compositor.
//!
//! [`HudLayout`] is the recommended way to display one or more HUD elements
//! simultaneously. It:
//!
//! - Accepts any mix of [`BarHandle`]s and [`ElementHandle`]s
//! - Positions each element at an absolute canvas coordinate
//! - Combines everything into a single actionbar text component per command
//!   so multiple elements appear at once without overwriting each other
//! - Handles the scoreboard Cartesian product for multiple dynamic bars
//!
//! # Vertical positioning
//!
//! Horizontal position is set via `canvas_x`. Vertical position is fixed at
//! build time through the `ascent` field in each `hud_bar!` / `hud_element!`
//! call — bars with different `ascent` values appear at different heights.
//! You do **not** need to do anything at display time to control Y position.
//!
//! # Example
//!
//! ```rust,ignore
//! use sand_resourcepack::HudLayout;
//!
//! hud_bar!(
//!     name = "health",
//!     texture = create!(fill = 0xFF4444FF, empty = 0x333333FF),
//!     steps = 20, height = 14, ascent = 14,
//! );
//! hud_bar!(
//!     name = "mana",
//!     texture = create!(fill = 0x4444FFFF, empty = 0x222244FF),
//!     steps = 20, height = 14, ascent = 0,   // lower Y than health
//! );
//!
//! const CANVAS_WIDTH: i32 = 1000;
//!
//! #[component(Tick)]
//! pub fn tick() {
//!     mcfunction! {
//!         // ... scoreboard math ...
//!
//!         HudLayout::new("my_pack", CANVAS_WIDTH)
//!             .bar(HEALTH, "hp_frame", 250)   // health bar at left-quarter
//!             .bar(MANA, "mp_frame", 750)     // mana bar at right-quarter
//!             .broadcast("@a");
//!     }
//! }
//! ```
//!
//! The layout emits `steps_health × steps_mana` combined actionbar commands.
//! For two bars of 20 steps each that is 400 commands — each one checks both
//! scores and renders both bars in a single text component. This is the only
//! correct way to show multiple dynamic bars without them overwriting each
//! other.

use crate::handle::{BarHandle, ElementHandle};
use crate::stat::BarStat;
use crate::unicode::{advance_x, json_escape_chars};

// ── Entry types ───────────────────────────────────────────────────────────────

enum LayoutEntry {
    Bar {
        handle: BarHandle,
        objective: String,
        canvas_x: i32,
    },
    Element {
        handle: ElementHandle,
        canvas_x: i32,
    },
}

impl LayoutEntry {
    fn font(&self) -> &'static str {
        match self {
            LayoutEntry::Bar { handle, .. } => handle.font,
            LayoutEntry::Element { handle, .. } => handle.font,
        }
    }
}

// ── HudLayout ─────────────────────────────────────────────────────────────────

/// Composes multiple HUD bars and elements into a single actionbar command set.
///
/// See the [module-level documentation](crate::layout) for a full walkthrough.
///
/// # Building a layout
///
/// ```rust,ignore
/// let layout = HudLayout::new("my_pack", 1000)
///     .bar(HEALTH, "hp_frame", 250)
///     .element(BORDER, 500);
/// ```
///
/// # Emitting commands
///
/// | Method | When to use |
/// |---|---|
/// | [`broadcast`] | `#[component(Tick)]` — iterates over all players |
/// | [`show_elements`] | Show only static elements (no bar state needed) |
///
/// [`broadcast`]: HudLayout::broadcast
/// [`show_elements`]: HudLayout::show_elements
pub struct HudLayout {
    namespace: String,
    canvas_width: i32,
    entries: Vec<LayoutEntry>,
}

impl HudLayout {
    /// Create a new layout for `namespace` with a virtual canvas of
    /// `canvas_width` units wide.
    ///
    /// `canvas_width / 2` maps to the horizontal screen center. For example,
    /// with `canvas_width = 1000`, `canvas_x = 0` is the far left, `500` is
    /// the center, and `1000` is the far right.
    ///
    /// # Choosing a canvas width
    ///
    /// Any value works; `1000` is a convenient round number. To make
    /// "1 unit = 1 visible pixel" at a specific resolution/scale combination:
    ///
    /// | Resolution | GUI scale | `canvas_width` |
    /// |---|---|---|
    /// | 1920 × 1080 | 2 | 960 |
    /// | 1920 × 1080 | 3 | 640 |
    /// | 2560 × 1440 | 2 | 1280 |
    pub fn new(namespace: impl Into<String>, canvas_width: i32) -> Self {
        Self {
            namespace: namespace.into(),
            canvas_width,
            entries: Vec::new(),
        }
    }

    /// Add a dynamic progress bar to the layout.
    ///
    /// - `handle` — the `BarHandle` constant generated by `hud_bar!`
    /// - `objective` — the scoreboard objective whose value selects the frame
    /// - `canvas_x` — horizontal position (0 = left edge, `canvas_width` = right edge)
    ///
    /// The score at `objective` must be in `0..handle.steps` before the
    /// layout's commands run. Scale and clamp from your raw stat first.
    pub fn bar(mut self, handle: BarHandle, objective: impl Into<String>, canvas_x: i32) -> Self {
        self.entries.push(LayoutEntry::Bar {
            handle,
            objective: objective.into(),
            canvas_x,
        });
        self
    }

    /// Add a static element to the layout.
    ///
    /// - `handle` — the `ElementHandle` constant generated by `hud_element!`
    /// - `canvas_x` — horizontal position
    pub fn element(mut self, handle: ElementHandle, canvas_x: i32) -> Self {
        self.entries.push(LayoutEntry::Element { handle, canvas_x });
        self
    }

    /// Add a [`BarStat`]-tracked bar to the layout.
    ///
    /// Equivalent to `.bar(stat.handle, &stat.frame_obj, canvas_x)` — this is
    /// a convenience shortcut so you don't have to spell out the objective name
    /// yourself when using the `BarStat` API.
    ///
    /// ```rust,ignore
    /// let health = BarStat::health(HEALTH);
    /// HudLayout::new("my_pack", 1000)
    ///     .tracked_bar(&health, 250)
    ///     .broadcast("@a");
    /// ```
    pub fn tracked_bar(self, stat: &BarStat, canvas_x: i32) -> Self {
        self.bar(stat.handle, stat.frame_obj.clone(), canvas_x)
    }

    // ── Internal text building ─────────────────────────────────────────────

    /// Build the combined text string for a specific combination of bar frames.
    ///
    /// Each element is placed using the zero-total-width technique:
    /// `advance_to + char + advance_back` where `advance_back` cancels the
    /// glyph advance, keeping the total string width at 0. With width 0 the
    /// centering origin is exactly at screen center, so `x_offset` pixels
    /// directly maps to font pixels from center.
    fn build_text_for_font(&self, font: &str, bar_frames: &[u32]) -> String {
        let mut text = String::new();
        let mut bar_idx = 0;

        for entry in &self.entries {
            if entry.font() != font {
                // Advance bar_idx even for skipped bars so indexing stays consistent.
                if let LayoutEntry::Bar { .. } = entry {
                    bar_idx += 1;
                }
                continue;
            }

            match entry {
                LayoutEntry::Bar {
                    handle, canvas_x, ..
                } => {
                    let frame = bar_frames[bar_idx];
                    bar_idx += 1;
                    let x = canvas_x - self.canvas_width / 2;
                    let ga = handle.glyph_advance().unwrap_or(1);
                    text.push_str(&advance_x(x));
                    text.push(handle.char(frame));
                    text.push_str(&advance_x(-(x + ga)));
                }
                LayoutEntry::Element { handle, canvas_x } => {
                    let x = canvas_x - self.canvas_width / 2;
                    let ga = handle.glyph_advance().unwrap_or(1);
                    text.push_str(&advance_x(x));
                    text.push(handle.char());
                    text.push_str(&advance_x(-(x + ga)));
                }
            }
        }
        text
    }

    /// Build the full JSON text component for a given bar-frame combination.
    ///
    /// If all entries share one font, produces a single `{"text":...}` object.
    /// If multiple fonts are in use, wraps each font group in an array element
    /// so every group can specify its own font identifier.
    fn build_json(&self, bar_frames: &[u32]) -> String {
        // Collect distinct fonts in insertion order.
        let mut fonts: Vec<&str> = Vec::new();
        for entry in &self.entries {
            let f = entry.font();
            if !fonts.contains(&f) {
                fonts.push(f);
            }
        }

        if fonts.is_empty() {
            return r#"{"text":""}"#.to_string();
        }

        let components: Vec<String> = fonts
            .iter()
            .map(|&font| {
                let text = self.build_text_for_font(font, bar_frames);
                let escaped = json_escape_chars(&text);
                let font_id = format!("{}:{}", self.namespace, font);
                format!(r#"{{"text":"{escaped}","font":"{font_id}","color":"white"}}"#)
            })
            .collect();

        if components.len() == 1 {
            components[0].clone()
        } else {
            format!("[{}]", components.join(","))
        }
    }

    // ── Public command generators ──────────────────────────────────────────

    /// Generate all display commands for a **tick function**.
    ///
    /// `executor` is the player selector, typically `"@a"`. For each player,
    /// Minecraft checks their scores and runs the matching combined command that
    /// renders all bars and elements in one actionbar update.
    ///
    /// **Command count**: the product of all bar `steps` values. Two bars of
    /// 20 steps each → 400 commands. For three bars keep steps ≤ 10 (≤ 1 000
    /// commands total) to stay well within Minecraft's function call budget.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// #[component(Tick)]
    /// pub fn tick() {
    ///     mcfunction! {
    ///         // ... scoreboard math for hp_frame and mp_frame ...
    ///
    ///         HudLayout::new("my_pack", 1000)
    ///             .bar(HEALTH, "hp_frame", 250)
    ///             .bar(MANA,   "mp_frame", 750)
    ///             .broadcast("@a");
    ///     }
    /// }
    /// ```
    pub fn broadcast(&self, executor: &str) -> Vec<String> {
        let bar_entries: Vec<(&BarHandle, &str)> = self
            .entries
            .iter()
            .filter_map(|e| {
                if let LayoutEntry::Bar {
                    handle, objective, ..
                } = e
                {
                    Some((handle, objective.as_str()))
                } else {
                    None
                }
            })
            .collect();

        if bar_entries.is_empty() {
            // Only static elements — one command for all.
            let json = self.build_json(&[]);
            return vec![format!("title {executor} actionbar {json}")];
        }

        let frame_ranges: Vec<Vec<u32>> = bar_entries
            .iter()
            .map(|(h, _)| (0..h.steps).collect())
            .collect();

        cartesian_product(&frame_ranges)
            .into_iter()
            .map(|combo| {
                // Build score conditions: one per bar.
                let conditions: String = combo
                    .iter()
                    .zip(bar_entries.iter())
                    .map(|(frame, (_, obj))| format!("if score @s {obj} matches {frame}..{frame}"))
                    .collect::<Vec<_>>()
                    .join(" ");

                let json = self.build_json(&combo);
                format!("execute as {executor} {conditions} run title @s actionbar {json}")
            })
            .collect()
    }

    /// Generate commands that show only the **static elements** in this layout
    /// (ignoring all bars).
    ///
    /// Useful for a load function or any one-shot display of decorative overlays.
    pub fn show_elements(&self, target: &str) -> Vec<String> {
        // Temporarily create a layout with only the elements.
        let elem_only = HudLayout {
            namespace: self.namespace.clone(),
            canvas_width: self.canvas_width,
            entries: self
                .entries
                .iter()
                .filter_map(|e| {
                    if let LayoutEntry::Element { handle, canvas_x } = e {
                        Some(LayoutEntry::Element {
                            handle: ElementHandle {
                                name: handle.name,
                                font: handle.font,
                                char_width: handle.char_width,
                            },
                            canvas_x: *canvas_x,
                        })
                    } else {
                        None
                    }
                })
                .collect(),
        };

        if elem_only.entries.is_empty() {
            return Vec::new();
        }

        let json = elem_only.build_json(&[]);
        vec![format!("title {target} actionbar {json}")]
    }
}

// ── Cartesian product helper ──────────────────────────────────────────────────

fn cartesian_product(ranges: &[Vec<u32>]) -> Vec<Vec<u32>> {
    if ranges.is_empty() {
        return vec![vec![]];
    }
    let mut result = Vec::new();
    for &item in &ranges[0] {
        for mut combo in cartesian_product(&ranges[1..]) {
            combo.insert(0, item);
            result.push(combo);
        }
    }
    result
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::handle::{BarHandle, ElementHandle};

    const HEALTH: BarHandle = BarHandle {
        name: "health",
        steps: 10,
        font: "hud",
        frame_width: 28,
    };
    const MANA: BarHandle = BarHandle {
        name: "mana",
        steps: 5,
        font: "hud",
        frame_width: 28,
    };
    const BORDER: ElementHandle = ElementHandle {
        name: "border",
        font: "hud",
        char_width: 180,
    };

    #[test]
    fn single_bar_produces_steps_commands() {
        let cmds = HudLayout::new("ns", 1000)
            .bar(HEALTH, "hp_frame", 500)
            .broadcast("@a");
        assert_eq!(cmds.len(), 10); // one per frame
        assert!(cmds[0].contains("execute as @a"));
        assert!(cmds[0].contains("if score @s hp_frame matches 0..0"));
    }

    #[test]
    fn two_bars_produces_cartesian_product() {
        let cmds = HudLayout::new("ns", 1000)
            .bar(HEALTH, "hp_frame", 300)
            .bar(MANA, "mp_frame", 700)
            .broadcast("@a");
        // 10 × 5 = 50 commands
        assert_eq!(cmds.len(), 50);
        // Each command checks both scores.
        assert!(cmds[0].contains("hp_frame"));
        assert!(cmds[0].contains("mp_frame"));
    }

    #[test]
    fn static_only_produces_one_command() {
        let cmds = HudLayout::new("ns", 1000)
            .element(BORDER, 500)
            .broadcast("@a");
        assert_eq!(cmds.len(), 1);
        assert!(cmds[0].starts_with("title @a actionbar"));
    }

    #[test]
    fn show_elements_returns_single_command() {
        let cmds = HudLayout::new("ns", 1000)
            .bar(HEALTH, "hp_frame", 300)
            .element(BORDER, 500)
            .show_elements("@a");
        assert_eq!(cmds.len(), 1);
        assert!(cmds[0].starts_with("title @a actionbar"));
    }

    #[test]
    fn center_position_uses_offset_zero() {
        // canvas_x = canvas_width/2 → x_offset = 0
        // advance_x(0) returns "" so the text has no leading advance chars.
        let cmds = HudLayout::new("ns", 1000)
            .bar(HEALTH, "hp_frame", 500)
            .broadcast("@a");
        // The JSON should contain the bar char directly (no leading advance).
        // We can't inspect the exact unicode escapes portably, but we can check
        // the command is well-formed.
        assert!(cmds[0].contains("\"font\":\"ns:hud\""));
    }

    #[test]
    fn cartesian_product_empty() {
        assert_eq!(
            cartesian_product(&[] as &[Vec<u32>]),
            vec![vec![]] as Vec<Vec<u32>>
        );
    }

    #[test]
    fn cartesian_product_single() {
        let r = cartesian_product(&[vec![0, 1, 2]]);
        assert_eq!(r, vec![vec![0], vec![1], vec![2]]);
    }

    #[test]
    fn cartesian_product_two() {
        let r = cartesian_product(&[vec![0, 1], vec![0, 1, 2]]);
        assert_eq!(r.len(), 6);
    }
}
