#[derive(Debug, Clone)]
pub enum ItemIDs {
    DIRT
}

impl ToString for ItemIDs {
    fn to_string(&self) -> String {
        match self {
            ItemIDs::DIRT => "minecraft:dirt".to_string()
        }
    }
}


#[derive(Debug, Clone)]
pub struct ItemMeta {
    pub attribute_modifiers: Option<String>,
    pub banner_patterns: Option<String>,
    pub base_color: Option<String>,
    pub bees: Option<String>,
    pub block_entity_data: Option<String>,
    pub block_state:  Option<String>,
    pub bucket_entity_data: Option<String>,
    pub bundle_contents: Option<String>,
    pub can_break: Option<String>,
    pub can_place_on: Option<String>,
    pub charged_projectiles: Option<String>,
    pub consumable: Option<String>,
    pub container: Option<String>,
    pub container_loot: Option<String>,
    pub custom_data: Option<String>,
    pub custom_model_data: Option<String>,
    pub damage: Option<f32>,
    pub damage_resistant: Option<String>,
    pub death_protection: Option<String>,
    pub debug_stick_state: Option<String>,
    pub dyed_colors: Option<String>,
    pub enchantable: Option<bool>,
    pub enchantment_glint_override: Option<String>,
    pub enchantments: Option<Vec<String>>,
    pub entity_data: Option<String>,
    pub equippable: Option<bool>,
    pub firework_explosion: Option<String>,
    pub fireworks: Option<String>,
    pub food: Option<String>,
    pub glider: Option<String>,
    pub hde_additional_tooltip: Option<String>,
    pub hide_tooltip: Option<String>,
    pub instrument: Option<String>,
    pub intangible_projectile: Option<String>,
    pub item_model: Option<String>,
    pub item_name: Option<String>,
    pub jukebox_playable: Option<bool>,
    pub lock: Option<bool>,
    pub lodestone_tracker: Option<String>,
    pub lore: Option<Vec<String>>,
    pub map_color: Option<String>,
    pub map_decoration: Option<String>,
    pub map_id: Option<String>,
    pub max_damage: Option<f32>,
    pub max_stack_size: Option<i32>,
    pub note_block_sound: Option<String>,
    pub ominous_bottle_amplifier: Option<String>,
    pub pot_decorations: Option<String>,
    pub potion_contents: Option<String>,
    pub profile: Option<String>,
    pub rarity: Option<String>,
    pub recipes: Option<Vec<String>>,
    pub repair_cost: Option<i32>,
    pub repairable: Option<bool>,
    pub stored_enchantments: Option<Vec<String>>,
    pub suspicious_stew_effects: Option<String>,
    pub tool: Option<String>,
    pub tooltip_style: Option<String>,
    pub trim: Option<String>,
    pub unbreakable: Option<bool>,
    pub use_cooldown: Option<String>,
    pub use_remainder: Option<String>,
    pub writeable_book_content: Option<Vec<String>>,
    pub written_book_content: Option<String>
    
}

impl Default for ItemMeta {
    fn default() -> Self {
        Self {
            attribute_modifiers: None,
            banner_patterns: None,
            base_color: None,
            bees: None,
            block_entity_data: None,
            block_state: None,
            bucket_entity_data: None,
            bundle_contents: None,
            can_break: None,
            can_place_on: None,
            charged_projectiles: None,
            consumable: None,
            container: None,
            container_loot: None,
            custom_data: None,
            custom_model_data: None,
            damage: None,
            damage_resistant: None,
            death_protection: None,
            debug_stick_state: None,
            dyed_colors: None,
            enchantable: None,
            enchantment_glint_override: None,
            enchantments: None,
            entity_data: None,
            equippable: None,
            firework_explosion: None,
            fireworks: None,
            food: None,
            glider: None,
            hde_additional_tooltip: None,
            hide_tooltip: None,
            instrument: None,
            intangible_projectile: None,
            item_model: None,
            item_name: None,
            jukebox_playable: None,
            lock: None,
            lodestone_tracker: None,
            lore: None,
            map_color: None,
            map_decoration: None,
            map_id: None,
            max_damage: None,
            max_stack_size: None,
            note_block_sound: None,
            ominous_bottle_amplifier: None,
            pot_decorations: None,
            potion_contents: None,
            profile: None,
            rarity: None,
            recipes: None,
            repair_cost: None,
            repairable: None,
            stored_enchantments: None,
            suspicious_stew_effects: None,
            tool: None,
            tooltip_style: None,
            trim: None,
            unbreakable: None,
            use_cooldown: None,
            use_remainder: None,
            writeable_book_content: None,
            written_book_content: None
        }
    }
}