#[derive(Debug, Clone)]
pub enum StatusEffects {
    Absorption,
    BadLuck, // unluck
    BadOmen,
    Blindness,
    ConduitPower,
    Darkness,
    DolphinsGrace,
    FireResistance,
    Glowing,
    Haste,
    HealthBoost,
    HeroOfTheVillage,
    Hunger,
    Infested,
    InstantDamage,
    InstantHealth,
    Invisibility,
    JumpBoost,
    MiningFatigue,
    Levitation,
    Luck,
    Nausea,
    NightVision,
    Oozing,
    Poison,
    RaidOmen,
    Regeneration,
    Resistance,
    Saturation,
    SlowFalling,
    Slowness,
    Speed,
    Strength,
    TrialOmen,
    WaterBreathing,
    Weakness,
    Weaving,
    WindCharged,
    Wither,
}

impl ToString for StatusEffects {
    fn to_string(&self) -> String {
        match self {
            StatusEffects::Absorption => "minecraft:absorption".to_string(),
            StatusEffects::BadLuck => "minecraft:unluck".to_string(),
            StatusEffects::BadOmen => "minecraft:bad_omen".to_string(),
            StatusEffects::Blindness => "minecraft:blindness".to_string(),
            StatusEffects::ConduitPower => "minecraft:conduit_power".to_string(),
            StatusEffects::Darkness => "minecraft:darkness".to_string(),
            StatusEffects::DolphinsGrace => "minecraft:dolphins_grace".to_string(),
            StatusEffects::FireResistance => "minecraft:fire_resistance".to_string(),
            StatusEffects::Glowing => "minecraft:glowing".to_string(),
            StatusEffects::Haste => "minecraft:haste".to_string(),
            StatusEffects::HealthBoost => "minecraft:health_boost".to_string(),
            StatusEffects::HeroOfTheVillage => "minecraft:hero_of_the_village".to_string(),
            StatusEffects::Hunger => "minecraft:hunger".to_string(),
            StatusEffects::Infested => "minecraft:infested".to_string(),
            StatusEffects::InstantDamage => "minecraft:instant_damage".to_string(),
            StatusEffects::InstantHealth => "minecraft:instant_health".to_string(),
            StatusEffects::Invisibility => "minecraft:invisibility".to_string(),
            StatusEffects::JumpBoost => "minecraft:jump_boost".to_string(),
            StatusEffects::Levitation => "minecraft:levitation".to_string(),
            StatusEffects::Luck => "minecraft:luck".to_string(),
            StatusEffects::MiningFatigue => "minecraft:mining_fatigue".to_string(),
            StatusEffects::Nausea => "minecraft:nausea".to_string(),
            StatusEffects::NightVision => "minecraft:night_vision".to_string(),
            StatusEffects::Oozing => "minecraft:oozing".to_string(),
            StatusEffects::Poison => "minecraft:poison".to_string(),
            StatusEffects::RaidOmen => "minecraft:raid_omen".to_string(),
            StatusEffects::Regeneration => "minecraft:regeneration".to_string(),
            StatusEffects::Resistance => "minecraft:resistance".to_string(),
            StatusEffects::Saturation => "minecraft:saturation".to_string(),
            StatusEffects::SlowFalling => "minecraft:slow_falling".to_string(),
            StatusEffects::Slowness => "minecraft:slowness".to_string(),
            StatusEffects::Speed => "minecraft:speed".to_string(),
            StatusEffects::Strength => "minecraft:strength".to_string(),
            StatusEffects::TrialOmen => "minecraft:trial_omen".to_string(),
            StatusEffects::WaterBreathing => "minecraft:water_breathing".to_string(),
            StatusEffects::Weakness => "minecraft:weakness".to_string(),
            StatusEffects::Weaving => "minecraft:weaving".to_string(),
            StatusEffects::WindCharged => "minecraft:wind_charged".to_string(),
            StatusEffects::Wither => "minecraft:wither".to_string(),
        }
    }
}