#[derive(Debug, Clone)]
pub enum StatusEffects {
    Absorption,
    BadLuck, // unluck
    BadOmen,
    Blindness,
    ConduitPower,
    Darkness,
    DolphinsGrace,
    FireResistance,
    Glowing,
    Haste,
    HealthBoost,
    HeroOfTheVillage,
    Hunger,
    Infested,
    InstantDamage,
    InstantHealth,
    Invisibility,
    JumpBoost,
    MiningFatigue,
    Levitation,
    Luck,
    Nausea,
    NightVision,
    Oozing,
    Poison,
    RaidOmen,
    Regeneration,
    Resistance,
    Saturation,
    SlowFalling,
    Slowness,
    Speed,
    Strength,
    TrialOmen,
    WaterBreathing,
    Weakness,
    Weaving,
    WindCharged,
    Wither,
}

impl ToString for StatusEffects {
    fn to_string(&self) -> String {
        match self {
            StatusEffects::Absorption => "absorption".to_string(),
            StatusEffects::BadLuck => "unluck".to_string(),
            StatusEffects::BadOmen => "bad_omen".to_string(),
            StatusEffects::Blindness => "blindness".to_string(),
            StatusEffects::ConduitPower => "conduit_power".to_string(),
            StatusEffects::Darkness => "darkness".to_string(),
            StatusEffects::DolphinsGrace => "dolphins_grace".to_string(),
            StatusEffects::FireResistance => "fire_resistance".to_string(),
            StatusEffects::Glowing => "glowing".to_string(),
            StatusEffects::Haste => "haste".to_string(),
            StatusEffects::HealthBoost => "health_boost".to_string(),
            StatusEffects::HeroOfTheVillage => "hero_of_the_village".to_string(),
            StatusEffects::Hunger => "hunger".to_string(),
            StatusEffects::Infested => "infested".to_string(),
            StatusEffects::InstantDamage => "instant_damage".to_string(),
            StatusEffects::InstantHealth => "instant_health".to_string(),
            StatusEffects::Invisibility => "invisibility".to_string(),
            StatusEffects::JumpBoost => "jump_boost".to_string(),
            StatusEffects::Levitation => "levitation".to_string(),
            StatusEffects::Luck => "luck".to_string(),
            StatusEffects::MiningFatigue => "mining_fatigue".to_string(),
            StatusEffects::Nausea => "nausea".to_string(),
            StatusEffects::NightVision => "night_vision".to_string(),
            StatusEffects::Oozing => "oozing".to_string(),
            StatusEffects::Poison => "poison".to_string(),
            StatusEffects::RaidOmen => "raid_omen".to_string(),
            StatusEffects::Regeneration => "regeneration".to_string(),
            StatusEffects::Resistance => "resistance".to_string(),
            StatusEffects::Saturation => "saturation".to_string(),
            StatusEffects::SlowFalling => "slow_falling".to_string(),
            StatusEffects::Slowness => "slowness".to_string(),
            StatusEffects::Speed => "speed".to_string(),
            StatusEffects::Strength => "strength".to_string(),
            StatusEffects::TrialOmen => "trial_omen".to_string(),
            StatusEffects::WaterBreathing => "water_breathing".to_string(),
            StatusEffects::Weakness => "weakness".to_string(),
            StatusEffects::Weaving => "weaving".to_string(),
            StatusEffects::WindCharged => "wind_charged".to_string(),
            StatusEffects::Wither => "wither".to_string(),
        }
    }
}